"""Content the missions read out loud: sentences to retype, things to draw, setup previews.

The typing sentences are the reason this app is genuinely localized rather than merely
translated. A typing mission that shows an English sentence to a Japanese user is not a
challenge, it is a keyboard-layout puzzle, so all four difficulty bands exist in all twelve
languages. Length is matched by *effort*, not by word count: the CJK entries are shorter in
characters because there are no spaces to coast through.

Order of values in every row: en ar de es fr hi it ja ko pt-BR ru zh-Hans
"""

# `TypingChallenge.LengthBand` and its six indices per band. Renaming a band in Swift without
# renaming it here produces a missing key, which is the intent.
SENTENCES = {
    "typing.sentence.short.0": ["The kettle is already on.", "الغلاية تعمل بالفعل.", "Der Wasserkocher läuft schon.", "El agua ya está al fuego.", "La bouilloire est déjà en marche.", "केतली पहले से चालू है।", "Il bollitore è già acceso.", "お湯はもう沸いている。", "물은 이미 끓고 있다.", "A água já está no fogo.", "Чайник уже вскипает.", "水已经在烧了。"],
    "typing.sentence.short.1": ["Daylight beats any alarm.", "ضوء النهار يتفوّق على أي منبه.", "Tageslicht schlägt jeden Alarm.", "La luz del día gana a cualquier alarma.", "La lumière du jour vaut mieux qu’une alarme.", "दिन की रोशनी हर अलार्म से बेहतर है।", "La luce del giorno batte ogni sveglia.", "日の光はどんなアラームにも勝る。", "햇빛은 어떤 알람보다 낫다.", "A luz do dia vence qualquer alarme.", "Дневной свет лучше будильника.", "日光胜过任何闹钟。"],
    "typing.sentence.short.2": ["Cold water wakes the face.", "الماء البارد يوقظ الوجه.", "Kaltes Wasser weckt das Gesicht.", "El agua fría despierta la cara.", "L’eau froide réveille le visage.", "ठंडा पानी चेहरे को जगा देता है।", "L’acqua fredda sveglia il viso.", "冷たい水が顔を起こす。", "찬물이 얼굴을 깨운다.", "Água fria acorda o rosto.", "Холодная вода будит лицо.", "冷水能唤醒一张脸。"],
    "typing.sentence.short.3": ["Nobody regrets rising early.", "لا أحد يندم على الاستيقاظ مبكراً.", "Niemand bedauert frühes Aufstehen.", "Nadie se arrepiente de madrugar.", "Personne ne regrette de se lever tôt.", "जल्दी उठने का पछतावा किसी को नहीं होता।", "Nessuno rimpiange di alzarsi presto.", "早起きを悔やむ人はいない。", "일찍 일어난 걸 후회하는 사람은 없다.", "Ninguém se arrepende de acordar cedo.", "Никто не жалеет, что встал рано.", "没人后悔早起。"],
    "typing.sentence.short.4": ["Your bed is a trap.", "سريرك فخّ.", "Dein Bett ist eine Falle.", "Tu cama es una trampa.", "Votre lit est un piège.", "आपका बिस्तर एक जाल है।", "Il tuo letto è una trappola.", "ベッドは罠だ。", "침대는 함정이다.", "Sua cama é uma armadilha.", "Твоя кровать — это ловушка.", "你的床是个陷阱。"],
    "typing.sentence.short.5": ["Stand up before thinking twice.", "قف قبل أن تفكّر مرتين.", "Steh auf, bevor du nachdenkst.", "Ponte en pie antes de pensarlo.", "Levez-vous avant d’y réfléchir.", "दोबारा सोचने से पहले खड़े हो जाइए।", "Alzati prima di ripensarci.", "考える前に立ち上がれ。", "다시 생각하기 전에 일어서라.", "Fique de pé antes de pensar duas vezes.", "Встань, пока не начал думать.", "别再想，先站起来。"],

    "typing.sentence.medium.0": ["The first hour of the day belongs to you.", "الساعة الأولى من اليوم لك وحدك.", "Die erste Stunde des Tages gehört dir.", "La primera hora del día es tuya.", "La première heure de la journée vous appartient.", "दिन का पहला घंटा आपका होता है।", "La prima ora del giorno è tua.", "1 日の最初の 1 時間はあなたのものだ。", "하루의 첫 시간은 당신 것이다.", "A primeira hora do dia é sua.", "Первый час дня принадлежит тебе.", "一天的第一个小时属于你。"],
    "typing.sentence.medium.1": ["Every morning you win is a small rebellion.", "كل صباح تكسبه هو تمرّد صغير.", "Jeder gewonnene Morgen ist eine kleine Rebellion.", "Cada mañana que ganas es una pequeña rebelión.", "Chaque matin gagné est une petite rébellion.", "जीती हुई हर सुबह एक छोटी बगावत है।", "Ogni mattina che vinci è una piccola rivolta.", "勝ち取った朝は、小さな反抗だ。", "이겨낸 아침마다 작은 반항이 쌓인다.", "Cada manhã que você ganha é uma pequena rebelião.", "Каждое отвоёванное утро — небольшой бунт.", "每个赢下来的早晨都是一次小小的反抗。"],
    "typing.sentence.medium.2": ["Sleep is not the same thing as rest.", "النوم ليس هو الراحة نفسها.", "Schlaf ist nicht dasselbe wie Erholung.", "Dormir no es lo mismo que descansar.", "Dormir n’est pas la même chose que se reposer.", "नींद और आराम एक चीज़ नहीं हैं।", "Dormire non è la stessa cosa che riposare.", "眠ることは休むことと同じではない。", "잠과 휴식은 같은 것이 아니다.", "Dormir não é a mesma coisa que descansar.", "Сон — это не то же самое, что отдых.", "睡觉和休息不是一回事。"],
    "typing.sentence.medium.3": ["You have never regretted getting up on time.", "لم تندم يوماً على الاستيقاظ في الوقت.", "Du hast rechtzeitiges Aufstehen noch nie bedauert.", "Nunca te has arrepentido de levantarte a tiempo.", "Vous n’avez jamais regretté de vous lever à l’heure.", "समय पर उठने का पछतावा आपको कभी नहीं हुआ।", "Non ti sei mai pentito di alzarti in orario.", "時間どおりに起きて後悔したことはない。", "제때 일어나서 후회한 적은 없다.", "Você nunca se arrependeu de levantar na hora.", "Ты ни разу не пожалел, что встал вовремя.", "你从未后悔过按时起床。"],
    "typing.sentence.medium.4": ["Put both feet on the floor and stand.", "ضع قدميك على الأرض وقف.", "Setz beide Füße auf den Boden und steh auf.", "Pon los dos pies en el suelo y levántate.", "Posez les deux pieds au sol et levez-vous.", "दोनों पैर ज़मीन पर रखें और खड़े हो जाएँ।", "Metti entrambi i piedi a terra e alzati.", "両足を床につけて、立ち上がる。", "두 발을 바닥에 대고 일어서라.", "Ponha os dois pés no chão e levante.", "Поставь обе ноги на пол и встань.", "两脚落地，然后站起来。"],
    "typing.sentence.medium.5": ["The day is quiet and it is yours.", "اليوم هادئ، وهو لك.", "Der Tag ist still, und er ist deiner.", "El día está en silencio y es tuyo.", "La journée est calme, et elle est à vous.", "दिन शांत है और वह आपका है।", "Il giorno è silenzioso ed è tuo.", "朝は静かで、そしてあなたのものだ。", "하루는 조용하고, 그것은 당신 것이다.", "O dia está silencioso e é seu.", "День тихий, и он твой.", "清晨很安静，而它是你的。"],

    "typing.sentence.long.0": ["Discipline is choosing what you want most over what you want now.", "الانضباط هو أن تختار ما تريده أكثر بدلاً من ما تريده الآن.", "Disziplin heißt, das Wichtigste über das Jetzige zu stellen.", "La disciplina es elegir lo que más quieres sobre lo que quieres ahora.", "La discipline, c’est choisir ce qu’on veut le plus plutôt que ce qu’on veut maintenant.", "अनुशासन का मतलब है, जो सबसे ज़्यादा चाहिए उसे अभी की चाह से ऊपर रखना।", "La disciplina è scegliere ciò che vuoi di più invece di ciò che vuoi adesso.", "規律とは、いま欲しいものより、いちばん欲しいものを選ぶことだ。", "규율이란 지금 원하는 것보다 가장 원하는 것을 택하는 일이다.", "Disciplina é escolher o que você mais quer em vez do que quer agora.", "Дисциплина — это выбрать то, чего хочешь больше всего, а не то, чего хочется сейчас.", "自律，就是选择你最想要的，而不是你此刻想要的。"],
    "typing.sentence.long.1": ["The alarm did not fail you; you negotiated with it and lost.", "لم يخذلك المنبه، بل تفاوضت معه وخسرت.", "Der Alarm hat nicht versagt; du hast mit ihm verhandelt und verloren.", "La alarma no falló; negociaste con ella y perdiste.", "L’alarme n’a pas failli ; vous avez négocié avec elle et perdu.", "अलार्म ने धोखा नहीं दिया, आपने उससे सौदा किया और हार गए।", "La sveglia non ti ha tradito: hai negoziato con lei e hai perso.", "アラームは裏切っていない。交渉して、あなたが負けただけだ。", "알람이 실패한 게 아니다. 협상하다 당신이 진 것이다.", "O alarme não falhou; você negociou com ele e perdeu.", "Будильник не подвёл — ты с ним поторговался и проиграл.", "闹钟没有失职，是你和它谈判，然后输了。"],
    "typing.sentence.long.2": ["Nothing good has ever come from the fourth press of snooze.", "لم يأتِ خير قط من التأجيل الرابع.", "Aus dem vierten Schlummern ist noch nie etwas Gutes geworden.", "Nunca ha salido nada bueno de la cuarta posposición.", "Rien de bon n’est jamais sorti du quatrième rappel.", "चौथी बार स्नूज़ दबाने से आज तक कुछ अच्छा नहीं निकला।", "Dal quarto posticipo non è mai venuto niente di buono.", "4 回目のスヌーズから、良いことが生まれた例はない。", "네 번째 다시 알림에서 좋은 일이 생긴 적은 없다.", "Nunca saiu nada bom da quarta soneca.", "Из четвёртого нажатия «отложить» ещё ничего хорошего не выходило.", "第四次按下小睡，从没带来什么好事。"],
    "typing.sentence.long.3": ["Morning is the only part of the day nobody else has claimed.", "الصباح هو الجزء الوحيد من اليوم الذي لم يطالب به أحد.", "Der Morgen ist der einzige Teil des Tages, den niemand sonst beansprucht.", "La mañana es la única parte del día que nadie más ha reclamado.", "Le matin est la seule partie de la journée que personne d’autre n’a réclamée.", "सुबह दिन का वह एकमात्र हिस्सा है जिस पर किसी और का दावा नहीं है।", "Il mattino è l’unica parte del giorno che nessun altro ha rivendicato.", "朝は、まだ誰にも取られていない唯一の時間だ。", "아침은 아직 아무도 차지하지 않은 유일한 시간이다.", "A manhã é a única parte do dia que ninguém mais reivindicou.", "Утро — единственная часть дня, которую ещё никто не занял.", "清晨是一天中唯一还没被别人占用的部分。"],
    "typing.sentence.long.4": ["You are three sentences away from the rest of your life.", "تفصلك ثلاث جمل عن بقية حياتك.", "Drei Sätze trennen dich vom Rest deines Lebens.", "Estás a tres frases del resto de tu vida.", "Trois phrases vous séparent du reste de votre vie.", "आपकी बाकी ज़िंदगी से आपको तीन वाक्य अलग करते हैं।", "Ti separano tre frasi dal resto della tua vita.", "残りの人生まで、あと 3 文。", "남은 인생까지 세 문장 거리다.", "Você está a três frases do resto da sua vida.", "От остатка твоей жизни тебя отделяют три фразы.", "距离你余生的开始，只差三句话。"],
    "typing.sentence.long.5": ["A made bed is the first small promise you keep today.", "سرير مرتّب هو أول وعد صغير تفي به اليوم.", "Ein gemachtes Bett ist das erste kleine Versprechen des Tages.", "Una cama hecha es la primera promesa pequeña que cumples hoy.", "Un lit fait est la première petite promesse que vous tenez aujourd’hui.", "बिस्तर ठीक करना आज का पहला छोटा वादा है जो आप निभाते हैं।", "Un letto rifatto è la prima piccola promessa che mantieni oggi.", "整えたベッドは、今日いちばん最初に守る小さな約束だ。", "정돈한 침대는 오늘 지키는 첫 작은 약속이다.", "Uma cama arrumada é a primeira promessa que você cumpre hoje.", "Заправленная кровать — первое небольшое обещание, которое ты сегодня сдержал.", "铺好的床，是你今天守住的第一个小承诺。"],

    "typing.sentence.epic.0": ["The difference between who you are and who you want to be is what you do before eight in the morning.", "الفرق بين ما أنت عليه وما تريد أن تكونه هو ما تفعله قبل الثامنة صباحاً.", "Der Unterschied zwischen dem, was du bist, und dem, was du sein willst, ist das, was du vor acht Uhr tust.", "La diferencia entre quién eres y quién quieres ser es lo que haces antes de las ocho de la mañana.", "La différence entre qui vous êtes et qui vous voulez être, c’est ce que vous faites avant huit heures du matin.", "आप जो हैं और जो बनना चाहते हैं, उसके बीच का फ़र्क वही है जो आप सुबह आठ बजे से पहले करते हैं।", "La differenza tra chi sei e chi vuoi essere è ciò che fai prima delle otto del mattino.", "いまの自分と、なりたい自分の差は、朝 8 時までに何をするかで決まる。", "지금의 당신과 되고 싶은 당신의 차이는 아침 여덟 시 전에 무엇을 하는지에 있다.", "A diferença entre quem você é e quem você quer ser é o que você faz antes das oito da manhã.", "Разница между тем, кто ты есть, и тем, кем хочешь быть, — это то, что ты делаешь до восьми утра.", "你是谁与你想成为谁之间的差别，就在于早上八点前你做了什么。"],
    "typing.sentence.epic.1": ["Somewhere out there another person is already awake, already moving, and not thinking about you at all.", "في مكان ما هناك شخص آخر مستيقظ بالفعل، ويتحرّك بالفعل، ولا يفكّر فيك إطلاقاً.", "Irgendwo da draußen ist jemand schon wach, schon in Bewegung, und denkt überhaupt nicht an dich.", "En algún lugar otra persona ya está despierta, ya se mueve y no piensa en ti en absoluto.", "Quelque part, quelqu’un d’autre est déjà réveillé, déjà en mouvement, et ne pense pas du tout à vous.", "कहीं कोई और पहले से जाग चुका है, चल भी रहा है, और आपके बारे में बिलकुल नहीं सोच रहा।", "Da qualche parte un’altra persona è già sveglia, già in movimento, e non pensa affatto a te.", "どこかで誰かがもう起きて、もう動きだして、あなたのことなど考えていない。", "어딘가에서 다른 누군가는 이미 깨어 움직이고 있고, 당신 생각은 전혀 하지 않는다.", "Em algum lugar outra pessoa já está acordada, já em movimento, e não está pensando em você.", "Где-то другой человек уже проснулся, уже двигается и вовсе не думает о тебе.", "此刻某处已有人醒来、已在行动，而且根本没在想你。"],
    "typing.sentence.epic.2": ["You will not remember this particular morning, but you will remember the year it belonged to.", "لن تتذكّر هذا الصباح بالذات، لكنك ستتذكّر السنة التي كان منها.", "Diesen einzelnen Morgen wirst du nicht erinnern, aber das Jahr, zu dem er gehörte.", "No recordarás esta mañana en concreto, pero recordarás el año al que perteneció.", "Vous ne vous souviendrez pas de ce matin précis, mais vous vous souviendrez de l’année à laquelle il appartenait.", "यह ख़ास सुबह आपको याद नहीं रहेगी, लेकिन वह साल याद रहेगा जिसका यह हिस्सा थी।", "Non ricorderai questa mattina in particolare, ma ricorderai l’anno a cui apparteneva.", "この朝そのものは覚えていないだろうが、この朝が属した一年は覚えている。", "이 아침 자체는 기억나지 않겠지만, 이 아침이 속한 해는 기억할 것이다.", "Você não vai lembrar desta manhã em particular, mas vai lembrar do ano a que ela pertenceu.", "Именно это утро ты не запомнишь, но запомнишь год, к которому оно относилось.", "你不会记得这个具体的早晨，但你会记得它属于的那一年。"],
    "typing.sentence.epic.3": ["Getting up is not a feeling you wait for; it is a decision you make while cold.", "الاستيقاظ ليس شعوراً تنتظره، بل قراراً تتخذه وأنت تشعر بالبرد.", "Aufstehen ist kein Gefühl, auf das man wartet, sondern eine Entscheidung, die man frierend trifft.", "Levantarse no es un sentimiento que esperas, es una decisión que tomas con frío.", "Se lever n’est pas un sentiment qu’on attend : c’est une décision qu’on prend en ayant froid.", "उठना कोई एहसास नहीं जिसका इंतज़ार किया जाए, यह ठंड में लिया गया फ़ैसला है।", "Alzarsi non è una sensazione che aspetti: è una decisione che prendi al freddo.", "起きることは待つべき気分ではなく、寒さの中で下す決断だ。", "일어남은 기다릴 감정이 아니라, 추운 채로 내리는 결정이다.", "Levantar não é um sentimento que você espera; é uma decisão que você toma com frio.", "Подъём — это не чувство, которого ждут, а решение, которое принимают, замерзая.", "起床不是一种等来的感觉，而是在寒意里做出的决定。"],
    "typing.sentence.epic.4": ["Every hour you take back from sleep is an hour nobody else can schedule a meeting in.", "كل ساعة تستعيدها من النوم هي ساعة لا يستطيع أحد أن يحجز فيها اجتماعاً.", "Jede Stunde, die du dem Schlaf abringst, ist eine Stunde, in die niemand ein Meeting legen kann.", "Cada hora que le quitas al sueño es una hora en la que nadie puede ponerte una reunión.", "Chaque heure reprise au sommeil est une heure où personne ne peut vous caler une réunion.", "नींद से छीना हर घंटा वह घंटा है जिसमें कोई आपकी मीटिंग नहीं रख सकता।", "Ogni ora che togli al sonno è un’ora in cui nessuno può fissarti una riunione.", "眠りから取り戻した 1 時間は、誰も会議を入れられない 1 時間だ。", "잠에서 되찾은 한 시간은 누구도 회의를 잡을 수 없는 한 시간이다.", "Cada hora que você tira do sono é uma hora em que ninguém pode marcar uma reunião.", "Каждый час, отобранный у сна, — это час, в который никто не назначит совещание.", "你从睡眠里夺回的每一小时，都是没人能安排会议的一小时。"],
    "typing.sentence.epic.5": ["The body follows the body: stand up first, and the willingness arrives about ninety seconds later.", "الجسد يتبع الجسد: قف أولاً، وستأتي الرغبة بعد تسعين ثانية تقريباً.", "Der Körper folgt dem Körper: steh erst auf, die Bereitschaft kommt neunzig Sekunden später.", "El cuerpo sigue al cuerpo: levántate primero y las ganas llegan unos noventa segundos después.", "Le corps suit le corps : levez-vous d’abord, l’envie arrive quatre-vingt-dix secondes plus tard.", "शरीर शरीर का अनुसरण करता है: पहले खड़े हों, इच्छा करीब नब्बे सेकंड बाद आ जाएगी।", "Il corpo segue il corpo: alzati prima, e la voglia arriva novanta secondi dopo.", "体は体に従う。まず立ち上がれば、やる気は 90 秒ほど遅れてやって来る。", "몸은 몸을 따른다. 먼저 일어서면 의욕은 구십 초쯤 뒤에 온다.", "O corpo segue o corpo: levante primeiro, e a vontade chega uns noventa segundos depois.", "Тело следует за телом: сначала встань, а желание придёт секунд через девяносто.", "身体听从身体：先站起来，意愿大约九十秒后才到。"],
}

# `DrawingPrompt.nameKey`. The English word here also has to match what Vision labels the
# object, which is why the list is deliberately made of things a classifier is good at.
DRAW_PROMPTS = {
    "draw.prompt.boat": ["boat", "قارب", "Boot", "barco", "bateau", "नाव", "barca", "船", "배", "barco", "лодка", "船"],
    "draw.prompt.car": ["car", "سيارة", "Auto", "coche", "voiture", "कार", "auto", "車", "자동차", "carro", "машина", "汽车"],
    "draw.prompt.cat": ["cat", "قطة", "Katze", "gato", "chat", "बिल्ली", "gatto", "猫", "고양이", "gato", "кот", "猫"],
    "draw.prompt.clock": ["clock", "ساعة", "Uhr", "reloj", "horloge", "घड़ी", "orologio", "時計", "시계", "relógio", "часы", "钟"],
    "draw.prompt.cup": ["cup", "كوب", "Tasse", "taza", "tasse", "कप", "tazza", "カップ", "컵", "copo", "чашка", "杯子"],
    "draw.prompt.fish": ["fish", "سمكة", "Fisch", "pez", "poisson", "मछली", "pesce", "魚", "물고기", "peixe", "рыба", "鱼"],
    "draw.prompt.flower": ["flower", "زهرة", "Blume", "flor", "fleur", "फूल", "fiore", "花", "꽃", "flor", "цветок", "花"],
    "draw.prompt.heart": ["heart", "قلب", "Herz", "corazón", "cœur", "दिल", "cuore", "ハート", "하트", "coração", "сердце", "心形"],
    "draw.prompt.house": ["house", "منزل", "Haus", "casa", "maison", "घर", "casa", "家", "집", "casa", "дом", "房子"],
    "draw.prompt.key": ["key", "مفتاح", "Schlüssel", "llave", "clé", "चाबी", "chiave", "鍵", "열쇠", "chave", "ключ", "钥匙"],
    "draw.prompt.moon": ["moon", "قمر", "Mond", "luna", "lune", "चाँद", "luna", "月", "달", "lua", "луна", "月亮"],
    "draw.prompt.star": ["star", "نجمة", "Stern", "estrella", "étoile", "तारा", "stella", "星", "별", "estrela", "звезда", "星星"],
    "draw.prompt.sun": ["sun", "شمس", "Sonne", "sol", "soleil", "सूरज", "sole", "太陽", "해", "sol", "солнце", "太阳"],
    "draw.prompt.tree": ["tree", "شجرة", "Baum", "árbol", "arbre", "पेड़", "albero", "木", "나무", "árvore", "дерево", "树"],
    "draw.prompt.umbrella": ["umbrella", "مظلة", "Regenschirm", "paraguas", "parapluie", "छाता", "ombrello", "傘", "우산", "guarda-chuva", "зонт", "雨伞"],
    "draw.prompt.bicycle": ["bicycle", "دراجة", "Fahrrad", "bicicleta", "vélo", "साइकिल", "bicicletta", "自転車", "자전거", "bicicleta", "велосипед", "自行车"],
}

# The one-line summary under each mission in the editor: exactly what this alarm will demand.
PREVIEWS = {
    "preview.math": ["%lld-digit sums", "أعداد من %lld خانات", "%lld-stellige Aufgaben", "Cuentas de %lld cifras", "Calculs à %lld chiffres", "%lld अंकों के सवाल", "Calcoli a %lld cifre", "%lld 桁の計算", "%lld자리 계산", "Contas de %lld dígitos", "Примеры из %lld цифр", "%lld 位数运算"],
    "preview.memory": ["%1$lld tiles on a %2$lld×%3$lld grid", "%1$lld مربعات في شبكة %2$lld×%3$lld", "%1$lld Felder auf %2$lld×%3$lld", "%1$lld casillas en una rejilla %2$lld×%3$lld", "%1$lld cases sur une grille %2$lld×%3$lld", "%2$lld×%3$lld ग्रिड में %1$lld टाइल", "%1$lld caselle su una griglia %2$lld×%3$lld", "%2$lld×%3$lld のマスに %1$lld 個", "%2$lld×%3$lld 격자에서 %1$lld칸", "%1$lld quadros numa grade %2$lld×%3$lld", "%1$lld плиток на поле %2$lld×%3$lld", "%2$lld×%3$lld 网格中的 %1$lld 格"],
    "preview.sequence": ["%lld-step pattern", "نمط من %lld خطوات", "Muster mit %lld Schritten", "Patrón de %lld pasos", "Motif de %lld étapes", "%lld चरणों का पैटर्न", "Sequenza di %lld passi", "%lld ステップのパターン", "%lld단계 패턴", "Padrão de %lld passos", "Рисунок из %lld шагов", "%lld 步的图案"],
    "preview.typing": ["Sentences of about %lld words", "جمل من نحو %lld كلمات", "Sätze mit etwa %lld Wörtern", "Frases de unas %lld palabras", "Phrases d’environ %lld mots", "लगभग %lld शब्दों के वाक्य", "Frasi di circa %lld parole", "約 %lld 語の文章", "약 %lld 단어 문장", "Frases de cerca de %lld palavras", "Фразы примерно из %lld слов", "约 %lld 个词的句子"],
    "preview.shake": ["%lld shakes", "%lld رجّة", "%lld× schütteln", "%lld sacudidas", "%lld secousses", "%lld बार हिलाना", "%lld scosse", "シェイク %lld 回", "흔들기 %lld회", "%lld sacudidas", "%lld встряхиваний", "摇动 %lld 次"],
    "preview.steps": ["%lld steps", "%lld خطوة", "%lld Schritte", "%lld pasos", "%lld pas", "%lld कदम", "%lld passi", "%lld 歩", "%lld걸음", "%lld passos", "%lld шагов", "%lld 步"],
    "preview.squats": ["%lld squats", "%lld قرفصاء", "%lld Kniebeugen", "%lld sentadillas", "%lld squats", "%lld स्क्वैट", "%lld squat", "スクワット %lld 回", "스쿼트 %lld회", "%lld agachamentos", "%lld приседаний", "深蹲 %lld 次"],
    "preview.photo": ["Photograph %@", "صوّر %@", "%@ fotografieren", "Fotografiar %@", "Photographier %@", "%@ की फ़ोटो लेना", "Fotografare %@", "%@ を撮影", "%@ 촬영", "Fotografar %@", "Сфотографировать %@", "拍摄%@"],
    "preview.photo.unset": ["an object you have not picked yet", "شيء لم تختره بعد", "ein noch nicht gewähltes Objekt", "un objeto que aún no has elegido", "un objet que vous n’avez pas encore choisi", "एक चीज़ जो आपने अभी नहीं चुनी", "un oggetto non ancora scelto", "まだ選んでいないモノ", "아직 고르지 않은 물건", "um objeto que você ainda não escolheu", "предмет, который вы ещё не выбрали", "你还没选的物品"],
    "preview.barcode": ["Scan %@", "امسح %@", "%@ scannen", "Escanear %@", "Scanner %@", "%@ स्कैन करना", "Scansionare %@", "%@ をスキャン", "%@ 스캔", "Escanear %@", "Отсканировать %@", "扫描%@"],
    "preview.barcode.unset": ["a code you have not scanned yet", "رمز لم تمسحه بعد", "ein noch nicht gescannter Code", "un código que aún no has escaneado", "un code que vous n’avez pas encore scanné", "एक कोड जो आपने अभी स्कैन नहीं किया", "un codice non ancora scansionato", "まだスキャンしていないコード", "아직 스캔하지 않은 코드", "um código que você ainda não escaneou", "код, который вы ещё не сканировали", "你还没扫过的条码"],
    "preview.draw": ["A different object each round", "شيء مختلف كل جولة", "Jede Runde ein anderes Motiv", "Un objeto distinto en cada ronda", "Un objet différent à chaque manche", "हर राउंड में अलग चीज़", "Un oggetto diverso a ogni turno", "ラウンドごとに違うお題", "라운드마다 다른 주제", "Um objeto diferente por rodada", "В каждом раунде свой предмет", "每轮换一个题目"],
    "preview.flap": ["%lld gaps to clear", "%lld فتحات لتعبرها", "%lld Lücken schaffen", "%lld huecos que pasar", "%lld passages à franchir", "%lld गैप पार करने हैं", "%lld aperture da superare", "隙間 %lld 個を通過", "틈 %lld개 통과", "%lld vãos para passar", "%lld проходов", "穿过 %lld 个缝隙"],
    "preview.breathe": ["%lld guided breaths", "%lld أنفاس موجّهة", "%lld geführte Atemzüge", "%lld respiraciones guiadas", "%lld respirations guidées", "%lld निर्देशित साँसें", "%lld respiri guidati", "ガイド付き呼吸 %lld 回", "안내 호흡 %lld회", "%lld respirações guiadas", "%lld направляемых вдохов", "%lld 次引导呼吸"],
    "preview.roundsSuffix": ["%lld rounds", "%lld جولات", "%lld Runden", "%lld rondas", "%lld manches", "%lld राउंड", "%lld turni", "%lld ラウンド", "%lld라운드", "%lld rodadas", "%lld раунда", "%lld 轮"],
}
