"""The twelve missions: their names in the picker, and every string they show while running.

Order of values in every row: en ar de es fr hi it ja ko pt-BR ru zh-Hans
"""

from . import family

TITLES = family("mission.", ".title", {
    "math": ["Math", "حساب", "Rechnen", "Cálculo", "Calcul", "गणित", "Calcoli", "計算", "계산", "Cálculo", "Математика", "算术"],
    "memory": ["Memory", "ذاكرة", "Gedächtnis", "Memoria", "Mémoire", "स्मृति", "Memoria", "記憶", "기억력", "Memória", "Память", "记忆"],
    "sequence": ["Sequence", "تسلسل", "Sequenz", "Secuencia", "Séquence", "क्रम", "Sequenza", "順番", "순서", "Sequência", "Последовательность", "序列"],
    "typing": ["Typing", "كتابة", "Tippen", "Escritura", "Frappe", "टाइपिंग", "Digitazione", "タイピング", "타이핑", "Digitação", "Набор текста", "打字"],
    "shake": ["Shake", "رجّ", "Schütteln", "Agitar", "Secouer", "हिलाना", "Scuoti", "シェイク", "흔들기", "Agitar", "Встряхивание", "摇一摇"],
    "steps": ["Steps", "خطوات", "Schritte", "Pasos", "Pas", "कदम", "Passi", "歩数", "걸음", "Passos", "Шаги", "步数"],
    "squats": ["Squats", "قرفصاء", "Kniebeugen", "Sentadillas", "Squats", "स्क्वैट", "Squat", "スクワット", "스쿼트", "Agachamentos", "Приседания", "深蹲"],
    "photo": ["Photo", "صورة", "Foto", "Foto", "Photo", "फ़ोटो", "Foto", "写真", "사진", "Foto", "Фото", "拍照"],
    "barcode": ["Barcode", "باركود", "Barcode", "Código de barras", "Code-barres", "बारकोड", "Codice a barre", "バーコード", "바코드", "Código de barras", "Штрих-код", "条码"],
    "draw": ["Draw", "رسم", "Zeichnen", "Dibujo", "Dessin", "चित्र", "Disegno", "お絵かき", "그리기", "Desenho", "Рисование", "涂鸦"],
    "flap": ["Flap", "تحليق", "Flattern", "Aleteo", "Battement", "उड़ान", "Volo", "フラップ", "플랩", "Voo", "Полёт", "飞行"],
    "breathe": ["Breathe", "تنفّس", "Atmen", "Respirar", "Respiration", "श्वास", "Respiro", "呼吸", "호흡", "Respirar", "Дыхание", "呼吸"],
})

SUBTITLES = family("mission.", ".subtitle", {
    "math": ["Sums, in your head", "عمليات حسابية ذهنية", "Kopfrechnen", "Cuentas mentales", "Du calcul mental", "मन में जोड़-घटाव", "Calcoli a mente", "頭の中で計算", "머릿속으로 계산", "Contas de cabeça", "Считать в голове", "心算题目"],
    "memory": ["Recall the tiles", "تذكّر المربعات", "Felder erinnern", "Recuerda las casillas", "Retenez les cases", "टाइल याद रखें", "Ricorda le caselle", "光ったマスを記憶", "칸을 기억하기", "Lembre os quadros", "Запомнить плитки", "记住亮起的格子"],
    "sequence": ["Repeat the pattern", "أعد النمط", "Muster nachspielen", "Repite el patrón", "Répétez le motif", "पैटर्न दोहराएँ", "Ripeti la sequenza", "パターンを再現", "패턴을 따라 하기", "Repita o padrão", "Повторить рисунок", "重复图案"],
    "typing": ["Retype a sentence", "أعد كتابة جملة", "Satz abtippen", "Copia una frase", "Recopiez une phrase", "एक वाक्य टाइप करें", "Ricopia una frase", "文章を打ち直す", "문장을 다시 입력", "Redigite uma frase", "Перепечатать фразу", "重打一句话"],
    "shake": ["Shake it awake", "رجّه لتستيقظ", "Wachschütteln", "Sacúdelo", "Secouez fort", "ज़ोर से हिलाएँ", "Scuotilo forte", "振って起きる", "흔들어서 깨기", "Sacuda com força", "Растрясти себя", "摇醒自己"],
    "steps": ["Leave the bed", "اترك السرير", "Raus aus dem Bett", "Sal de la cama", "Quittez le lit", "बिस्तर छोड़ें", "Esci dal letto", "ベッドから出る", "침대에서 벗어나기", "Saia da cama", "Встать с кровати", "离开被窝"],
    "squats": ["Squats on camera", "قرفصاء أمام الكاميرا", "Kniebeugen vor der Kamera", "Sentadillas ante la cámara", "Des squats face caméra", "कैमरे के सामने स्क्वैट", "Squat davanti alla camera", "カメラの前でスクワット", "카메라 앞에서 스쿼트", "Agachamentos na câmera", "Приседания перед камерой", "在镜头前深蹲"],
    "photo": ["Photograph a thing", "صوّر شيئاً", "Etwas fotografieren", "Fotografía algo", "Photographiez un objet", "किसी चीज़ की फ़ोटो", "Fotografa un oggetto", "モノを撮影", "물건 촬영하기", "Fotografe um objeto", "Сфотографировать вещь", "拍下某个物品"],
    "barcode": ["Scan your code", "امسح رمزك", "Deinen Code scannen", "Escanea tu código", "Scannez votre code", "अपना कोड स्कैन करें", "Scansiona il codice", "コードを読み取る", "코드 스캔하기", "Escaneie seu código", "Отсканировать код", "扫描你的条码"],
    "draw": ["Draw to order", "ارسم المطلوب", "Auf Ansage zeichnen", "Dibuja lo pedido", "Dessinez à la demande", "जो कहा जाए बनाएँ", "Disegna a richiesta", "お題を描く", "요청대로 그리기", "Desenhe o pedido", "Нарисовать по заказу", "按题作画"],
    "flap": ["Keep it flying", "أبقِه يطير", "Halte es in der Luft", "Mantenlo en el aire", "Gardez-le en vol", "उड़ता रखें", "Tienilo in volo", "飛ばし続ける", "계속 날리기", "Mantenha voando", "Не дать упасть", "让它一直飞"],
    "breathe": ["Breathe, then wake", "تنفّس ثم استيقظ", "Atmen, dann wach", "Respira y despierta", "Respirez, puis debout", "साँस लें, फिर उठें", "Respira, poi sveglia", "呼吸して目覚める", "호흡하며 깨어나기", "Respire e acorde", "Дыхание и подъём", "先呼吸，再清醒"],
})

INSTRUCTIONS = family("mission.", ".instruction", {
    "math": ["Answer each sum. A wrong answer starts the round again.", "أجب عن كل عملية. الإجابة الخاطئة تُعيد الجولة.", "Löse jede Aufgabe. Eine falsche Antwort startet die Runde neu.", "Resuelve cada cuenta. Un error reinicia la ronda.", "Résolvez chaque calcul. Une erreur relance la manche.", "हर सवाल का जवाब दें। गलत जवाब पर राउंड फिर शुरू होगा।", "Risolvi ogni calcolo. Una risposta sbagliata ricomincia il turno.", "各問に答えてください。間違えるとそのラウンドは最初から。", "각 문제에 답하세요. 틀리면 라운드가 처음부터 다시 시작됩니다.", "Responda cada conta. Um erro reinicia a rodada.", "Решите каждый пример. Ошибка начинает раунд заново.", "回答每道题。答错则本轮重新开始。"],
    "memory": ["Watch which tiles light up, then tap those tiles.", "لاحظ المربعات التي تُضاء، ثم اضغط عليها.", "Merke dir die leuchtenden Felder und tippe sie dann an.", "Fíjate en las casillas que se iluminan y tócalas.", "Observez les cases qui s’allument, puis touchez-les.", "देखें कौन-सी टाइल जलती हैं, फिर उन्हें दबाएँ।", "Guarda quali caselle si illuminano, poi toccale.", "光ったマスを覚えて、そのマスをタップします。", "불이 켜진 칸을 기억한 뒤 그 칸을 누르세요.", "Veja quais quadros acendem e toque neles.", "Заметьте, какие плитки загорелись, и нажмите на них.", "记住亮起的格子，然后点它们。"],
    "sequence": ["Watch the pattern, then repeat it in the same order.", "شاهد النمط ثم أعده بالترتيب نفسه.", "Sieh das Muster und wiederhole es in derselben Reihenfolge.", "Observa el patrón y repítelo en el mismo orden.", "Regardez le motif, puis répétez-le dans le même ordre.", "पैटर्न देखें, फिर उसी क्रम में दोहराएँ।", "Osserva la sequenza, poi ripetila nello stesso ordine.", "パターンを見て、同じ順番で再現します。", "패턴을 본 뒤 같은 순서로 따라 하세요.", "Observe o padrão e repita na mesma ordem.", "Посмотрите рисунок и повторите его в том же порядке.", "看清图案，再按相同顺序重复。"],
    "typing": ["Retype the sentence exactly, punctuation and all.", "أعد كتابة الجملة حرفياً، بعلامات الترقيم كلها.", "Tippe den Satz genau ab, mit allen Satzzeichen.", "Copia la frase exactamente, con su puntuación.", "Recopiez la phrase à l’identique, ponctuation comprise.", "वाक्य को ठीक वैसा ही टाइप करें, विराम-चिह्नों सहित।", "Ricopia la frase esattamente, punteggiatura compresa.", "句読点まで含めて、文章をそのまま打ち直します。", "문장을 문장부호까지 그대로 입력하세요.", "Redigite a frase exatamente, com pontuação e tudo.", "Перепечатайте фразу в точности, вместе со знаками.", "一字不差地重打这句话，标点也算。"],
    "shake": ["Shake your iPhone until the counter fills.", "رجّ الـ iPhone حتى يمتلئ العدّاد.", "Schüttle dein iPhone, bis der Zähler voll ist.", "Agita el iPhone hasta llenar el contador.", "Secouez votre iPhone jusqu’à remplir le compteur.", "काउंटर भरने तक iPhone हिलाएँ।", "Scuoti l’iPhone finché il contatore non è pieno.", "カウンターが埋まるまで iPhone を振ります。", "카운터가 채워질 때까지 iPhone을 흔드세요.", "Agite o iPhone até o contador encher.", "Трясите iPhone, пока счётчик не заполнится.", "摇动 iPhone 直到计数满。"],
    "steps": ["Get out of bed and walk until the steps are counted.", "انزل من السرير وامشِ حتى تُحتسب الخطوات.", "Steh auf und gehe, bis die Schritte gezählt sind.", "Levántate y camina hasta completar los pasos.", "Levez-vous et marchez jusqu’à ce que les pas soient comptés.", "बिस्तर से उठें और कदम पूरे होने तक चलें।", "Alzati e cammina finché i passi non sono contati.", "ベッドから出て、歩数が満たされるまで歩きます。", "침대에서 나와 걸음 수가 채워질 때까지 걸으세요.", "Levante e caminhe até os passos serem contados.", "Встаньте и идите, пока шаги не будут засчитаны.", "下床走动，直到步数达标。"],
    "squats": ["Stand your iPhone up, get in frame, and do the squats.", "أسند الـ iPhone، ادخل في الإطار، وقم بتمارين القرفصاء.", "Stelle dein iPhone auf, komm ins Bild und mach die Kniebeugen.", "Apoya el iPhone, ponte en el encuadre y haz las sentadillas.", "Posez votre iPhone, cadrez-vous et faites les squats.", "iPhone खड़ा करें, फ्रेम में आएँ और स्क्वैट करें।", "Appoggia l’iPhone, inquadrati e fai gli squat.", "iPhone を立てて、画面に全身を入れてスクワットします。", "iPhone을 세우고 화면에 몸을 맞춘 뒤 스쿼트를 하세요.", "Apoie o iPhone, apareça no quadro e faça os agachamentos.", "Поставьте iPhone, попадите в кадр и приседайте.", "把 iPhone 立起来，站进取景框，开始深蹲。"],
    "photo": ["Go to the object you registered and photograph it.", "اذهب إلى الشيء الذي سجّلته وصوّره.", "Geh zu dem registrierten Objekt und fotografiere es.", "Ve al objeto que registraste y fotografíalo.", "Allez jusqu’à l’objet enregistré et photographiez-le.", "आपने जो चीज़ रजिस्टर की है, उसके पास जाकर फ़ोटो लें।", "Vai all’oggetto che hai registrato e fotografalo.", "登録したモノのところへ行って撮影します。", "등록한 물건에 가서 사진을 찍으세요.", "Vá até o objeto que você registrou e fotografe.", "Подойдите к зарегистрированной вещи и сфотографируйте её.", "走到你注册的物品前，把它拍下来。"],
    "barcode": ["Find the code you registered and scan it.", "ابحث عن الرمز الذي سجّلته وامسحه.", "Finde den registrierten Code und scanne ihn.", "Busca el código que registraste y escanéalo.", "Trouvez le code enregistré et scannez-le.", "आपने जो कोड रजिस्टर किया है, उसे ढूँढकर स्कैन करें।", "Trova il codice che hai registrato e scansionalo.", "登録したコードを探して読み取ります。", "등록한 코드를 찾아 스캔하세요.", "Encontre o código que você registrou e escaneie.", "Найдите зарегистрированный код и отсканируйте его.", "找到你注册的条码并扫描。"],
    "draw": ["Draw what the screen asks for, well enough to be recognised.", "ارسم ما تطلبه الشاشة بشكل يمكن التعرّف عليه.", "Zeichne, was der Bildschirm verlangt — erkennbar genug.", "Dibuja lo que pide la pantalla, de forma reconocible.", "Dessinez ce que l’écran demande, de façon reconnaissable.", "स्क्रीन जो कहे वह बनाएँ, इतना साफ़ कि पहचाना जा सके।", "Disegna ciò che chiede lo schermo, in modo riconoscibile.", "画面のお題を、認識できる程度に描きます。", "화면이 요구하는 것을 알아볼 수 있게 그리세요.", "Desenhe o que a tela pedir, de forma reconhecível.", "Нарисуйте то, что просит экран, узнаваемо.", "画出屏幕给的题目，画到能被认出为止。"],
    "flap": ["Tap to keep the bird flying through the gaps.", "اضغط لتُبقي الطائر يطير عبر الفتحات.", "Tippe, damit der Vogel durch die Lücken fliegt.", "Toca para que el pájaro pase por los huecos.", "Touchez pour faire passer l’oiseau entre les obstacles.", "टैप करके पक्षी को गैप के बीच उड़ाते रहें।", "Tocca per far volare l’uccello tra le aperture.", "タップして、鳥を隙間に通し続けます。", "탭해서 새가 틈 사이로 계속 날게 하세요.", "Toque para o pássaro passar pelos vãos.", "Нажимайте, чтобы птица пролетала между препятствиями.", "点击屏幕，让小鸟穿过缝隙。"],
    "breathe": ["Follow the circle: breathe in, hold, breathe out.", "اتبع الدائرة: شهيق، حبس، زفير.", "Folge dem Kreis: einatmen, halten, ausatmen.", "Sigue el círculo: inspira, aguanta, espira.", "Suivez le cercle : inspirez, retenez, expirez.", "गोले का अनुसरण करें: साँस लें, रोकें, छोड़ें।", "Segui il cerchio: inspira, trattieni, espira.", "円に合わせて、吸って、止めて、吐きます。", "원을 따라 들이쉬고, 멈추고, 내쉬세요.", "Siga o círculo: inspire, segure, expire.", "Следуйте за кругом: вдох, пауза, выдох.", "跟着圆圈：吸气、屏息、呼气。"],
})

# MARK: - The mission runner's own chrome

RUNNER = {
    "mission.progress": ["Progress", "التقدّم", "Fortschritt", "Progreso", "Progression", "प्रगति", "Progresso", "進捗", "진행", "Progresso", "Прогресс", "进度"],
    "mission.progress.value": ["%1$lld / %2$lld", "%1$lld / %2$lld", "%1$lld / %2$lld", "%1$lld / %2$lld", "%1$lld / %2$lld", "%1$lld / %2$lld", "%1$lld / %2$lld", "%1$lld / %2$lld", "%1$lld / %2$lld", "%1$lld / %2$lld", "%1$lld / %2$lld", "%1$lld / %2$lld"],
    "mission.timeLeft": ["Time left", "الوقت المتبقي", "Restzeit", "Tiempo restante", "Temps restant", "बचा समय", "Tempo rimasto", "残り時間", "남은 시간", "Tempo restante", "Осталось", "剩余时间"],
    "mission.snooze": ["Snooze %lld min", "تأجيل %lld د", "%lld Min. schlummern", "Posponer %lld min", "Répéter %lld min", "%lld मि स्नूज़", "Posticipa %lld min", "%lld 分スヌーズ", "%lld분 후 다시", "Soneca de %lld min", "Отложить на %lld мин", "小睡 %lld 分钟"],
    # `mission.snoozesLeft` is a plural: see scripts/strings/plurals.py.
    "mission.exit": ["Give up", "استسلام", "Aufgeben", "Rendirse", "Abandonner", "हार मानें", "Arrenditi", "あきらめる", "포기", "Desistir", "Сдаться", "放弃"],
    "mission.exit.title": ["Give up on this mission?", "التخلي عن هذه المهمة؟", "Mission aufgeben?", "¿Rendirse en esta misión?", "Abandonner cette mission ?", "यह मिशन छोड़ दें?", "Arrendersi in questa missione?", "このミッションをあきらめますか？", "이 미션을 포기할까요?", "Desistir desta missão?", "Сдаться в этом задании?", "放弃这个任务？"],
    "mission.exit.body": ["The alarm stops and the morning is logged as a bail-out. You are the one who has to be somewhere.", "سيتوقف المنبه وسيُسجّل الصباح كانسحاب. أنت من عليه أن يكون في مكان ما.", "Der Alarm verstummt und der Morgen wird als Abbruch protokolliert. Du bist der, der irgendwo sein muss.", "La alarma se para y la mañana queda registrada como abandono. Tú eres quien tiene que estar en algún sitio.", "L’alarme s’arrête et la matinée est notée comme un abandon. C’est vous qui devez être quelque part.", "अलार्म बंद हो जाएगा और यह सुबह छोड़ने के रूप में दर्ज होगी। कहीं पहुँचना आपको ही है।", "La sveglia si ferma e la mattina viene registrata come resa. Sei tu quello che deve essere da qualche parte.", "アラームは止まり、この朝は「途中でやめた」として記録されます。どこかへ行かなければならないのはあなたです。", "알람이 멈추고 이 아침은 포기로 기록됩니다. 어딘가에 가야 하는 사람은 당신입니다.", "O alarme para e a manhã fica registrada como desistência. Quem precisa estar em algum lugar é você.", "Будильник выключится, а утро запишется как отказ. Это вам нужно куда-то успеть.", "闹钟会停止，这个早晨会记为放弃。要赶去某处的人是你。"],
    "mission.exit.confirm": ["Give up and stop the alarm", "استسلم وأوقف المنبه", "Aufgeben und Alarm stoppen", "Rendirse y parar la alarma", "Abandonner et arrêter l’alarme", "हार मानें और अलार्म बंद करें", "Arrenditi e ferma la sveglia", "あきらめてアラームを止める", "포기하고 알람 끄기", "Desistir e parar o alarme", "Сдаться и выключить будильник", "放弃并停止闹钟"],
    "mission.exit.keepGoing": ["Keep going", "استمر", "Weitermachen", "Seguir", "Continuer", "जारी रखें", "Continua", "続ける", "계속하기", "Continuar", "Продолжить", "继续"],
    "mission.done.title": ["You are up", "أنت مستيقظ", "Du bist wach", "Estás en pie", "Vous êtes debout", "आप जाग गए", "Sei in piedi", "起きました", "일어났습니다", "Você acordou", "Вы встали", "你起来了"],
    "mission.done.body": ["Mission cleared in %@.", "أنجزت المهمة في %@.", "Mission in %@ geschafft.", "Misión superada en %@.", "Mission réussie en %@.", "मिशन %@ में पूरा हुआ।", "Missione completata in %@.", "%@ でミッション達成。", "%@ 만에 미션 완료.", "Missão concluída em %@.", "Задание выполнено за %@.", "用 %@ 完成任务。"],
    "mission.done.streak": ["%lld mornings in a row", "%lld صباحاً على التوالي", "%lld Morgen in Folge", "%lld mañanas seguidas", "%lld matins d’affilée", "लगातार %lld सुबह", "%lld mattine di fila", "%lld 日連続", "%lld일 연속", "%lld manhãs seguidas", "%lld утро подряд", "连续 %lld 个早晨"],
    "mission.done.action": ["Start the day", "ابدأ اليوم", "Tag beginnen", "Empezar el día", "Commencer la journée", "दिन शुरू करें", "Inizia la giornata", "1 日を始める", "하루 시작하기", "Começar o dia", "Начать день", "开始新的一天"],
    "mission.unavailable.dismiss": ["Skip this mission and stop the alarm", "تخطَّ المهمة وأوقف المنبه", "Mission überspringen und Alarm stoppen", "Saltar la misión y parar la alarma", "Passer la mission et arrêter l’alarme", "इस मिशन को छोड़ें और अलार्म बंद करें", "Salta la missione e ferma la sveglia", "このミッションを飛ばしてアラームを止める", "이 미션을 건너뛰고 알람 끄기", "Pular a missão e parar o alarme", "Пропустить задание и выключить будильник", "跳过任务并停止闹钟"],
    "mission.camera.denied.title": ["Camera is off", "الكاميرا معطّلة", "Kamera ist aus", "La cámara está desactivada", "La caméra est désactivée", "कैमरा बंद है", "La fotocamera è disattivata", "カメラがオフです", "카메라가 꺼져 있습니다", "A câmera está desativada", "Камера отключена", "相机已关闭"],
    "mission.camera.denied.body": ["This mission needs the camera. Allow it in Settings, or skip the mission this once.", "تحتاج هذه المهمة إلى الكاميرا. اسمح بها من الإعدادات أو تخطَّ المهمة هذه المرة.", "Diese Mission braucht die Kamera. Erlaube sie in den Einstellungen oder überspringe sie dieses Mal.", "Esta misión necesita la cámara. Permítela en Ajustes o sáltala esta vez.", "Cette mission a besoin de la caméra. Autorisez-la dans Réglages, ou passez la mission cette fois.", "इस मिशन को कैमरा चाहिए। सेटिंग में अनुमति दें, या इस बार मिशन छोड़ दें।", "Questa missione richiede la fotocamera. Consentila in Impostazioni o salta la missione per questa volta.", "このミッションにはカメラが必要です。設定で許可するか、今回は飛ばしてください。", "이 미션은 카메라가 필요합니다. 설정에서 허용하거나 이번만 건너뛰세요.", "Esta missão precisa da câmera. Permita em Ajustes ou pule a missão desta vez.", "Для этого задания нужна камера. Разрешите её в настройках или пропустите задание на этот раз.", "该任务需要相机。请在“设置”中允许，或本次跳过。"],
}

# MARK: - Per-mission strings

MATH = {
    "mission.math.answer": ["Answer", "الإجابة", "Antwort", "Respuesta", "Réponse", "उत्तर", "Risposta", "答え", "정답", "Resposta", "Ответ", "答案"],
    "keypad.submit": ["Check", "تحقّق", "Prüfen", "Comprobar", "Valider", "जाँचें", "Verifica", "判定", "확인", "Verificar", "Проверить", "确认"],
    "keypad.delete": ["Delete last digit", "حذف آخر رقم", "Letzte Ziffer löschen", "Borrar último dígito", "Effacer le dernier chiffre", "अंतिम अंक हटाएँ", "Cancella l’ultima cifra", "最後の桁を削除", "마지막 숫자 지우기", "Apagar último dígito", "Удалить последнюю цифру", "删除最后一位"],
    "keypad.negative": ["Minus sign", "إشارة السالب", "Minuszeichen", "Signo menos", "Signe moins", "ऋण चिह्न", "Segno meno", "マイナス記号", "마이너스 기호", "Sinal de menos", "Знак минус", "负号"],
}

PATTERN = {
    "mission.memory.watch": ["Watch closely", "راقب بتركيز", "Genau hinsehen", "Fíjate bien", "Regardez bien", "ध्यान से देखें", "Guarda bene", "よく見て", "잘 보세요", "Preste atenção", "Смотрите внимательно", "看仔细"],
    "mission.memory.remaining": ["%lld to find", "بقي %lld", "noch %lld", "faltan %lld", "%lld à trouver", "%lld बाकी", "ne restano %lld", "残り %lld", "%lld개 남음", "faltam %lld", "осталось %lld", "还剩 %lld 个"],
    "mission.memory.tile": ["Tile %lld", "مربع %lld", "Feld %lld", "Casilla %lld", "Case %lld", "टाइल %lld", "Casella %lld", "マス %lld", "%lld번 칸", "Quadro %lld", "Плитка %lld", "第 %lld 格"],
    "mission.sequence.watch": ["Watch the order", "راقب الترتيب", "Reihenfolge merken", "Fíjate en el orden", "Retenez l’ordre", "क्रम देखें", "Osserva l’ordine", "順番を見て", "순서를 보세요", "Observe a ordem", "Запомните порядок", "注意顺序"],
    "mission.sequence.step": ["Step %1$lld of %2$lld", "الخطوة %1$lld من %2$lld", "Schritt %1$lld von %2$lld", "Paso %1$lld de %2$lld", "Étape %1$lld sur %2$lld", "%2$lld में से %1$lld चरण", "Passo %1$lld di %2$lld", "%2$lld 個中 %1$lld 番目", "%2$lld단계 중 %1$lld", "Passo %1$lld de %2$lld", "Шаг %1$lld из %2$lld", "第 %1$lld 步，共 %2$lld 步"],
    "mission.sequence.pad": ["Pad %lld", "لوح %lld", "Taste %lld", "Panel %lld", "Touche %lld", "पैड %lld", "Tasto %lld", "パッド %lld", "%lld번 패드", "Botão %lld", "Кнопка %lld", "第 %lld 键"],
}

TYPING_UI = {
    "mission.typing.placeholder": ["Type it here", "اكتبها هنا", "Hier eintippen", "Escríbelo aquí", "Tapez ici", "यहाँ टाइप करें", "Scrivi qui", "ここに入力", "여기에 입력", "Digite aqui", "Печатайте здесь", "在此输入"],
    "mission.typing.check": ["Check", "تحقّق", "Prüfen", "Comprobar", "Valider", "जाँचें", "Verifica", "判定", "확인", "Verificar", "Проверить", "确认"],
}

MOTION = {
    "mission.shake.unit": ["shakes", "رجّة", "Schütteln", "sacudidas", "secousses", "बार", "scosse", "回", "회", "sacudidas", "встряхиваний", "次"],
    "mission.shake.unavailable.title": ["No motion sensor", "لا مستشعر حركة", "Kein Bewegungssensor", "Sin sensor de movimiento", "Pas de capteur de mouvement", "मोशन सेंसर नहीं", "Nessun sensore di movimento", "モーションセンサーがありません", "동작 센서 없음", "Sem sensor de movimento", "Нет датчика движения", "没有运动传感器"],
    "mission.shake.unavailable.body": ["This iPhone will not report motion, so the shake cannot be counted.", "هذا الـ iPhone لا يبلّغ عن الحركة، لذا لا يمكن عدّ الرجّات.", "Dieses iPhone meldet keine Bewegung, das Schütteln lässt sich nicht zählen.", "Este iPhone no informa del movimiento, así que no se pueden contar las sacudidas.", "Cet iPhone ne remonte pas le mouvement : les secousses ne peuvent pas être comptées.", "यह iPhone मोशन रिपोर्ट नहीं करता, इसलिए हिलाना गिना नहीं जा सकता।", "Questo iPhone non riporta il movimento: le scosse non possono essere contate.", "この iPhone はモーションを報告しないため、シェイクを数えられません。", "이 iPhone은 동작을 보고하지 않아 흔들기를 셀 수 없습니다.", "Este iPhone não informa movimento, então não é possível contar as sacudidas.", "Этот iPhone не сообщает о движении, поэтому встряхивания не считаются.", "此 iPhone 不上报运动数据，无法统计摇动次数。"],
    "mission.steps.unit": ["steps", "خطوة", "Schritte", "pasos", "pas", "कदम", "passi", "歩", "걸음", "passos", "шагов", "步"],
    "mission.steps.hint": ["Keep the iPhone with you while you walk.", "احمل الـ iPhone معك أثناء المشي.", "Nimm das iPhone beim Gehen mit.", "Lleva el iPhone contigo mientras caminas.", "Gardez l’iPhone sur vous en marchant.", "चलते समय iPhone अपने साथ रखें।", "Porta l’iPhone con te mentre cammini.", "歩くときは iPhone を持っていてください。", "걸을 때 iPhone을 몸에 지니세요.", "Leve o iPhone com você enquanto caminha.", "Держите iPhone при себе, когда идёте.", "走动时把 iPhone 带在身上。"],
    "mission.steps.unavailable.title": ["No step counter", "لا عدّاد خطوات", "Kein Schrittzähler", "Sin contador de pasos", "Pas de compteur de pas", "स्टेप काउंटर नहीं", "Nessun contapassi", "歩数計がありません", "걸음 수 측정 불가", "Sem contador de passos", "Нет счётчика шагов", "没有计步器"],
    "mission.steps.unavailable.body": ["This iPhone cannot count steps, so this mission has no way to finish.", "لا يمكن لهذا الـ iPhone عدّ الخطوات، لذا لا سبيل لإكمال المهمة.", "Dieses iPhone kann keine Schritte zählen, diese Mission ist nicht abschließbar.", "Este iPhone no puede contar pasos, así que esta misión no puede completarse.", "Cet iPhone ne peut pas compter les pas : cette mission n’a aucun moyen d’aboutir.", "यह iPhone कदम नहीं गिन सकता, इसलिए यह मिशन पूरा नहीं हो सकता।", "Questo iPhone non può contare i passi: la missione non può concludersi.", "この iPhone は歩数を数えられないため、このミッションは完了できません。", "이 iPhone은 걸음 수를 셀 수 없어 이 미션을 끝낼 방법이 없습니다.", "Este iPhone não conta passos, então esta missão não tem como terminar.", "Этот iPhone не умеет считать шаги, поэтому задание невозможно завершить.", "此 iPhone 无法计步，该任务无法完成。"],
    "mission.steps.denied.title": ["Motion access is off", "الوصول للحركة معطّل", "Bewegungszugriff ist aus", "El acceso al movimiento está desactivado", "L’accès au mouvement est désactivé", "मोशन एक्सेस बंद है", "L’accesso al movimento è disattivato", "モーションへのアクセスがオフです", "동작 접근이 꺼져 있습니다", "O acesso ao movimento está desativado", "Доступ к движению отключён", "运动权限已关闭"],
    "mission.steps.denied.body": ["Dawnbreak cannot read your steps. Allow Motion & Fitness in Settings, or skip this once.", "لا يستطيع Dawnbreak قراءة خطواتك. اسمح بالحركة واللياقة من الإعدادات أو تخطَّ هذه المرة.", "Dawnbreak kann deine Schritte nicht lesen. Erlaube Bewegung & Fitness in den Einstellungen oder überspringe dieses Mal.", "Dawnbreak no puede leer tus pasos. Permite Movimiento y Fitness en Ajustes, o sáltalo esta vez.", "Dawnbreak ne peut pas lire vos pas. Autorisez Mouvement et Forme dans Réglages, ou passez cette fois.", "Dawnbreak आपके कदम नहीं पढ़ सकता। सेटिंग में मोशन और फ़िटनेस की अनुमति दें, या इस बार छोड़ दें।", "Dawnbreak non può leggere i tuoi passi. Consenti Movimento e fitness in Impostazioni o salta per questa volta.", "Dawnbreak は歩数を読み取れません。設定で「モーションとフィットネス」を許可するか、今回は飛ばしてください。", "Dawnbreak가 걸음 수를 읽을 수 없습니다. 설정에서 동작 및 피트니스를 허용하거나 이번만 건너뛰세요.", "O Dawnbreak não consegue ler seus passos. Permita Movimento e Preparo Físico em Ajustes ou pule desta vez.", "Dawnbreak не может считать ваши шаги. Разрешите «Движение и фитнес» в настройках или пропустите на этот раз.", "Dawnbreak 无法读取你的步数。请在“设置”中允许“运动与健身”，或本次跳过。"],
    "mission.breathe.inhale": ["Breathe in", "شهيق", "Einatmen", "Inspira", "Inspirez", "साँस लें", "Inspira", "吸って", "들이쉬기", "Inspire", "Вдох", "吸气"],
    "mission.breathe.hold": ["Hold", "احبس", "Halten", "Aguanta", "Retenez", "रोकें", "Trattieni", "止めて", "멈추기", "Segure", "Задержите", "屏息"],
    "mission.breathe.exhale": ["Breathe out", "زفير", "Ausatmen", "Espira", "Expirez", "छोड़ें", "Espira", "吐いて", "내쉬기", "Expire", "Выдох", "呼气"],
    "mission.breathe.cycle": ["Breath %1$lld of %2$lld", "النفس %1$lld من %2$lld", "Atemzug %1$lld von %2$lld", "Respiración %1$lld de %2$lld", "Respiration %1$lld sur %2$lld", "%2$lld में से %1$lld साँस", "Respiro %1$lld di %2$lld", "%2$lld 回中 %1$lld 回目", "%2$lld회 중 %1$lld회", "Respiração %1$lld de %2$lld", "Дыхание %1$lld из %2$lld", "第 %1$lld 次呼吸，共 %2$lld 次"],
}

CAMERA = {
    "mission.photo.find": ["Find your %@", "ابحث عن %@", "Finde: %@", "Encuentra: %@", "Trouvez : %@", "%@ ढूँढें", "Trova: %@", "%@ を見つけて", "%@ 찾기", "Encontre: %@", "Найдите: %@", "找到你的%@"],
    "mission.photo.searching": ["Point the camera at it", "وجّه الكاميرا نحوه", "Kamera darauf richten", "Apunta la cámara hacia él", "Pointez la caméra dessus", "कैमरा उस पर रखें", "Inquadralo con la fotocamera", "カメラを向けてください", "카메라를 그쪽으로 향하세요", "Aponte a câmera para ele", "Наведите камеру на него", "把相机对准它"],
    "mission.photo.seeing": ["Seeing: %@", "يرى: %@", "Erkannt: %@", "Se ve: %@", "Détecté : %@", "दिख रहा है: %@", "Rilevato: %@", "認識中: %@", "인식 중: %@", "Vendo: %@", "Вижу: %@", "识别到：%@"],
    "mission.photo.holdStill": ["Hold still", "ثبّتها", "Still halten", "No te muevas", "Ne bougez plus", "स्थिर रखें", "Tieni fermo", "そのまま静止", "그대로 유지", "Segure firme", "Держите ровно", "保持不动"],
    "mission.barcode.find": ["Scan your %@", "امسح %@", "Scanne: %@", "Escanea: %@", "Scannez : %@", "%@ स्कैन करें", "Scansiona: %@", "%@ をスキャン", "%@ 스캔", "Escaneie: %@", "Отсканируйте: %@", "扫描你的%@"],
    "mission.barcode.hint": ["Line the code up inside the frame", "ضع الرمز داخل الإطار", "Code im Rahmen ausrichten", "Alinea el código dentro del marco", "Alignez le code dans le cadre", "कोड को फ़्रेम के भीतर रखें", "Allinea il codice nel riquadro", "枠の中にコードを合わせて", "코드를 프레임 안에 맞추세요", "Alinhe o código dentro do quadro", "Совместите код с рамкой", "把条码对准取景框"],
    "mission.barcode.wrong": ["That is a different code", "هذا رمز مختلف", "Das ist ein anderer Code", "Ese es otro código", "Ce n’est pas le bon code", "यह दूसरा कोड है", "Questo è un altro codice", "別のコードです", "다른 코드입니다", "Esse é outro código", "Это другой код", "这是另一个条码"],
    "mission.squats.frameYourself": ["Step back until you fit in the frame", "تراجع حتى تظهر كاملاً في الإطار", "Geh zurück, bis du ins Bild passt", "Retrocede hasta caber en el encuadre", "Reculez jusqu’à tenir dans le cadre", "पीछे हटें ताकि आप फ़्रेम में आ जाएँ", "Allontanati finché non rientri nell’inquadratura", "全身が入るまで下がってください", "화면에 다 들어올 만큼 뒤로 물러나세요", "Afaste-se até caber no quadro", "Отойдите, чтобы попасть в кадр целиком", "后退，直到全身进入取景框"],
    "mission.squats.goDown": ["Go down", "انزل", "Runter", "Abajo", "Descendez", "नीचे जाएँ", "Scendi", "下げて", "내려가기", "Desça", "Вниз", "下蹲"],
    "mission.squats.standUp": ["Stand up", "قف", "Aufstehen", "Arriba", "Remontez", "खड़े हों", "Rialzati", "立ち上がって", "일어서기", "Levante", "Вверх", "起立"],
    "mission.squats.depth": ["Depth", "العمق", "Tiefe", "Profundidad", "Profondeur", "गहराई", "Profondità", "深さ", "깊이", "Profundidade", "Глубина", "深度"],
    "mission.squats.unit": ["squats", "قرفصاء", "Kniebeugen", "sentadillas", "squats", "स्क्वैट", "squat", "回", "회", "agachamentos", "приседаний", "次"],
    "mission.squats.denied.body": ["Squats are counted by the front camera. Allow the camera in Settings, or skip this once.", "تُحتسب القرفصاء بالكاميرا الأمامية. اسمح بالكاميرا من الإعدادات أو تخطَّ هذه المرة.", "Kniebeugen werden von der Frontkamera gezählt. Erlaube die Kamera in den Einstellungen oder überspringe dieses Mal.", "Las sentadillas se cuentan con la cámara frontal. Permite la cámara en Ajustes, o sáltalo esta vez.", "Les squats sont comptés par la caméra avant. Autorisez la caméra dans Réglages, ou passez cette fois.", "स्क्वैट फ़्रंट कैमरे से गिने जाते हैं। सेटिंग में कैमरा की अनुमति दें, या इस बार छोड़ दें।", "Gli squat vengono contati dalla fotocamera frontale. Consenti la fotocamera in Impostazioni o salta per questa volta.", "スクワットは前面カメラで数えます。設定でカメラを許可するか、今回は飛ばしてください。", "스쿼트는 전면 카메라로 셉니다. 설정에서 카메라를 허용하거나 이번만 건너뛰세요.", "Os agachamentos são contados pela câmera frontal. Permita a câmera em Ajustes ou pule desta vez.", "Приседания считает фронтальная камера. Разрешите камеру в настройках или пропустите на этот раз.", "深蹲由前置摄像头计数。请在“设置”中允许相机，或本次跳过。"],
}

DRAW_FLAP = {
    "mission.draw.prompt": ["Draw a %@", "ارسم %@", "Zeichne: %@", "Dibuja: %@", "Dessinez : %@", "%@ बनाएँ", "Disegna: %@", "%@ を描いて", "%@ 그리기", "Desenhe: %@", "Нарисуйте: %@", "画一个%@"],
    "mission.draw.canvas": ["Drawing canvas", "لوحة الرسم", "Zeichenfläche", "Lienzo de dibujo", "Zone de dessin", "ड्रॉइंग कैनवास", "Area di disegno", "描画キャンバス", "그리기 캔버스", "Área de desenho", "Холст для рисования", "绘图画布"],
    "mission.draw.clear": ["Clear", "مسح", "Löschen", "Borrar", "Effacer", "साफ़ करें", "Cancella", "消す", "지우기", "Limpar", "Стереть", "清除"],
    "mission.draw.check": ["Check", "تحقّق", "Prüfen", "Comprobar", "Valider", "जाँचें", "Verifica", "判定", "확인", "Verificar", "Проверить", "确认"],
    "mission.draw.tooEmpty": ["Draw a bit more first", "ارسم أكثر قليلاً أولاً", "Zeichne erst noch etwas", "Dibuja un poco más", "Dessinez un peu plus", "पहले थोड़ा और बनाएँ", "Disegna ancora un po’", "もう少し描いてください", "조금 더 그려 보세요", "Desenhe um pouco mais", "Нарисуйте ещё немного", "先多画一点"],
    "mission.draw.notRecognised": ["Not quite. Try again.", "ليس تماماً. حاول مرة أخرى.", "Nicht ganz. Versuch es nochmal.", "Casi. Inténtalo otra vez.", "Pas tout à fait. Réessayez.", "बिलकुल नहीं। फिर कोशिश करें।", "Non proprio. Riprova.", "惜しい。もう一度。", "아직 아니에요. 다시 해 보세요.", "Quase. Tente de novo.", "Не совсем. Попробуйте снова.", "还差一点，再试一次。"],
    "mission.draw.sawInstead": ["It looked like %@", "بدا وكأنه %@", "Sah aus wie %@", "Parecía %@", "On dirait %@", "यह %@ जैसा लगा", "Sembrava %@", "%@ に見えました", "%@처럼 보였어요", "Pareceu %@", "Похоже на %@", "看起来像%@"],
    "mission.flap.canvas": ["Flying game", "لعبة التحليق", "Flugspiel", "Juego de vuelo", "Jeu de vol", "उड़ान खेल", "Gioco di volo", "フライトゲーム", "비행 게임", "Jogo de voo", "Игра-полёт", "飞行小游戏"],
    "mission.flap.start": ["Tap to start", "اضغط للبدء", "Zum Starten tippen", "Toca para empezar", "Touchez pour commencer", "शुरू करने के लिए टैप करें", "Tocca per iniziare", "タップして開始", "탭해서 시작", "Toque para começar", "Нажмите, чтобы начать", "点击开始"],
    "mission.flap.crashed": ["Keep flying!", "استمر بالتحليق!", "Weiterfliegen!", "¡Sigue volando!", "Continuez à voler !", "उड़ते रहें!", "Continua a volare!", "飛び続けて！", "계속 날아요!", "Continue voando!", "Летите дальше!", "继续飞！"],
    "mission.flap.retry": ["Again", "مرة أخرى", "Nochmal", "Otra vez", "Encore", "फिर से", "Ancora", "もう一度", "다시", "De novo", "Ещё раз", "再来"],
}
