"""The three pages App Store Connect needs a URL for, in all twelve languages.

Apple requires a privacy policy URL and a support URL before a build can be submitted, and it
requires them per locale. A Japanese listing that links an English-only support page is accepted,
and it is also the moment a Japanese reader learns how much of this app was actually made for them.
So the pages ship in the same twelve languages as the app.

One page per subject rather than one per subject per language: `make_pages.py` renders all twelve
translations into a single file with a language picker, so `privacy.html` is one URL that answers in
whichever language the reader's browser asks for. Twelve URLs would mean twelve values in
`store.py`, twelve values inside twelve descriptions, and a broken link the day one is renamed.

Blocks rather than HTML strings. A block is a tuple:

    ("h",  "A heading")
    ("p",  "A paragraph. <a href=…> is allowed, nothing else is.")
    ("ul", ["An item", "Another item"])

Written this way so `make_pages.py` can escape the text, check that every language has the same
shape as English, and change the markup for all twelve pages at once.
"""

# What the picker shows. Endonyms, because a reader looking for their own language is looking for
# the word they call it by, not for the English name of it.
LANGUAGE_NAME = {
    "en": "English",
    "ar": "العربية",
    "de": "Deutsch",
    "es": "Español",
    "fr": "Français",
    "hi": "हिन्दी",
    "it": "Italiano",
    "ja": "日本語",
    "ko": "한국어",
    "pt-BR": "Português (Brasil)",
    "ru": "Русский",
    "zh-Hans": "简体中文",
}

# The `<title>` and the `<h1>`, per page per language.
TITLE = {
    "index": {
        "en": "Dawnbreak",
        "ar": "Dawnbreak",
        "de": "Dawnbreak",
        "es": "Dawnbreak",
        "fr": "Dawnbreak",
        "hi": "Dawnbreak",
        "it": "Dawnbreak",
        "ja": "Dawnbreak",
        "ko": "Dawnbreak",
        "pt-BR": "Dawnbreak",
        "ru": "Dawnbreak",
        "zh-Hans": "Dawnbreak",
    },
    "privacy": {
        "en": "Privacy",
        "ar": "الخصوصية",
        "de": "Datenschutz",
        "es": "Privacidad",
        "fr": "Confidentialité",
        "hi": "गोपनीयता",
        "it": "Privacy",
        "ja": "プライバシー",
        "ko": "개인정보",
        "pt-BR": "Privacidade",
        "ru": "Конфиденциальность",
        "zh-Hans": "隐私",
    },
    "terms": {
        "en": "Terms",
        "ar": "الشروط",
        "de": "Nutzungsbedingungen",
        "es": "Términos",
        "fr": "Conditions",
        "hi": "शर्तें",
        "it": "Termini",
        "ja": "利用規約",
        "ko": "이용약관",
        "pt-BR": "Termos",
        "ru": "Условия",
        "zh-Hans": "使用条款",
    },
    "support": {
        "en": "Support",
        "ar": "الدعم",
        "de": "Hilfe",
        "es": "Soporte",
        "fr": "Assistance",
        "hi": "सहायता",
        "it": "Assistenza",
        "ja": "サポート",
        "ko": "지원",
        "pt-BR": "Suporte",
        "ru": "Поддержка",
        "zh-Hans": "支持",
    },
}

# The one-line promise under the name on the marketing page.
TAGLINE = {
    "en": "The alarm you cannot switch off in your sleep.",
    "ar": "منبّه لا يمكنك إسكاته وأنت نائم.",
    "de": "Der Wecker, den du im Schlaf nicht ausschalten kannst.",
    "es": "El despertador que no puedes apagar dormido.",
    "fr": "Le réveil qu'on ne peut pas éteindre en dormant.",
    "hi": "वह अलार्म जिसे आप नींद में बंद नहीं कर सकते।",
    "it": "La sveglia che non puoi spegnere nel sonno.",
    "ja": "寝たまま止められない目覚まし。",
    "ko": "잠결에는 끌 수 없는 알람.",
    "pt-BR": "O despertador que você não desliga dormindo.",
    "ru": "Будильник, который не выключить во сне.",
    "zh-Hans": "睡着的时候关不掉的闹钟。",
}

INDEX = {
    "en": [
        ("p", "You do not oversleep because your alarm is too quiet. You oversleep because stopping it takes one thumb, half a second, and no thought at all."),
        ("p", "Dawnbreak takes the thumb out of it. To silence the alarm you have to do something a sleeping person cannot: walk to the kitchen and photograph the kettle, do ten squats in front of the camera, solve arithmetic you would find easy at noon, scan the barcode on a box in another room."),
        ("h", "Twelve missions"),
        ("p", "Arithmetic, a tile pattern to reproduce, a colour sequence, a sentence to type exactly, a shake, a walk of a set number of steps, squats counted by the camera, an object to go and photograph, a barcode to scan, a drawing recognised on the device, a lap of a small game, and a round of guided breathing. Four difficulties, and as many missions in a row as you dare set."),
        ("h", "It does not let go"),
        ("p", "Stop the alarm without finishing the mission and it comes back a minute later under a title that says so. Up to ten rounds. An emergency exit is there from the first launch, because an alarm that can trap someone is a bug, not a feature."),
        ("h", "Nothing leaves your phone"),
        ("p", "No account, no server, no analytics, no third-party code of any kind. The camera frames the squat mission counts are analysed in memory and thrown away. Your alarms and your history are files on your device and nowhere else."),
        ("h", "Twelve languages"),
        ("p", "English, Arabic, German, Spanish, French, Hindi, Italian, Japanese, Korean, Portuguese, Russian and Simplified Chinese, including the right-to-left layout Arabic needs rather than a mirrored afterthought."),
    ],
    "ar": [
        ("p", "أنت لا تتأخر في النوم لأن المنبّه هادئ جدًا، بل لأن إسكاته لا يحتاج أكثر من إبهام ونصف ثانية وبلا أي تفكير."),
        ("p", "‏Dawnbreak يزيل الإبهام من المعادلة. لإسكات المنبّه عليك أن تفعل ما لا يقدر عليه نائم: أن تمشي إلى المطبخ وتصوّر الغلاية، أن تؤدي عشر حركات قرفصاء أمام الكاميرا، أن تحلّ مسألة حسابية تراها سهلة في منتصف النهار، أن تقرأ باركود علبة في غرفة أخرى."),
        ("h", "اثنتا عشرة مهمة"),
        ("p", "حساب، نمط مربّعات تعيد رسمه، تسلسل ألوان، جملة تكتبها حرفًا بحرف، رجّة للهاتف، عدد محدد من الخطوات، قرفصاء تعدّها الكاميرا، شيء تذهب وتصوّره، باركود تقرأه، رسمة يتعرّف عليها الجهاز، لفة في لعبة صغيرة، ودورة تنفّس موجّه. أربع درجات صعوبة، وعدد المهام المتتالية متروك لجرأتك."),
        ("h", "لا يتركك"),
        ("p", "أوقف المنبّه دون إنهاء المهمة وسيعود بعد دقيقة تحت عنوان يقول ذلك بصراحة. حتى عشر جولات. ومخرج الطوارئ موجود من أول تشغيل، لأن منبّهًا قادرًا على حجز صاحبه هو خلل لا ميزة."),
        ("h", "لا شيء يخرج من هاتفك"),
        ("p", "لا حساب، لا خادم، لا تحليلات، ولا سطر واحد من كود طرف ثالث. صور الكاميرا التي تعدّ القرفصاء تُحلَّل في الذاكرة ثم تُرمى. منبّهاتك وسجلك ملفات على جهازك ولا مكان غيره."),
        ("h", "اثنتا عشرة لغة"),
        ("p", "الإنجليزية والعربية والألمانية والإسبانية والفرنسية والهندية والإيطالية واليابانية والكورية والبرتغالية والروسية والصينية المبسطة، مع تخطيط من اليمين إلى اليسار مصمّم للعربية لا مجرد انعكاس متأخر."),
    ],
    "de": [
        ("p", "Du verschläfst nicht, weil der Wecker zu leise ist. Du verschläfst, weil ihn auszuschalten einen Daumen, eine halbe Sekunde und keinerlei Nachdenken kostet."),
        ("p", "Dawnbreak nimmt den Daumen aus der Rechnung. Um den Wecker still zu bekommen, musst du etwas tun, das ein Schlafender nicht kann: in die Küche gehen und den Wasserkocher fotografieren, zehn Kniebeugen vor der Kamera machen, eine Rechnung lösen, die mittags leicht wäre, den Barcode einer Packung im Nebenzimmer scannen."),
        ("h", "Zwölf Missionen"),
        ("p", "Rechnen, ein Muster nachlegen, eine Farbfolge wiederholen, einen Satz genau abtippen, das Telefon schütteln, eine festgelegte Zahl von Schritten gehen, Kniebeugen von der Kamera zählen lassen, einen Gegenstand fotografieren gehen, einen Barcode scannen, eine Zeichnung, die das Gerät erkennt, eine Runde in einem kleinen Spiel und eine Runde geführtes Atmen. Vier Schwierigkeiten, und so viele Missionen hintereinander, wie du dir zutraust."),
        ("h", "Er lässt nicht los"),
        ("p", "Beende den Wecker ohne die Mission, und er kommt eine Minute später zurück, unter einem Titel, der das auch sagt. Bis zu zehn Runden. Ein Notausgang ist ab dem ersten Start da, denn ein Wecker, der jemanden einsperren kann, ist ein Fehler und keine Funktion."),
        ("h", "Nichts verlässt dein Telefon"),
        ("p", "Kein Konto, kein Server, keine Analyse, keine einzige Zeile Fremdcode. Die Kamerabilder, mit denen Kniebeugen gezählt werden, werden im Speicher ausgewertet und weggeworfen. Deine Wecker und deine Historie sind Dateien auf deinem Gerät und sonst nirgends."),
        ("h", "Zwölf Sprachen"),
        ("p", "Englisch, Arabisch, Deutsch, Spanisch, Französisch, Hindi, Italienisch, Japanisch, Koreanisch, Portugiesisch, Russisch und Chinesisch (vereinfacht), mit dem Rechts-nach-links-Layout, das Arabisch braucht, und nicht als nachträglich gespiegelte Notlösung."),
    ],
    "es": [
        ("p", "No te quedas dormido porque la alarma suene poco. Te quedas dormido porque apagarla cuesta un pulgar, medio segundo y ningún pensamiento."),
        ("p", "Dawnbreak quita el pulgar de la ecuación. Para callar la alarma tienes que hacer algo que alguien dormido no puede: ir a la cocina y fotografiar el hervidor, hacer diez sentadillas delante de la cámara, resolver una cuenta que a mediodía te parecería fácil, escanear el código de barras de una caja en otra habitación."),
        ("h", "Doce misiones"),
        ("p", "Cuentas, un patrón de fichas que repetir, una secuencia de colores, una frase que escribir exacta, agitar el teléfono, andar un número fijo de pasos, sentadillas contadas por la cámara, un objeto que ir a fotografiar, un código de barras que escanear, un dibujo que el dispositivo reconoce, una vuelta en un juego pequeño y una ronda de respiración guiada. Cuatro dificultades, y tantas misiones seguidas como te atrevas a poner."),
        ("h", "No te suelta"),
        ("p", "Detén la alarma sin terminar la misión y vuelve un minuto después, con un título que lo dice. Hasta diez rondas. Hay una salida de emergencia desde el primer arranque, porque una alarma capaz de atrapar a alguien es un fallo, no una función."),
        ("h", "Nada sale de tu teléfono"),
        ("p", "Sin cuenta, sin servidor, sin analítica, sin una sola línea de código ajeno. Los fotogramas con los que se cuentan las sentadillas se analizan en memoria y se descartan. Tus alarmas y tu historial son archivos en tu dispositivo y en ningún otro sitio."),
        ("h", "Doce idiomas"),
        ("p", "Inglés, árabe, alemán, español, francés, hindi, italiano, japonés, coreano, portugués, ruso y chino simplificado, con la disposición de derecha a izquierda que el árabe necesita y no un reflejo puesto al final."),
    ],
    "fr": [
        ("p", "Vous ne dormez pas trop longtemps parce que le réveil est trop discret. Vous dormez trop longtemps parce que l'arrêter demande un pouce, une demi-seconde et aucune réflexion."),
        ("p", "Dawnbreak retire le pouce de l'équation. Pour faire taire le réveil, il faut faire quelque chose qu'un dormeur ne peut pas faire : aller dans la cuisine et photographier la bouilloire, faire dix squats devant la caméra, résoudre un calcul qui serait facile à midi, scanner le code-barres d'une boîte laissée dans une autre pièce."),
        ("h", "Douze missions"),
        ("p", "Du calcul, un motif à reproduire, une séquence de couleurs, une phrase à taper à l'identique, une secousse, un nombre de pas à parcourir, des squats comptés par la caméra, un objet à aller photographier, un code-barres à scanner, un dessin reconnu sur l'appareil, un tour dans un petit jeu, et un cycle de respiration guidée. Quatre difficultés, et autant de missions d'affilée que vous osez en régler."),
        ("h", "Il ne lâche pas"),
        ("p", "Arrêtez le réveil sans finir la mission et il revient une minute plus tard, sous un titre qui le dit. Jusqu'à dix tours. Une sortie de secours existe dès le premier lancement, parce qu'un réveil capable de piéger quelqu'un est un défaut, pas une fonctionnalité."),
        ("h", "Rien ne quitte votre téléphone"),
        ("p", "Pas de compte, pas de serveur, pas de statistiques, pas une ligne de code tiers. Les images qui servent à compter les squats sont analysées en mémoire puis jetées. Vos réveils et votre historique sont des fichiers sur votre appareil, et nulle part ailleurs."),
        ("h", "Douze langues"),
        ("p", "Anglais, arabe, allemand, espagnol, français, hindi, italien, japonais, coréen, portugais, russe et chinois simplifié, avec la mise en page de droite à gauche que l'arabe exige, et non un miroir posé à la fin."),
    ],
    "hi": [
        ("p", "आप देर तक इसलिए नहीं सोते कि अलार्म धीमा है। आप इसलिए सोते हैं कि उसे बंद करने में एक अंगूठा, आधा सेकंड और कोई सोच नहीं लगती।"),
        ("p", "Dawnbreak उस अंगूठे को हटा देता है। अलार्म चुप कराने के लिए आपको वह करना पड़ता है जो सोया हुआ आदमी नहीं कर सकता: रसोई तक जाकर केतली की फ़ोटो लेना, कैमरे के सामने दस स्क्वैट करना, दोपहर में आसान लगने वाला गणित हल करना, दूसरे कमरे में रखे डिब्बे का बारकोड स्कैन करना।"),
        ("h", "बारह मिशन"),
        ("p", "गणित, दोहराने के लिए एक पैटर्न, रंगों का क्रम, हूबहू टाइप करने के लिए एक वाक्य, फ़ोन हिलाना, तय संख्या में क़दम चलना, कैमरे से गिने जाने वाले स्क्वैट, जाकर फ़ोटो लेने के लिए एक चीज़, स्कैन करने के लिए एक बारकोड, डिवाइस पर पहचानी जाने वाली एक ड्रॉइंग, एक छोटे खेल का एक चक्कर, और निर्देशित सांस का एक दौर। चार कठिनाई स्तर, और लगातार जितने मिशन आप रखने की हिम्मत करें।"),
        ("h", "यह पीछा नहीं छोड़ता"),
        ("p", "मिशन पूरा किए बिना अलार्म रोकें और वह एक मिनट बाद ऐसे शीर्षक के साथ लौट आता है जो यही कहता है। दस राउंड तक। आपातकालीन रास्ता पहली बार खोलने से ही मौजूद है, क्योंकि किसी को फंसा सकने वाला अलार्म ख़राबी है, सुविधा नहीं।"),
        ("h", "कुछ भी आपके फ़ोन से बाहर नहीं जाता"),
        ("p", "कोई खाता नहीं, कोई सर्वर नहीं, कोई एनालिटिक्स नहीं, किसी और का कोड एक पंक्ति भी नहीं। स्क्वैट गिनने वाले कैमरा फ़्रेम मेमोरी में जांचे जाते हैं और फेंक दिए जाते हैं। आपके अलार्म और आपका इतिहास आपके डिवाइस पर फ़ाइलें हैं, और कहीं नहीं।"),
        ("h", "बारह भाषाएं"),
        ("p", "अंग्रेज़ी, अरबी, जर्मन, स्पेनिश, फ़्रेंच, हिन्दी, इतालवी, जापानी, कोरियाई, पुर्तगाली, रूसी और सरलीकृत चीनी, और अरबी के लिए दाएं से बाएं का वह लेआउट जो उसे चाहिए, बाद में लगाया गया आईना नहीं।"),
    ],
    "it": [
        ("p", "Non dormi troppo perché la sveglia è troppo bassa. Dormi troppo perché spegnerla costa un pollice, mezzo secondo e nessun pensiero."),
        ("p", "Dawnbreak toglie il pollice dall'equazione. Per far tacere la sveglia devi fare qualcosa che chi dorme non può fare: andare in cucina e fotografare il bollitore, fare dieci squat davanti alla fotocamera, risolvere un calcolo che a mezzogiorno ti sembrerebbe facile, scansionare il codice a barre di una scatola in un'altra stanza."),
        ("h", "Dodici missioni"),
        ("p", "Calcoli, uno schema di tessere da rifare, una sequenza di colori, una frase da digitare identica, una scossa, un numero fissato di passi, squat contati dalla fotocamera, un oggetto da andare a fotografare, un codice a barre da scansionare, un disegno riconosciuto sul dispositivo, un giro in un piccolo gioco e un ciclo di respirazione guidata. Quattro difficoltà, e tante missioni di fila quante hai il coraggio di impostare."),
        ("h", "Non ti molla"),
        ("p", "Ferma la sveglia senza finire la missione e torna un minuto dopo, con un titolo che lo dice. Fino a dieci giri. Un'uscita di emergenza c'è dal primo avvio, perché una sveglia che può intrappolare qualcuno è un difetto, non una funzione."),
        ("h", "Niente esce dal telefono"),
        ("p", "Nessun account, nessun server, nessuna analitica, nemmeno una riga di codice di terzi. I fotogrammi con cui si contano gli squat vengono analizzati in memoria e buttati. Le tue sveglie e il tuo storico sono file sul tuo dispositivo e in nessun altro posto."),
        ("h", "Dodici lingue"),
        ("p", "Inglese, arabo, tedesco, spagnolo, francese, hindi, italiano, giapponese, coreano, portoghese, russo e cinese semplificato, con l'impaginazione da destra a sinistra che l'arabo richiede e non uno specchio messo alla fine."),
    ],
    "ja": [
        ("p", "寝坊するのは、目覚ましの音が小さいからではありません。止めるのに親指ひとつ、半秒、考える必要がまったくないからです。"),
        ("p", "Dawnbreak はその親指を取り除きます。アラームを黙らせるには、眠っている人にはできないことをしなければなりません。台所まで歩いてケトルを撮る、カメラの前でスクワットを十回、昼間なら簡単な計算を解く、別の部屋にある箱のバーコードを読み取る。"),
        ("h", "ミッションは12種類"),
        ("p", "計算、並べ直すタイルの模様、色の並び、一字も違わず打つ文章、端末を振る、決めた歩数を歩く、カメラが数えるスクワット、行って撮ってくる対象物、読み取るバーコード、端末が認識する手描き、小さなゲームの一周、そして誘導つきの呼吸。難易度は四段階、連続させるミッションの数は設定するあなたの度胸次第です。"),
        ("h", "簡単には離してくれません"),
        ("p", "ミッションを終えずに止めれば、1分後にそう書かれたタイトルで戻ってきます。最大十回。緊急脱出は初回起動から用意してあります。人を閉じ込められる目覚ましは機能ではなく不具合だからです。"),
        ("h", "端末から何も出ていきません"),
        ("p", "アカウントなし、サーバーなし、解析なし、他社のコードは一行もありません。スクワットを数えるカメラの映像はメモリ上で解析して捨てます。アラームと記録は端末上のファイルであり、それ以外のどこにもありません。"),
        ("h", "12の言語"),
        ("p", "英語、アラビア語、ドイツ語、スペイン語、フランス語、ヒンディー語、イタリア語、日本語、韓国語、ポルトガル語、ロシア語、簡体中国語。アラビア語には後付けの鏡像ではなく、必要な右から左のレイアウトを用意しています。"),
    ],
    "ko": [
        ("p", "늦잠을 자는 건 알람이 작아서가 아닙니다. 끄는 데 엄지 하나, 반 초, 그리고 생각이 전혀 필요하지 않아서입니다."),
        ("p", "Dawnbreak는 그 엄지를 빼버립니다. 알람을 멈추려면 잠든 사람은 할 수 없는 일을 해야 합니다. 부엌까지 걸어가 주전자를 찍고, 카메라 앞에서 스쿼트를 열 번 하고, 낮이라면 쉬웠을 계산을 풀고, 다른 방에 둔 상자의 바코드를 스캔하는 일."),
        ("h", "미션 12가지"),
        ("p", "계산, 다시 맞추는 타일 패턴, 색 순서, 한 글자도 틀리지 않게 치는 문장, 흔들기, 정해진 걸음 수 걷기, 카메라가 세는 스쿼트, 가서 찍어와야 하는 물건, 스캔할 바코드, 기기가 알아보는 그림, 작은 게임 한 바퀴, 그리고 호흡 한 세트. 난이도는 네 단계, 연달아 붙일 미션 수는 당신의 배짱에 달렸습니다."),
        ("h", "쉽게 놓아주지 않습니다"),
        ("p", "미션을 끝내지 않고 알람을 멈추면 1분 뒤에 그렇게 적힌 제목으로 돌아옵니다. 최대 열 번. 비상 탈출은 첫 실행부터 있습니다. 사람을 가둘 수 있는 알람은 기능이 아니라 결함이니까요."),
        ("h", "휴대폰을 벗어나는 것은 없습니다"),
        ("p", "계정 없음, 서버 없음, 분석 없음, 남의 코드는 한 줄도 없음. 스쿼트를 세는 카메라 영상은 메모리에서 분석하고 버립니다. 알람과 기록은 기기 안의 파일이며 그 밖에는 없습니다."),
        ("h", "12개 언어"),
        ("p", "영어, 아랍어, 독일어, 스페인어, 프랑스어, 힌디어, 이탈리아어, 일본어, 한국어, 포르투갈어, 러시아어, 중국어 간체. 아랍어에는 나중에 붙인 거울이 아니라 필요한 오른쪽에서 왼쪽 배치를 넣었습니다."),
    ],
    "pt-BR": [
        ("p", "Você não dorme demais porque o despertador é baixo. Você dorme demais porque desligá-lo custa um polegar, meio segundo e nenhum pensamento."),
        ("p", "O Dawnbreak tira o polegar da conta. Para calar o despertador você tem que fazer algo que quem está dormindo não consegue: ir até a cozinha e fotografar a chaleira, fazer dez agachamentos na frente da câmera, resolver uma conta que ao meio-dia seria fácil, escanear o código de barras de uma caixa em outro quarto."),
        ("h", "Doze missões"),
        ("p", "Cálculo, um padrão de peças para repetir, uma sequência de cores, uma frase para digitar igual, sacudir o telefone, andar um número fixo de passos, agachamentos contados pela câmera, um objeto para ir fotografar, um código de barras para escanear, um desenho que o aparelho reconhece, uma volta num joguinho e uma rodada de respiração guiada. Quatro dificuldades, e quantas missões em sequência você tiver coragem de configurar."),
        ("h", "Ele não solta"),
        ("p", "Pare o despertador sem terminar a missão e ele volta um minuto depois, com um título dizendo exatamente isso. Até dez rodadas. Existe uma saída de emergência desde a primeira abertura, porque um despertador capaz de prender alguém é um defeito, não um recurso."),
        ("h", "Nada sai do seu telefone"),
        ("p", "Sem conta, sem servidor, sem analytics, sem uma linha de código de terceiros. Os quadros da câmera que contam os agachamentos são analisados na memória e descartados. Seus despertadores e seu histórico são arquivos no seu aparelho e em nenhum outro lugar."),
        ("h", "Doze idiomas"),
        ("p", "Inglês, árabe, alemão, espanhol, francês, híndi, italiano, japonês, coreano, português, russo e chinês simplificado, com o layout da direita para a esquerda que o árabe precisa, e não um espelho colado no fim."),
    ],
    "ru": [
        ("p", "Вы просыпаете не потому, что будильник тихий. Вы просыпаете потому, что выключить его стоит одного пальца, половины секунды и никаких размышлений."),
        ("p", "Dawnbreak убирает палец из этого уравнения. Чтобы будильник замолчал, нужно сделать то, чего спящий не может: дойти до кухни и снять чайник, сделать десять приседаний перед камерой, решить арифметику, которая днём кажется простой, отсканировать штрихкод коробки в другой комнате."),
        ("h", "Двенадцать заданий"),
        ("p", "Арифметика, узор из плиток, который надо повторить, последовательность цветов, фраза, которую надо набрать точь-в-точь, встряхивание, заданное число шагов, приседания, которые считает камера, предмет, который надо пойти и снять, штрихкод, рисунок, распознаваемый на устройстве, круг в маленькой игре и подход дыхательного упражнения. Четыре уровня сложности, а заданий подряд — сколько хватит смелости поставить."),
        ("h", "Он не отпускает"),
        ("p", "Остановите будильник, не закончив задание, и через минуту он вернётся под заголовком, который об этом и говорит. До десяти кругов. Аварийный выход есть с первого запуска: будильник, способный запереть человека, — это дефект, а не функция."),
        ("h", "Ничего не покидает телефон"),
        ("p", "Ни учётной записи, ни сервера, ни аналитики, ни одной строки чужого кода. Кадры камеры, по которым считаются приседания, разбираются в памяти и выбрасываются. Ваши будильники и ваша история — файлы на устройстве и больше нигде."),
        ("h", "Двенадцать языков"),
        ("p", "Английский, арабский, немецкий, испанский, французский, хинди, итальянский, японский, корейский, португальский, русский и упрощённый китайский, с той раскладкой справа налево, которая нужна арабскому, а не с зеркалом, приделанным напоследок."),
    ],
    "zh-Hans": [
        ("p", "你睡过头，不是因为闹钟太轻。是因为关掉它只需要一根拇指、半秒钟，以及完全不用想。"),
        ("p", "Dawnbreak 把那根拇指拿掉。要让闹钟安静下来，你得做一件睡着的人做不到的事：走到厨房去拍下水壶，在摄像头前做十个深蹲，解一道中午看来很简单的算术，扫描另一个房间里那个盒子上的条码。"),
        ("h", "十二种任务"),
        ("p", "算术、要复原的方块图案、一串颜色顺序、要一字不差打出的句子、摇一摇、走满指定的步数、由摄像头来数的深蹲、要走过去拍下的物件、要扫的条码、由设备识别的手绘、小游戏里的一圈，以及一轮引导呼吸。四种难度，连续几个任务，取决于你敢设几个。"),
        ("h", "它不轻易放手"),
        ("p", "没做完任务就把闹钟停掉，它会在一分钟后带着一个明说这件事的标题回来。最多十轮。紧急退出从第一次启动就在，因为一个能把人困住的闹钟是缺陷，不是功能。"),
        ("h", "没有东西离开你的手机"),
        ("p", "没有账号，没有服务器，没有统计分析，没有一行别人的代码。用来数深蹲的画面在内存里分析完就丢掉。你的闹钟和记录是设备上的文件，别的地方没有。"),
        ("h", "十二种语言"),
        ("p", "英语、阿拉伯语、德语、西班牙语、法语、印地语、意大利语、日语、韩语、葡萄牙语、俄语和简体中文，并为阿拉伯语准备了它需要的从右到左布局，而不是事后加上的一面镜子。"),
    ],
}

PRIVACY = {
    "en": [
        ("p", "Dawnbreak collects nothing. There is no account to create, no server to talk to, and no analytics of any kind. This page is short because there is very little to describe."),
        ("h", "What stays on your phone"),
        ("p", "Your alarms, the missions attached to them, your preferences and your wake-up history are written to files inside the app's own container on your device. They are never uploaded. If you back your device up to iCloud or to a computer, they are part of that backup, which is between you and Apple."),
        ("h", "The camera and the motion sensors"),
        ("p", "Three missions use the camera: photographing an object, scanning a barcode, and counting squats. Frames are analysed on the device, in memory, while the mission is on screen, and are discarded as they are replaced. Nothing is written to your photo library and nothing is transmitted. Three missions read the motion sensors: to count steps, to detect a shake, and to prove the phone is resting on something while squats are counted. Those readings are used as they arrive and never stored."),
        ("h", "Children"),
        ("p", "The app collects nothing from anyone, at any age, so there is nothing here to treat differently for a child."),
        ("h", "Changes"),
        ("p", "If any of the above stops being true, this page changes in the same release that makes it untrue."),
    ],
    "ar": [
        ("p", "‏Dawnbreak لا يجمع أي شيء. لا حساب تُنشئه، ولا خادم يتواصل معه، ولا تحليلات من أي نوع. هذه الصفحة قصيرة لأن ما يُوصَف قليل جدًا."),
        ("h", "ما يبقى على هاتفك"),
        ("p", "منبّهاتك، والمهام المرتبطة بها، وإعداداتك، وسجل استيقاظك، تُكتب في ملفات داخل حاوية التطبيق على جهازك. ولا تُرفع أبدًا. وإذا أخذت نسخة احتياطية إلى iCloud أو إلى حاسوب، فهي جزء من تلك النسخة، وذلك أمر بينك وبين Apple."),
        ("h", "الكاميرا وحساسات الحركة"),
        ("p", "ثلاث مهام تستخدم الكاميرا: تصوير شيء، وقراءة باركود، وعدّ القرفصاء. تُحلَّل الصور على الجهاز، في الذاكرة، طوال وجود المهمة على الشاشة، ثم تُرمى مع وصول ما يليها. ولا يُكتب شيء في مكتبة صورك ولا يُرسل شيء. وثلاث مهام تقرأ حساسات الحركة: لعدّ الخطوات، ولاكتشاف الرجّة، ولإثبات أن الهاتف مستقر على شيء أثناء عدّ القرفصاء. وتُستخدم القراءات لحظة وصولها ولا تُخزَّن."),
        ("h", "الأطفال"),
        ("p", "التطبيق لا يجمع شيئًا من أي شخص في أي عمر، فلا يوجد هنا ما يُعامل بشكل مختلف مع طفل."),
        ("h", "التغييرات"),
        ("p", "إن توقف أي ممّا سبق عن كونه صحيحًا، فستتغير هذه الصفحة في الإصدار نفسه الذي جعله غير صحيح."),
    ],
    "de": [
        ("p", "Dawnbreak erhebt nichts. Es gibt kein Konto, keinen Server, mit dem gesprochen wird, und keine Analyse irgendeiner Art. Diese Seite ist kurz, weil es sehr wenig zu beschreiben gibt."),
        ("h", "Was auf deinem Telefon bleibt"),
        ("p", "Deine Wecker, die daran hängenden Missionen, deine Einstellungen und deine Aufwach-Historie werden in Dateien im eigenen Container der App auf deinem Gerät geschrieben. Sie werden nie hochgeladen. Wenn du dein Gerät in iCloud oder auf einen Computer sicherst, sind sie Teil dieser Sicherung, und das ist eine Sache zwischen dir und Apple."),
        ("h", "Kamera und Bewegungssensoren"),
        ("p", "Drei Missionen nutzen die Kamera: einen Gegenstand fotografieren, einen Barcode scannen, Kniebeugen zählen. Die Bilder werden auf dem Gerät im Speicher ausgewertet, solange die Mission zu sehen ist, und verworfen, sobald das nächste kommt. In deine Fotobibliothek wird nichts geschrieben und übertragen wird nichts. Drei Missionen lesen die Bewegungssensoren: um Schritte zu zählen, um ein Schütteln zu erkennen und um zu belegen, dass das iPhone beim Zählen von Kniebeugen irgendwo aufliegt. Diese Werte werden benutzt, wie sie eintreffen, und nie gespeichert."),
        ("h", "Kinder"),
        ("p", "Die App erhebt von niemandem etwas, in keinem Alter, also gibt es hier nichts, was für ein Kind anders behandelt werden müsste."),
        ("h", "Änderungen"),
        ("p", "Sollte etwas davon aufhören zu stimmen, ändert sich diese Seite in derselben Version, die es nicht mehr stimmen lässt."),
    ],
    "es": [
        ("p", "Dawnbreak no recoge nada. No hay cuenta que crear, ni servidor con el que hablar, ni analítica de ningún tipo. Esta página es corta porque hay muy poco que describir."),
        ("h", "Lo que se queda en tu teléfono"),
        ("p", "Tus alarmas, las misiones que llevan asociadas, tus preferencias y tu historial de despertares se escriben en archivos dentro del contenedor propio de la app, en tu dispositivo. Nunca se suben. Si respaldas el dispositivo en iCloud o en un ordenador, forman parte de ese respaldo, que es un asunto entre tú y Apple."),
        ("h", "La cámara y los sensores de movimiento"),
        ("p", "Tres misiones usan la cámara: fotografiar un objeto, escanear un código de barras y contar sentadillas. Los fotogramas se analizan en el dispositivo, en memoria, mientras la misión está en pantalla, y se descartan al llegar el siguiente. No se escribe nada en tu carrete y no se transmite nada. Tres misiones leen los sensores de movimiento: para contar pasos, para detectar una sacudida y para comprobar que el teléfono está apoyado en algo mientras se cuentan las sentadillas. Esas lecturas se usan según llegan y nunca se guardan."),
        ("h", "Menores"),
        ("p", "La app no recoge nada de nadie, a ninguna edad, así que no hay aquí nada que deba tratarse de otro modo para un menor."),
        ("h", "Cambios"),
        ("p", "Si algo de lo anterior deja de ser cierto, esta página cambia en la misma versión que lo deja de serlo."),
    ],
    "fr": [
        ("p", "Dawnbreak ne collecte rien. Pas de compte à créer, pas de serveur à qui parler, aucune statistique d'aucune sorte. Cette page est courte parce qu'il y a très peu à décrire."),
        ("h", "Ce qui reste sur votre téléphone"),
        ("p", "Vos réveils, les missions qui y sont attachées, vos préférences et votre historique de réveils sont écrits dans des fichiers à l'intérieur du conteneur de l'application, sur votre appareil. Ils ne sont jamais envoyés. Si vous sauvegardez votre appareil sur iCloud ou sur un ordinateur, ils font partie de cette sauvegarde, ce qui se joue entre vous et Apple."),
        ("h", "La caméra et les capteurs de mouvement"),
        ("p", "Trois missions utilisent la caméra : photographier un objet, scanner un code-barres, compter des squats. Les images sont analysées sur l'appareil, en mémoire, pendant que la mission est à l'écran, et jetées dès que la suivante arrive. Rien n'est écrit dans votre photothèque et rien n'est transmis. Trois missions lisent les capteurs de mouvement : pour compter des pas, pour détecter une secousse, et pour prouver que le téléphone est posé pendant que les squats sont comptés. Ces mesures sont utilisées à mesure et jamais conservées."),
        ("h", "Enfants"),
        ("p", "L'application ne collecte rien de personne, à aucun âge, il n'y a donc rien ici à traiter différemment pour un enfant."),
        ("h", "Modifications"),
        ("p", "Si l'un des points ci-dessus cesse d'être vrai, cette page change dans la version même qui le rend faux."),
    ],
    "hi": [
        ("p", "Dawnbreak कुछ भी इकट्ठा नहीं करता। कोई खाता बनाना नहीं है, कोई सर्वर से बात नहीं होती, और किसी भी तरह का एनालिटिक्स नहीं है। यह पेज छोटा है क्योंकि बताने के लिए बहुत कम है।"),
        ("h", "आपके फ़ोन पर क्या रहता है"),
        ("p", "आपके अलार्म, उनसे जुड़े मिशन, आपकी पसंद और आपका जागने का इतिहास आपके डिवाइस पर ऐप के अपने कंटेनर के अंदर फ़ाइलों में लिखे जाते हैं। ये कभी अपलोड नहीं होते। अगर आप डिवाइस का बैकअप iCloud या कंप्यूटर पर लेते हैं, तो ये उस बैकअप का हिस्सा होते हैं, जो आपके और Apple के बीच की बात है।"),
        ("h", "कैमरा और मोशन सेंसर"),
        ("p", "तीन मिशन कैमरे का इस्तेमाल करते हैं: किसी चीज़ की फ़ोटो लेना, बारकोड स्कैन करना, और स्क्वैट गिनना। फ़्रेम डिवाइस पर, मेमोरी में, तब तक जांचे जाते हैं जब तक मिशन स्क्रीन पर है, और अगला आते ही फेंक दिए जाते हैं। आपकी फ़ोटो लाइब्रेरी में कुछ नहीं लिखा जाता और कुछ भेजा नहीं जाता। तीन मिशन मोशन सेंसर पढ़ते हैं: क़दम गिनने के लिए, हिलाना पहचानने के लिए, और स्क्वैट गिनते समय यह प्रमाणित करने के लिए कि फ़ोन किसी चीज़ पर टिका है। वे रीडिंग आते ही इस्तेमाल होती हैं और कभी संग्रहित नहीं होतीं।"),
        ("h", "बच्चे"),
        ("p", "ऐप किसी भी उम्र के किसी भी व्यक्ति से कुछ इकट्ठा नहीं करता, इसलिए यहां किसी बच्चे के लिए अलग बरताव करने जैसा कुछ नहीं है।"),
        ("h", "बदलाव"),
        ("p", "अगर ऊपर लिखी कोई बात सच न रह जाए, तो यह पेज उसी रिलीज़ में बदल जाएगा जो उसे बदल देती है।"),
    ],
    "it": [
        ("p", "Dawnbreak non raccoglie nulla. Non c'è un account da creare, non c'è un server con cui parlare, non c'è analitica di alcun tipo. Questa pagina è corta perché c'è molto poco da descrivere."),
        ("h", "Cosa resta sul telefono"),
        ("p", "Le tue sveglie, le missioni collegate, le tue preferenze e il tuo storico dei risvegli vengono scritti in file dentro il container dell'app, sul tuo dispositivo. Non vengono mai caricati. Se fai il backup del dispositivo su iCloud o su un computer, fanno parte di quel backup, che è una questione fra te e Apple."),
        ("h", "La fotocamera e i sensori di movimento"),
        ("p", "Tre missioni usano la fotocamera: fotografare un oggetto, scansionare un codice a barre, contare gli squat. I fotogrammi vengono analizzati sul dispositivo, in memoria, mentre la missione è a schermo, e scartati appena arriva il successivo. Nella tua libreria foto non viene scritto niente e niente viene trasmesso. Tre missioni leggono i sensori di movimento: per contare i passi, per rilevare una scossa e per dimostrare che il telefono è appoggiato mentre si contano gli squat. Quelle letture si usano man mano e non vengono mai salvate."),
        ("h", "Bambini"),
        ("p", "L'app non raccoglie nulla da nessuno, a nessuna età, quindi qui non c'è niente da trattare diversamente per un bambino."),
        ("h", "Modifiche"),
        ("p", "Se qualcosa di quanto sopra smette di essere vero, questa pagina cambia nella stessa versione che lo rende falso."),
    ],
    "ja": [
        ("p", "Dawnbreak は何も収集しません。作るアカウントはなく、通信する相手のサーバーもなく、いかなる解析もありません。このページが短いのは、書くことがほとんどないからです。"),
        ("h", "端末に残るもの"),
        ("p", "アラーム、それに結びついたミッション、設定、起床の記録は、端末上のアプリ専用の領域にあるファイルに書かれます。アップロードされることはありません。iCloud やコンピュータにバックアップを取れば、それはバックアップの一部になります。そこから先はあなたと Apple の間の話です。"),
        ("h", "カメラとモーションセンサー"),
        ("p", "カメラを使うミッションは三つです。対象物の撮影、バーコードの読み取り、スクワットの計数。映像はミッションが表示されている間、端末上のメモリで解析され、次の映像が来た時点で捨てられます。写真ライブラリには何も書き込まれず、何も送信されません。モーションセンサーを読むミッションは三つです。歩数の計数、振りの検出、そしてスクワットを数えるあいだ端末が何かに置かれていることの確認。その値は届いたその場で使われ、記録されることはありません。"),
        ("h", "子どもについて"),
        ("p", "年齢にかかわらず誰からも何も収集しないので、子どもに対して別に扱うべきものがここにはありません。"),
        ("h", "変更"),
        ("p", "上のどれかが事実でなくなったときは、事実でなくしたリリースと同じリリースでこのページも変わります。"),
    ],
    "ko": [
        ("p", "Dawnbreak는 아무것도 수집하지 않습니다. 만들 계정도, 이야기할 서버도, 어떤 종류의 분석도 없습니다. 이 페이지가 짧은 것은 설명할 것이 거의 없기 때문입니다."),
        ("h", "휴대폰에 남는 것"),
        ("p", "알람, 거기에 붙은 미션, 설정, 기상 기록은 기기 안 앱 전용 영역의 파일에 기록됩니다. 업로드되는 일은 없습니다. iCloud나 컴퓨터로 백업하면 그 백업의 일부가 되며, 그다음은 당신과 Apple 사이의 일입니다."),
        ("h", "카메라와 모션 센서"),
        ("p", "카메라를 쓰는 미션은 셋입니다. 물건 촬영, 바코드 스캔, 스쿼트 계수. 영상은 미션이 화면에 있는 동안 기기 안 메모리에서 분석되고, 다음 영상이 오면 버려집니다. 사진 라이브러리에는 아무것도 기록되지 않고, 전송되는 것도 없습니다. 모션 센서를 읽는 미션은 셋입니다. 걸음 수 세기, 흔들기 감지, 그리고 스쿼트를 세는 동안 폰이 어딘가에 놓여 있음을 확인하기. 그 값은 들어오는 대로 쓰이고 저장되지 않습니다."),
        ("h", "아동"),
        ("p", "나이와 무관하게 누구에게서도 아무것도 수집하지 않으므로, 아동에게 다르게 다룰 것이 여기에는 없습니다."),
        ("h", "변경"),
        ("p", "위의 내용 중 무엇이든 사실이 아니게 되면, 사실이 아니게 만든 그 릴리스에서 이 페이지도 함께 바뀝니다."),
    ],
    "pt-BR": [
        ("p", "O Dawnbreak não coleta nada. Não há conta para criar, não há servidor com quem falar e não há analytics de nenhum tipo. Esta página é curta porque há muito pouco a descrever."),
        ("h", "O que fica no seu telefone"),
        ("p", "Seus despertadores, as missões ligadas a eles, suas preferências e seu histórico de despertares são gravados em arquivos dentro do container da própria app, no seu aparelho. Nunca são enviados. Se você faz backup do aparelho no iCloud ou num computador, eles fazem parte desse backup, o que é assunto entre você e a Apple."),
        ("h", "A câmera e os sensores de movimento"),
        ("p", "Três missões usam a câmera: fotografar um objeto, escanear um código de barras e contar agachamentos. Os quadros são analisados no aparelho, na memória, enquanto a missão está na tela, e descartados quando chega o seguinte. Nada é gravado na sua biblioteca de fotos e nada é transmitido. Três missões leem os sensores de movimento: para contar passos, para detectar uma sacudida e para comprovar que o telefone está apoiado em algo enquanto os agachamentos são contados. Essas leituras são usadas conforme chegam e nunca guardadas."),
        ("h", "Crianças"),
        ("p", "A app não coleta nada de ninguém, em nenhuma idade, então não há aqui nada a tratar de outro modo para uma criança."),
        ("h", "Alterações"),
        ("p", "Se alguma das afirmações acima deixar de ser verdade, esta página muda na mesma versão que a torna falsa."),
    ],
    "ru": [
        ("p", "Dawnbreak ничего не собирает. Нет учётной записи, нет сервера, с которым он общается, нет аналитики любого рода. Эта страница короткая, потому что описывать почти нечего."),
        ("h", "Что остаётся на телефоне"),
        ("p", "Ваши будильники, привязанные к ним задания, настройки и история пробуждений записываются в файлы внутри собственного контейнера приложения на вашем устройстве. Они никогда не выгружаются. Если вы делаете резервную копию устройства в iCloud или на компьютер, они входят в неё, и это уже дело между вами и Apple."),
        ("h", "Камера и датчики движения"),
        ("p", "Камеру используют три задания: снять предмет, отсканировать штрихкод, посчитать приседания. Кадры разбираются на устройстве, в памяти, пока задание на экране, и выбрасываются с приходом следующего. В вашу медиатеку ничего не пишется и ничего не передаётся. Три задания читают датчики движения: чтобы считать шаги, чтобы заметить встряхивание и чтобы убедиться, что телефон на что-то опирается, пока считаются приседания. Эти показания используются по мере поступления и никогда не сохраняются."),
        ("h", "Дети"),
        ("p", "Приложение ничего не собирает ни у кого и ни в каком возрасте, поэтому здесь нечего рассматривать иначе для ребёнка."),
        ("h", "Изменения"),
        ("p", "Если что-либо из перечисленного перестанет быть правдой, эта страница изменится в том же выпуске, который сделает её неправдой."),
    ],
    "zh-Hans": [
        ("p", "Dawnbreak 不收集任何东西。没有要注册的账号，没有要通信的服务器，也没有任何形式的统计分析。这一页很短，因为可写的实在不多。"),
        ("h", "留在你手机上的东西"),
        ("p", "你的闹钟、挂在闹钟上的任务、你的偏好设置和你的起床记录，都写进设备上属于这个应用自己的容器里的文件。它们从不上传。如果你把设备备份到 iCloud 或电脑，它们会在那份备份里，而那是你和 Apple 之间的事。"),
        ("h", "摄像头与运动传感器"),
        ("p", "有三个任务用到摄像头：拍下一件物品、扫描条码、数深蹲。画面在任务显示期间于设备内存中分析，下一帧到来时即丢弃。不会往你的照片图库里写入任何东西，也不会传出任何东西。有三个任务读取运动传感器：数步数、识别摇动，以及在数深蹲时确认手机确实靠在东西上。这些读数随到随用，从不保存。"),
        ("h", "儿童"),
        ("p", "本应用不从任何年龄的任何人处收集任何东西，因此这里没有需要对儿童另行处理的部分。"),
        ("h", "变更"),
        ("p", "如果上面任何一条不再成立，这一页会在让它不再成立的那个版本里一起改。"),
    ],
}

SUPPORT = {
    "en": [
        ("p", "Dawnbreak is an alarm that will not switch off until you have done something. Most questions are about the alarm not ringing, or about the mission being harder than expected at six in the morning. Both are below."),
        ("h", "The alarm did not ring"),
        ("ul", [
            "Alarms need permission. The app asks once, on the first launch; if it was declined, turn it on in Settings, under Dawnbreak.",
            "An alarm you saved but never switched on will not ring. The toggle on the row is the one that matters.",
            "Focus and Do Not Disturb do not silence it. Alarms are exempt by design.",
            "A phone that ran out of battery overnight cannot ring. Low Power Mode on its own is fine.",
        ]),
        ("h", "I cannot finish the mission"),
        ("p", "Every mission screen has a way out. Tap the cross in its top corner, confirm, and the alarm stops for that morning: a repeating alarm stays set for its next day, a one-time alarm is switched off. No setting removes it."),
        ("h", "Deleting everything"),
        ("p", "Deleting the app deletes the alarms and the history with it. There is no copy anywhere else, and nothing to ask us to erase."),
        ("h", "Anything else"),
        ("p", "Write to <a href=\"mailto:fastpapershot.supp@outlook.com\">fastpapershot.supp@outlook.com</a> and it will be read. Please include your iOS version, the mission, and what the alarm was set to."),
    ],
    "ar": [
        ("p", "‏Dawnbreak منبّه لا ينطفئ حتى تفعل شيئًا. أكثر الأسئلة تدور حول منبّه لم يرن، أو حول مهمة تبدو أصعب مما توقعت في السادسة صباحًا. وكلاهما هنا."),
        ("h", "المنبّه لم يرن"),
        ("ul", [
            "المنبّهات تحتاج إذنًا. يطلبه التطبيق مرة واحدة عند أول تشغيل؛ فإن رُفض، شغّله من الإعدادات ضمن Dawnbreak.",
            "المنبّه الذي حفظته ولم تشغّله لن يرن. المفتاح الموجود على السطر هو المهم.",
            "‏Focus ووضع عدم الإزعاج لا يُسكتانه. المنبّهات مستثناة بالتصميم.",
            "الهاتف الذي نفدت بطاريته ليلًا لا يستطيع أن يرن. أما وضع الطاقة المنخفضة وحده فلا مشكلة فيه.",
        ]),
        ("h", "لا أستطيع إنهاء المهمة"),
        ("p", "لكل شاشة مهمة مخرج. اضغط على علامة × في زاويتها العليا ثم أكّد، فيتوقف المنبّه لذلك الصباح: المنبّه المتكرر يبقى مضبوطًا ليومه التالي، والمنبّه لمرة واحدة يُطفأ. ولا يوجد إعداد يزيله."),
        ("h", "حذف كل شيء"),
        ("p", "حذف التطبيق يحذف المنبّهات والسجل معه. لا توجد نسخة في أي مكان آخر، ولا شيء تطلب منّا محوه."),
        ("h", "أي شيء آخر"),
        ("p", "اكتب إلى <a href=\"mailto:fastpapershot.supp@outlook.com\">fastpapershot.supp@outlook.com</a> وستُقرأ رسالتك. أرجو ذكر إصدار iOS، والمهمة، وما كان المنبّه مضبوطًا عليه."),
    ],
    "de": [
        ("p", "Dawnbreak ist ein Wecker, der sich erst abschaltet, wenn du etwas getan hast. Die meisten Fragen drehen sich um einen Wecker, der nicht geklingelt hat, oder um eine Mission, die um sechs Uhr morgens schwerer ist als gedacht. Beides steht hier."),
        ("h", "Der Wecker hat nicht geklingelt"),
        ("ul", [
            "Wecker brauchen eine Berechtigung. Die App fragt einmal, beim ersten Start; wurde sie abgelehnt, schalte sie in den Einstellungen unter Dawnbreak ein.",
            "Ein Wecker, den du gespeichert aber nie eingeschaltet hast, klingelt nicht. Entscheidend ist der Schalter in der Zeile.",
            "Fokus und Nicht stören schalten ihn nicht stumm. Wecker sind bewusst ausgenommen.",
            "Ein Telefon, dessen Akku nachts leer wurde, kann nicht klingeln. Der Energiesparmodus allein ist unproblematisch.",
        ]),
        ("h", "Ich schaffe die Mission nicht"),
        ("p", "Jeder Missionsbildschirm hat einen Ausweg. Tippe oben in der Ecke auf das Kreuz, bestätige, und der Wecker hört für diesen Morgen auf: Ein wiederkehrender Wecker bleibt für seinen nächsten Tag gestellt, ein einmaliger wird ausgeschaltet. Keine Einstellung entfernt ihn."),
        ("h", "Alles löschen"),
        ("p", "Die App zu löschen löscht die Wecker und die Historie mit. Es gibt nirgends eine Kopie und nichts, um dessen Löschung du uns bitten müsstest."),
        ("h", "Alles andere"),
        ("p", "Schreib an <a href=\"mailto:fastpapershot.supp@outlook.com\">fastpapershot.supp@outlook.com</a>, die Nachricht wird gelesen. Bitte nenne deine iOS-Version, die Mission und wie der Wecker eingestellt war."),
    ],
    "es": [
        ("p", "Dawnbreak es un despertador que no se apaga hasta que has hecho algo. Casi todas las preguntas son sobre una alarma que no sonó o sobre una misión más difícil de lo previsto a las seis de la mañana. Las dos están aquí."),
        ("h", "La alarma no sonó"),
        ("ul", [
            "Las alarmas necesitan permiso. La app lo pide una vez, en el primer arranque; si se denegó, actívalo en Ajustes, dentro de Dawnbreak.",
            "Una alarma que guardaste pero nunca activaste no suena. El interruptor de la fila es el que cuenta.",
            "Concentración y No molestar no la silencian. Las alarmas están exentas a propósito.",
            "Un teléfono que se quedó sin batería de noche no puede sonar. El modo de bajo consumo por sí solo no estorba.",
        ]),
        ("h", "No consigo terminar la misión"),
        ("p", "Toda pantalla de misión tiene una salida. Toca la cruz de su esquina superior, confirma, y la alarma se detiene por esa mañana: una alarma que se repite sigue puesta para su próximo día, una alarma de una sola vez se desactiva. Ningún ajuste la quita."),
        ("h", "Borrarlo todo"),
        ("p", "Borrar la app borra las alarmas y el historial con ella. No hay copia en ningún otro sitio, ni nada que pedirnos que eliminemos."),
        ("h", "Cualquier otra cosa"),
        ("p", "Escribe a <a href=\"mailto:fastpapershot.supp@outlook.com\">fastpapershot.supp@outlook.com</a> y se leerá. Indica tu versión de iOS, la misión y cómo estaba puesta la alarma."),
    ],
    "fr": [
        ("p", "Dawnbreak est un réveil qui ne s'éteint pas avant que vous ayez fait quelque chose. La plupart des questions portent sur un réveil qui n'a pas sonné, ou sur une mission plus difficile que prévu à six heures du matin. Les deux sont ici."),
        ("h", "Le réveil n'a pas sonné"),
        ("ul", [
            "Les réveils demandent une autorisation. L'application la demande une fois, au premier lancement ; si elle a été refusée, activez-la dans Réglages, sous Dawnbreak.",
            "Un réveil enregistré mais jamais activé ne sonnera pas. C'est l'interrupteur sur la ligne qui compte.",
            "Concentration et Ne pas déranger ne le font pas taire. Les réveils en sont exemptés par conception.",
            "Un téléphone dont la batterie s'est vidée dans la nuit ne peut pas sonner. Le mode économie d'énergie seul ne gêne rien.",
        ]),
        ("h", "Je n'arrive pas à finir la mission"),
        ("p", "Chaque écran de mission a une sortie. Touchez la croix dans son coin supérieur, confirmez, et le réveil s'arrête pour ce matin-là : un réveil répété reste réglé pour son prochain jour, un réveil unique est désactivé. Aucun réglage ne la retire."),
        ("h", "Tout supprimer"),
        ("p", "Supprimer l'application supprime les réveils et l'historique avec. Il n'y a de copie nulle part ailleurs, et rien à nous demander d'effacer."),
        ("h", "Autre chose"),
        ("p", "Écrivez à <a href=\"mailto:fastpapershot.supp@outlook.com\">fastpapershot.supp@outlook.com</a>, le message sera lu. Précisez votre version d'iOS, la mission, et le réglage du réveil."),
    ],
    "hi": [
        ("p", "Dawnbreak एक अलार्म है जो कुछ करने तक बंद नहीं होता। ज़्यादातर सवाल अलार्म न बजने के बारे में होते हैं, या सुबह छह बजे मिशन के उम्मीद से ज़्यादा मुश्किल लगने के बारे में। दोनों नीचे हैं।"),
        ("h", "अलार्म नहीं बजा"),
        ("ul", [
            "अलार्म के लिए अनुमति चाहिए। ऐप पहली बार खुलने पर एक बार पूछता है; मना कर दिया हो तो Settings में Dawnbreak के नीचे चालू करें।",
            "जो अलार्म आपने सहेजा पर कभी चालू नहीं किया, वह नहीं बजेगा। पंक्ति पर लगा टॉगल ही मायने रखता है।",
            "Focus और Do Not Disturb इसे चुप नहीं कराते। अलार्म को जान-बूझकर छूट दी गई है।",
            "रात में बैटरी ख़त्म हो चुका फ़ोन बज नहीं सकता। अकेला Low Power Mode कोई अड़चन नहीं है।",
        ]),
        ("h", "मैं मिशन पूरा नहीं कर पा रहा"),
        ("p", "हर मिशन स्क्रीन पर बाहर निकलने का रास्ता है। उसके ऊपरी कोने में क्रॉस दबाएँ, पुष्टि करें, और अलार्म उस सुबह के लिए रुक जाएगा: दोहराने वाला अलार्म अपने अगले दिन के लिए लगा रहता है, एक बार वाला अलार्म बंद हो जाता है। कोई सेटिंग इसे हटाती नहीं।"),
        ("h", "सब कुछ मिटाना"),
        ("p", "ऐप हटाने से अलार्म और इतिहास भी उसके साथ हट जाते हैं। कहीं और कोई प्रति नहीं है, और हमसे मिटाने को कहने जैसा कुछ नहीं है।"),
        ("h", "और कुछ"),
        ("p", "<a href=\"mailto:fastpapershot.supp@outlook.com\">fastpapershot.supp@outlook.com</a> पर लिखें, संदेश पढ़ा जाएगा। कृपया अपना iOS संस्करण, मिशन, और अलार्म की सेटिंग बताएं।"),
    ],
    "it": [
        ("p", "Dawnbreak è una sveglia che non si spegne finché non hai fatto qualcosa. Quasi tutte le domande riguardano una sveglia che non ha suonato, o una missione più difficile del previsto alle sei del mattino. Ci sono entrambe qui."),
        ("h", "La sveglia non ha suonato"),
        ("ul", [
            "Le sveglie richiedono un permesso. L'app lo chiede una volta, al primo avvio; se è stato negato, attivalo in Impostazioni, sotto Dawnbreak.",
            "Una sveglia salvata ma mai attivata non suona. Conta l'interruttore sulla riga.",
            "Full Immersion e Non disturbare non la silenziano. Le sveglie sono escluse per scelta.",
            "Un telefono rimasto senza batteria di notte non può suonare. La modalità Risparmio energetico da sola non dà problemi.",
        ]),
        ("h", "Non riesco a finire la missione"),
        ("p", "Ogni schermata di missione ha un'uscita. Tocca la croce nell'angolo in alto, conferma, e la sveglia si ferma per quella mattina: una sveglia ripetuta resta impostata per il giorno successivo, una sveglia singola si disattiva. Nessuna impostazione la toglie."),
        ("h", "Cancellare tutto"),
        ("p", "Eliminare l'app elimina le sveglie e lo storico con essa. Non c'è una copia altrove, e non c'è nulla da chiederci di cancellare."),
        ("h", "Qualsiasi altra cosa"),
        ("p", "Scrivi a <a href=\"mailto:fastpapershot.supp@outlook.com\">fastpapershot.supp@outlook.com</a> e il messaggio verrà letto. Indica la versione di iOS, la missione e com'era impostata la sveglia."),
    ],
    "ja": [
        ("p", "Dawnbreak は、何かをするまで切れない目覚ましです。届く質問のほとんどは、鳴らなかったという話か、朝六時のミッションが思ったより難しいという話です。どちらも以下にあります。"),
        ("h", "アラームが鳴らなかった"),
        ("ul", [
            "アラームには許可が必要です。初回起動時に一度だけ尋ねます。断ってしまった場合は、設定の Dawnbreak からオンにしてください。",
            "保存しただけでオンにしていないアラームは鳴りません。効くのは行にあるスイッチです。",
            "集中モードやおやすみモードでは消音されません。アラームは意図的に対象外です。",
            "夜のあいだにバッテリーが切れた端末は鳴れません。低電力モードそのものは問題ありません。",
        ]),
        ("h", "ミッションを終えられません"),
        ("p", "どのミッション画面にも出口があります。上隅の×を押して確認すれば、その朝のアラームは止まります。繰り返しのアラームは次の日のために残り、1回だけのアラームはオフになります。これを消す設定はありません。"),
        ("h", "すべて削除する"),
        ("p", "アプリを削除すれば、アラームと記録も一緒に消えます。ほかに控えはなく、こちらに消去を依頼するものもありません。"),
        ("h", "それ以外"),
        ("p", "<a href=\"mailto:fastpapershot.supp@outlook.com\">fastpapershot.supp@outlook.com</a> までご連絡ください。必ず読みます。iOSのバージョン、ミッション、アラームの設定内容を書き添えてください。"),
    ],
    "ko": [
        ("p", "Dawnbreak는 무언가를 하기 전까지 꺼지지 않는 알람입니다. 들어오는 질문은 대개 알람이 울리지 않았다는 것, 아니면 아침 여섯 시의 미션이 생각보다 어렵다는 것입니다. 둘 다 아래에 있습니다."),
        ("h", "알람이 울리지 않았습니다"),
        ("ul", [
            "알람에는 권한이 필요합니다. 앱이 첫 실행에서 한 번 묻습니다. 거절했다면 설정의 Dawnbreak에서 켜주세요.",
            "저장만 하고 켜지 않은 알람은 울리지 않습니다. 중요한 것은 행에 있는 스위치입니다.",
            "집중 모드와 방해금지 모드는 이 알람을 음소거하지 않습니다. 알람은 의도적으로 예외입니다.",
            "밤사이 배터리가 다 떨어진 기기는 울릴 수 없습니다. 저전력 모드 자체는 문제가 없습니다.",
        ]),
        ("h", "미션을 끝낼 수 없습니다"),
        ("p", "모든 미션 화면에는 나가는 길이 있습니다. 위쪽 모서리의 ×를 누르고 확인하면 그날 아침의 알람이 멈춥니다. 반복 알람은 다음 날을 위해 그대로 남고, 한 번만 울리는 알람은 꺼집니다. 이를 없애는 설정은 없습니다."),
        ("h", "전부 삭제하기"),
        ("p", "앱을 삭제하면 알람과 기록도 함께 사라집니다. 다른 곳에 사본이 없고, 저희에게 삭제를 요청할 것도 없습니다."),
        ("h", "그 밖의 문의"),
        ("p", "<a href=\"mailto:fastpapershot.supp@outlook.com\">fastpapershot.supp@outlook.com</a> 으로 보내 주시면 읽습니다. iOS 버전, 미션, 알람 설정 내용을 함께 적어 주세요."),
    ],
    "pt-BR": [
        ("p", "O Dawnbreak é um despertador que não desliga até você fazer algo. Quase toda pergunta é sobre um despertador que não tocou, ou sobre uma missão mais difícil do que se esperava às seis da manhã. As duas estão aqui."),
        ("h", "O despertador não tocou"),
        ("ul", [
            "Despertadores precisam de permissão. A app pede uma vez, na primeira abertura; se foi negada, ative em Ajustes, dentro de Dawnbreak.",
            "Um despertador que você salvou mas nunca ligou não toca. O que vale é a chave na linha.",
            "Foco e Não Perturbe não o silenciam. Despertadores são isentos de propósito.",
            "Um telefone que ficou sem bateria de madrugada não consegue tocar. O Modo de Pouca Energia por si só não atrapalha.",
        ]),
        ("h", "Não consigo terminar a missão"),
        ("p", "Toda tela de missão tem uma saída. Toque na cruz no canto de cima, confirme, e o despertador para naquela manhã: um despertador que se repete continua ativo para o próximo dia, um despertador único é desligado. Nenhum ajuste a remove."),
        ("h", "Apagar tudo"),
        ("p", "Apagar a app apaga os despertadores e o histórico junto. Não existe cópia em outro lugar, nem nada para pedir que a gente apague."),
        ("h", "Qualquer outra coisa"),
        ("p", "Escreva para <a href=\"mailto:fastpapershot.supp@outlook.com\">fastpapershot.supp@outlook.com</a> e a mensagem será lida. Informe sua versão do iOS, a missão e como o despertador estava configurado."),
    ],
    "ru": [
        ("p", "Dawnbreak — будильник, который не выключается, пока вы что-нибудь не сделаете. Почти все вопросы про то, что будильник не зазвонил, или про задание, которое в шесть утра оказалось труднее, чем ожидалось. И то, и другое ниже."),
        ("h", "Будильник не зазвонил"),
        ("ul", [
            "Будильникам нужно разрешение. Приложение спрашивает один раз, при первом запуске; если было отказано, включите его в Настройках, в разделе Dawnbreak.",
            "Будильник, который вы сохранили, но не включили, не зазвонит. Решает переключатель в строке.",
            "Фокусирование и режим «Не беспокоить» его не приглушают. Будильники намеренно исключены.",
            "Телефон, у которого за ночь села батарея, зазвонить не может. Сам режим энергосбережения при этом не мешает.",
        ]),
        ("h", "Я не могу выполнить задание"),
        ("p", "На каждом экране задания есть выход. Нажмите крестик в верхнем углу, подтвердите, и будильник остановится на это утро: повторяющийся будильник останется на следующий день, разовый будет выключен. Никакая настройка его не убирает."),
        ("h", "Удалить всё"),
        ("p", "Удаление приложения удаляет вместе с ним будильники и историю. Копии нигде нет, и просить нас что-то стереть не нужно."),
        ("h", "Всё остальное"),
        ("p", "Напишите на <a href=\"mailto:fastpapershot.supp@outlook.com\">fastpapershot.supp@outlook.com</a>, письмо прочитают. Укажите версию iOS, задание и то, как был настроен будильник."),
    ],
    "zh-Hans": [
        ("p", "Dawnbreak 是一个在你做完某件事之前不会关掉的闹钟。绝大多数问题都是关于闹钟没响，或者早上六点的任务比想象中难。两件事都写在下面。"),
        ("h", "闹钟没响"),
        ("ul", [
            "闹钟需要权限。应用在首次启动时问一次；如果当时拒绝了，请到「设置」里的 Dawnbreak 打开它。",
            "只保存却没打开的闹钟不会响。起作用的是那一行上的开关。",
            "专注模式和「不供打扰」不会把它静音。闹钟是有意排除在外的。",
            "夜里电池耗尽的手机响不了。单是低电量模式并不影响。",
        ]),
        ("h", "我完不成任务"),
        ("p", "每个任务界面都有出口。点按上方角落的叉并确认，闹钟就会在这个早上停下：重复闹钟会保留到下一次，单次闹钟会被关闭。没有任何设置能去掉它。"),
        ("h", "全部删除"),
        ("p", "删除应用会一并删除闹钟和记录。别处没有副本，也没有需要请我们抹除的东西。"),
        ("h", "其他问题"),
        ("p", "发邮件到 <a href=\"mailto:fastpapershot.supp@outlook.com\">fastpapershot.supp@outlook.com</a>，会有人读。请附上你的 iOS 版本、任务，以及闹钟当时的设置。"),
    ],
}

# The terms of use. Nothing in the app sells anything, so Apple does not require this page; it is
# here because Settings links it and because a person installing an alarm clock is owed a plain
# statement of what it will and will not do.
#
# Written to be read rather than to be impressive: the only clauses here are the ones that are true
# of this app. The safety paragraph is not boilerplate either: an alarm clock that somebody trusts
# with a flight has to say out loud that a flat battery beats any software.
TERMS = {
    "en": [
        ("p", "Dawnbreak is made and published by Aymane Bamhamed. Installing it means accepting what is written here. It is short on purpose: there is no account, no server and no data collection to describe."),
        ("h", "An alarm clock, not a safety device"),
        ("p", "Dawnbreak rings through Focus modes and through Silent because iOS lets an alarm do that. It cannot ring if the phone is switched off, out of battery, or if the permission it asked for at first launch was refused. Do not make it the only thing standing between you and a flight, an exam or a shift. Keep a second alarm for anything that matters that much."),
        ("h", "The missions ask you to move"),
        ("p", "Two missions count steps and squats using the phone's sensors and camera. Do only what your body allows, and stop if something hurts. Every mission screen has a way out, the cross in its top corner, which abandons the mission and stands the alarm down; no setting removes it. If you have a medical condition that makes physical effort unwise, choose one of the missions that asks nothing of your body."),
        ("h", "Free"),
        ("p", "Everything in the app is free: twelve missions, four difficulties, up to ten rounds, as many alarms as your week needs and ninety days of history. There is nothing to buy, no subscription, no advertising and no account."),
        ("h", "Your data"),
        ("p", "Nothing leaves your phone. The alarms, the missions, the history and the reference photo a mission may need are files inside the app's own container. The privacy policy on this site says the same thing in more detail."),
        ("h", "What is not promised"),
        ("p", "The app is provided as it is. It has been tested on current iPhones and current iOS, and it can still be wrong: an iOS release can change how alarms behave, and a sensor can misread a movement. The app is free, so there is no price to refund and no sum paid against which a claim could be measured. Nothing here removes the rights your own consumer law gives you."),
        ("h", "Changes"),
        ("p", "These terms change when the app changes, in the same release. The version on this page is the one that applies."),
        ("h", "Contact"),
        ("p", "Questions about these terms, or about anything the app did: fastpapershot.supp@outlook.com. French law applies, without prejudice to the consumer protections of the country you live in."),
    ],
    "ar": [
        ("p", "Dawnbreak من تطوير أيمن بامحمد ونشره. تثبيت التطبيق يعني قبول ما هو مكتوب هنا. النص قصير بقصد: لا حساب، ولا خادم، ولا جمع بيانات نصفه."),
        ("h", "منبّه، وليس جهاز سلامة"),
        ("p", "يرن Dawnbreak عبر أنماط التركيز وعبر الصامت لأن iOS يسمح للمنبه بذلك. ولا يمكنه الرنين إذا كان الهاتف مطفأً أو نفدت بطاريته أو إذا رُفض الإذن الذي طلبه في أول تشغيل. لا تجعله الشيء الوحيد بينك وبين طائرة أو امتحان أو نوبة عمل. أبقِ منبهاً ثانياً لكل ما يهم بهذا القدر."),
        ("h", "المهام تطلب منك الحركة"),
        ("p", "مهمتان تعتمدان على مستشعرات الهاتف والكاميرا لعدّ الخطوات والقرفصاء. افعل ما يسمح به جسدك فقط، وتوقّف إذا شعرت بألم. لكل شاشة مهمة مخرج، علامة × في زاويتها العليا، يتخلّى عن المهمة ويوقف المنبه؛ ولا يوجد إعداد يزيله. إذا كانت لديك حالة صحية تجعل المجهود البدني غير حكيم، فاختر إحدى المهام التي لا تطلب شيئاً من جسدك."),
        ("h", "بالمجان"),
        ("p", "كل ما في التطبيق مجاني: اثنتا عشرة مهمة، وأربع صعوبات، وحتى عشر جولات، وعدد المنبهات الذي يحتاجه أسبوعك، وتسعون يوماً من السجل. لا شيء للبيع، ولا اشتراك، ولا إعلانات، ولا حساب."),
        ("h", "بياناتك"),
        ("p", "لا شيء يخرج من هاتفك. المنبهات والمهام والسجل وصورة المرجع التي قد تحتاجها مهمة، كلها ملفات داخل حاوية التطبيق. وسياسة الخصوصية على هذا الموقع تقول الأمر نفسه بتفصيل أكبر."),
        ("h", "ما لا يُوعَد به"),
        ("p", "يُقدَّم التطبيق كما هو. جُرّب على أجهزة iPhone وأنظمة iOS الحالية، ويمكن أن يخطئ رغم ذلك: قد يغيّر إصدار من iOS سلوك المنبهات، وقد يخطئ مستشعر في قراءة حركة. التطبيق مجاني، فلا ثمن يُرد ولا مبلغ دُفع تُقاس عليه مطالبة. ولا شيء هنا يسقط الحقوق التي يمنحك قانون حماية المستهلك عندك."),
        ("h", "التغييرات"),
        ("p", "تتغير هذه الشروط عندما يتغير التطبيق، في الإصدار نفسه. والنسخة المعروضة في هذه الصفحة هي السارية."),
        ("h", "التواصل"),
        ("p", "أسئلة عن هذه الشروط أو عن أي شيء فعله التطبيق: fastpapershot.supp@outlook.com. يسري القانون الفرنسي، دون المساس بحقوق حماية المستهلك في بلد إقامتك."),
    ],
    "de": [
        ("p", "Dawnbreak wird von Aymane Bamhamed entwickelt und veröffentlicht. Wer es installiert, akzeptiert, was hier steht. Der Text ist absichtlich kurz: es gibt kein Konto, keinen Server und keine Datenerhebung zu beschreiben."),
        ("h", "Ein Wecker, kein Sicherheitsgerät"),
        ("p", "Dawnbreak klingelt durch Fokus und durch den Lautlos-Schalter, weil iOS das einem Alarm erlaubt. Es kann nicht klingeln, wenn das iPhone aus ist, der Akku leer ist oder die Berechtigung beim ersten Start abgelehnt wurde. Mach es nicht zum einzigen, was zwischen dir und einem Flug, einer Prüfung oder einer Schicht steht. Halte für alles, was so wichtig ist, einen zweiten Wecker."),
        ("h", "Die Missionen verlangen Bewegung"),
        ("p", "Zwei Missionen zählen Schritte und Kniebeugen über Sensoren und Kamera. Tu nur, was dein Körper zulässt, und höre auf, wenn etwas schmerzt. Jeder Missionsbildschirm hat einen Ausweg, das Kreuz oben in der Ecke, der die Mission abbricht und den Alarm abstellt; keine Einstellung entfernt ihn. Wenn eine Erkrankung körperliche Anstrengung unklug macht, nimm eine der Missionen, die vom Körper nichts verlangt."),
        ("h", "Gratis"),
        ("p", "Alles in der App ist gratis: zwölf Missionen, vier Schwierigkeiten, bis zu zehn Runden, so viele Alarme wie deine Woche braucht und neunzig Tage Verlauf. Es gibt nichts zu kaufen, kein Abo, keine Werbung und kein Konto."),
        ("h", "Deine Daten"),
        ("p", "Nichts verlässt dein iPhone. Alarme, Missionen, Verlauf und das Referenzfoto, das eine Mission braucht, sind Dateien im eigenen Container der App. Die Datenschutzseite auf dieser Website sagt dasselbe ausführlicher."),
        ("h", "Was nicht versprochen wird"),
        ("p", "Die App wird so bereitgestellt, wie sie ist. Sie wurde auf aktuellen iPhones und aktuellem iOS getestet und kann sich trotzdem irren: ein iOS-Update kann das Verhalten von Alarmen ändern, und ein Sensor kann eine Bewegung falsch lesen. Die App ist gratis, es gibt also keinen Preis zurückzuzahlen und keinen bezahlten Betrag, an dem sich ein Anspruch messen ließe. Nichts hiervon nimmt dir Rechte aus deinem Verbraucherrecht."),
        ("h", "Änderungen"),
        ("p", "Diese Bedingungen ändern sich mit der App, in derselben Version. Es gilt die Fassung, die auf dieser Seite steht."),
        ("h", "Kontakt"),
        ("p", "Fragen zu diesen Bedingungen oder zu irgendetwas, das die App getan hat: fastpapershot.supp@outlook.com. Es gilt französisches Recht, unbeschadet des Verbraucherschutzes deines Wohnsitzlandes."),
    ],
    "es": [
        ("p", "Dawnbreak lo hace y lo publica Aymane Bamhamed. Instalarlo significa aceptar lo que está escrito aquí. Es corto a propósito: no hay cuenta, ni servidor, ni recogida de datos que describir."),
        ("h", "Un despertador, no un dispositivo de seguridad"),
        ("p", "Dawnbreak suena a través de los modos de concentración y del silencio porque iOS lo permite a una alarma. No puede sonar si el teléfono está apagado, sin batería, o si se denegó el permiso que pidió al primer arranque. No lo conviertas en lo único que hay entre ti y un vuelo, un examen o un turno. Deja un segundo despertador para todo lo que importe tanto."),
        ("h", "Las misiones te piden moverte"),
        ("p", "Dos misiones cuentan pasos y sentadillas con los sensores y la cámara. Haz solo lo que tu cuerpo permita y para si algo duele. Cada pantalla de misión tiene una salida, la cruz de su esquina superior, que abandona la misión y desarma la alarma; ningún ajuste la quita. Si tienes una condición médica que hace imprudente el esfuerzo físico, elige una de las misiones que no pide nada al cuerpo."),
        ("h", "Gratis"),
        ("p", "Todo en la app es gratis: doce misiones, cuatro dificultades, hasta diez rondas, tantas alarmas como necesite tu semana y noventa días de historial. No hay nada que comprar, ni suscripción, ni anuncios, ni cuenta."),
        ("h", "Tus datos"),
        ("p", "Nada sale de tu teléfono. Las alarmas, las misiones, el historial y la foto de referencia que una misión pueda necesitar son archivos dentro del contenedor de la app. La política de privacidad de este sitio lo dice con más detalle."),
        ("h", "Lo que no se promete"),
        ("p", "La app se ofrece tal cual. Se ha probado en iPhones e iOS actuales y aun así puede equivocarse: una versión de iOS puede cambiar cómo se comportan las alarmas, y un sensor puede leer mal un movimiento. La app es gratis, así que no hay precio que devolver ni importe pagado con el que medir una reclamación. Nada de esto te quita los derechos que te da tu ley de consumo."),
        ("h", "Cambios"),
        ("p", "Estos términos cambian cuando cambia la app, en la misma versión. La versión que aparece en esta página es la que se aplica."),
        ("h", "Contacto"),
        ("p", "Dudas sobre estos términos o sobre cualquier cosa que haya hecho la app: fastpapershot.supp@outlook.com. Se aplica la ley francesa, sin perjuicio de las protecciones al consumidor del país donde vives."),
    ],
    "fr": [
        ("p", "Dawnbreak est développé et publié par Aymane Bamhamed. L'installer vaut acceptation de ce qui est écrit ici. Le texte est court exprès : il n'y a ni compte, ni serveur, ni collecte de données à décrire."),
        ("h", "Un réveil, pas un dispositif de sécurité"),
        ("p", "Dawnbreak sonne à travers les modes de concentration et à travers le mode silencieux, parce qu'iOS l'autorise pour une alarme. Il ne peut pas sonner si le téléphone est éteint, à plat, ou si l'autorisation demandée au premier lancement a été refusée. N'en faites pas la seule chose entre vous et un avion, un examen ou une prise de poste. Gardez un second réveil pour tout ce qui compte à ce point."),
        ("h", "Les missions demandent de bouger"),
        ("p", "Deux missions comptent des pas et des squats avec les capteurs et la caméra. Ne faites que ce que votre corps permet, et arrêtez si quelque chose fait mal. Chaque écran de mission a une sortie, la croix dans son coin supérieur, qui abandonne la mission et désarme l'alarme ; aucun réglage ne la retire. Si une condition médicale rend l'effort physique déconseillé, choisissez une des missions qui ne demandent rien au corps."),
        ("h", "Gratuit"),
        ("p", "Tout dans l'app est gratuit : douze missions, quatre difficultés, jusqu'à dix manches, autant d'alarmes que votre semaine en demande et quatre-vingt-dix jours d'historique. Il n'y a rien à acheter, aucun abonnement, aucune publicité et aucun compte."),
        ("h", "Vos données"),
        ("p", "Rien ne quitte votre téléphone. Les alarmes, les missions, l'historique et la photo de référence dont une mission peut avoir besoin sont des fichiers dans le conteneur de l'app. La politique de confidentialité de ce site le dit plus en détail."),
        ("h", "Ce qui n'est pas promis"),
        ("p", "L'app est fournie telle quelle. Elle est testée sur des iPhone et des iOS actuels, et elle peut quand même se tromper : une version d'iOS peut changer le comportement des alarmes, et un capteur peut mal lire un mouvement. L'app est gratuite : il n'y a aucun prix à rembourser et aucune somme payée sur laquelle mesurer une réclamation. Rien ici ne vous retire les droits que votre droit de la consommation vous donne."),
        ("h", "Modifications"),
        ("p", "Ces conditions changent quand l'app change, dans la même version. Celle qui figure sur cette page est celle qui s'applique."),
        ("h", "Contact"),
        ("p", "Une question sur ces conditions, ou sur quelque chose que l'app a fait : fastpapershot.supp@outlook.com. Le droit français s'applique, sans préjudice des protections du consommateur du pays où vous vivez."),
    ],
    "hi": [
        ("p", "Dawnbreak को अयमान बामहामेद बनाते और प्रकाशित करते हैं। इसे इंस्टॉल करना यहाँ लिखी बातों को स्वीकारना है। यह जान-बूझकर छोटा है: कोई खाता, कोई सर्वर, और कोई डेटा संग्रह नहीं है जिसका वर्णन करना पड़े।"),
        ("h", "एक अलार्म, कोई सुरक्षा उपकरण नहीं"),
        ("p", "Dawnbreak फ़ोकस मोड और साइलेंट के आर-पार बजता है, क्योंकि iOS एक अलार्म को इसकी अनुमति देता है। यह नहीं बज सकता अगर फ़ोन बंद है, बैटरी ख़त्म है, या पहली बार माँगी गई अनुमति मना कर दी गई थी। इसे अपनी उड़ान, परीक्षा या शिफ़्ट के बीच खड़ी एकमात्र चीज़ न बनाएँ। इतनी अहम चीज़ों के लिए दूसरा अलार्म रखें।"),
        ("h", "मिशन आपसे हिलने-डुलने को कहते हैं"),
        ("p", "दो मिशन फ़ोन के सेंसर और कैमरे से कदम और स्क्वैट गिनते हैं। वही करें जो आपका शरीर सहे, और दर्द होने पर रुक जाएँ। हर मिशन स्क्रीन पर बाहर निकलने का रास्ता है, ऊपरी कोने का क्रॉस, जो मिशन छोड़ देता है और अलार्म बंद कर देता है; कोई सेटिंग इसे हटाती नहीं। अगर कोई चिकित्सीय स्थिति शारीरिक श्रम को असुरक्षित बनाती है, तो उन मिशनों में से चुनें जो शरीर से कुछ नहीं माँगते।"),
        ("h", "मुफ़्त"),
        ("p", "ऐप में सब कुछ मुफ़्त है: बारह मिशन, चार कठिनाइयाँ, दस राउंड तक, जितने अलार्म आपके हफ़्ते को चाहिए उतने, और नब्बे दिन का इतिहास। ख़रीदने के लिए कुछ नहीं है, कोई सदस्यता नहीं, कोई विज्ञापन नहीं, कोई खाता नहीं।"),
        ("h", "आपका डेटा"),
        ("p", "कुछ भी आपके फ़ोन से बाहर नहीं जाता। अलार्म, मिशन, इतिहास और किसी मिशन को चाहने वाली संदर्भ तस्वीर, सब ऐप के अपने कंटेनर में फ़ाइलें हैं। इस साइट की गोपनीयता नीति यही बात और विस्तार से कहती है।"),
        ("h", "जो वादा नहीं है"),
        ("p", "ऐप जैसा है वैसा दिया जाता है। इसे वर्तमान iPhone और वर्तमान iOS पर परखा गया है, और फिर भी यह ग़लत हो सकता है: iOS का कोई अपडेट अलार्म के व्यवहार को बदल सकता है, और सेंसर किसी हरकत को ग़लत पढ़ सकता है। ऐप मुफ़्त है, इसलिए लौटाने के लिए कोई क़ीमत नहीं है और कोई चुकाई गई राशि नहीं जिस पर दावा नापा जाए। यहाँ कुछ भी आपके उपभोक्ता क़ानून से मिले अधिकार नहीं छीनता।"),
        ("h", "बदलाव"),
        ("p", "ये शर्तें ऐप के बदलने पर उसी रिलीज़ में बदलती हैं। इस पृष्ठ पर मौजूद संस्करण ही लागू है।"),
        ("h", "संपर्क"),
        ("p", "इन शर्तों, या ऐप ने जो किया उसके बारे में सवाल: fastpapershot.supp@outlook.com. फ़्रांसीसी क़ानून लागू होता है, आपके निवास देश की उपभोक्ता सुरक्षा पर प्रभाव डाले बिना।"),
    ],
    "it": [
        ("p", "Dawnbreak è realizzato e pubblicato da Aymane Bamhamed. Installarlo significa accettare quanto scritto qui. È breve di proposito: non c'è un account, non c'è un server e non c'è raccolta di dati da descrivere."),
        ("h", "Una sveglia, non un dispositivo di sicurezza"),
        ("p", "Dawnbreak suona attraverso le modalità di concentrazione e attraverso il silenzioso, perché iOS lo consente a una sveglia. Non può suonare se il telefono è spento, senza batteria, o se il permesso chiesto al primo avvio è stato negato. Non farne l'unica cosa fra te e un volo, un esame o un turno. Tieni una seconda sveglia per tutto ciò che conta così tanto."),
        ("h", "Le missioni chiedono di muoversi"),
        ("p", "Due missioni contano passi e squat usando i sensori e la fotocamera. Fai solo quello che il tuo corpo permette, e fermati se qualcosa fa male. Ogni schermata di missione ha un'uscita, la croce nell'angolo in alto, che abbandona la missione e disarma la sveglia; nessuna impostazione la toglie. Se una condizione medica rende imprudente lo sforzo fisico, scegli una delle missioni che non chiedono nulla al corpo."),
        ("h", "Gratis"),
        ("p", "Tutto nell'app è gratis: dodici missioni, quattro difficoltà, fino a dieci turni, tutte le sveglie che la tua settimana richiede e novanta giorni di cronologia. Non c'è nulla da comprare, nessun abbonamento, nessuna pubblicità e nessun account."),
        ("h", "I tuoi dati"),
        ("p", "Niente lascia il telefono. Sveglie, missioni, cronologia e la foto di riferimento che una missione può richiedere sono file nel contenitore dell'app. L'informativa privacy di questo sito lo dice più in dettaglio."),
        ("h", "Ciò che non viene promesso"),
        ("p", "L'app è fornita così com'è. È stata provata su iPhone e iOS attuali e può comunque sbagliare: una versione di iOS può cambiare il comportamento delle sveglie, e un sensore può leggere male un movimento. L'app è gratis, quindi non c'è un prezzo da rimborsare né una somma pagata su cui misurare una richiesta. Niente di questo ti toglie i diritti che ti dà la tua legge sui consumatori."),
        ("h", "Modifiche"),
        ("p", "Questi termini cambiano quando cambia l'app, nella stessa versione. Vale quella che appare in questa pagina."),
        ("h", "Contatti"),
        ("p", "Domande su questi termini o su qualsiasi cosa abbia fatto l'app: fastpapershot.supp@outlook.com. Si applica la legge francese, senza pregiudizio delle tutele del consumatore del paese in cui vivi."),
    ],
    "ja": [
        ("p", "Dawnbreak は Aymane Bamhamed が開発・公開しています。インストールは、ここに書かれている内容への同意を意味します。短いのは意図的です。アカウントもサーバーもデータ収集もないので、書くことがありません。"),
        ("h", "目覚まし時計であり、安全装置ではありません"),
        ("p", "Dawnbreak は集中モードや消音でも鳴ります。iOS がアラームにそれを許しているからです。ただし端末の電源が切れているとき、バッテリーが尽きたとき、初回起動時の許可を拒否したときは鳴りません。飛行機、試験、勤務のあいだに立つ唯一の手段にはしないでください。それほど大事なものには、別のアラームも用意してください。"),
        ("h", "ミッションは体を動かします"),
        ("p", "2つのミッションはセンサーとカメラで歩数とスクワットを数えます。体が許す範囲だけにして、痛みが出たらやめてください。どのミッション画面にも上隅の×という出口があり、ミッションを放棄してアラームを解除します。これを消す設定はありません。運動が望ましくない健康状態であれば、体に何も求めないミッションを選んでください。"),
        ("h", "無料です"),
        ("p", "アプリのすべてが無料です。12のミッション、4段階の難易度、最大10ラウンド、一週間に必要なだけのアラーム、90日ぶんの履歴。購入するものはなく、サブスクリプションも広告もアカウントもありません。"),
        ("h", "あなたのデータ"),
        ("p", "端末から出るものはありません。アラーム、ミッション、履歴、そしてミッションが必要とする参照写真は、すべてアプリ自身のコンテナ内のファイルです。このサイトのプライバシーポリシーが、より詳しく同じことを述べています。"),
        ("h", "約束しないこと"),
        ("p", "アプリは現状のまま提供されます。現行の iPhone と現行の iOS で試験していますが、それでも誤ることがあります。iOS の更新でアラームの挙動が変わることもあり、センサーが動きを読み違えることもあります。アプリは無料なので、返金する代金もなく、請求の基準になる支払いもありません。ここに書かれたどれも、あなたの消費者法上の権利を奪いません。"),
        ("h", "変更"),
        ("p", "この規約はアプリが変わるときに、同じリリースで変わります。適用されるのはこのページに載っている版です。"),
        ("h", "連絡先"),
        ("p", "この規約、またはアプリの挙動についてのご質問は fastpapershot.supp@outlook.com へ。フランス法が適用されますが、お住まいの国の消費者保護を損なうものではありません。"),
    ],
    "ko": [
        ("p", "Dawnbreak은 Aymane Bamhamed이 만들고 배포합니다. 설치하는 것은 여기에 적힌 내용에 동의하는 것입니다. 일부러 짧습니다. 계정도 서버도 데이터 수집도 없어서 설명할 것이 없습니다."),
        ("h", "알람 시계이고, 안전 장치가 아닙니다"),
        ("p", "Dawnbreak은 집중 모드와 무음을 뚫고 울립니다. iOS가 알람에 그것을 허용하기 때문입니다. 다만 기기가 꺼져 있거나 배터리가 없거나 첫 실행에서 요청한 권한을 거부했다면 울릴 수 없습니다. 비행기, 시험, 근무와 당신 사이에 놓인 유일한 수단으로 삼지 마세요. 그만큼 중요한 일에는 두 번째 알람을 두세요."),
        ("h", "미션은 몸을 움직이게 합니다"),
        ("p", "두 미션은 센서와 카메라로 걸음과 스쿼트를 셉니다. 몸이 허락하는 범위만 하고, 아프면 멈추세요. 모든 미션 화면에는 위쪽 모서리의 ×라는 출구가 있어 미션을 포기하고 알람을 해제합니다. 이를 없애는 설정은 없습니다. 신체 활동이 권장되지 않는 건강 상태라면 몸에 아무것도 요구하지 않는 미션을 고르세요."),
        ("h", "무료"),
        ("p", "앱의 모든 것이 무료입니다. 열두 가지 미션, 네 단계 난이도, 최대 10라운드, 한 주에 필요한 만큼의 알람, 90일간의 기록. 살 것이 없고, 구독도 광고도 계정도 없습니다."),
        ("h", "당신의 데이터"),
        ("p", "기기를 떠나는 것은 없습니다. 알람, 미션, 기록, 그리고 미션이 필요로 하는 참조 사진은 모두 앱 자체 컨테이너 안의 파일입니다. 이 사이트의 개인정보 처리방침이 같은 내용을 더 자세히 설명합니다."),
        ("h", "약속하지 않는 것"),
        ("p", "앱은 있는 그대로 제공됩니다. 현행 iPhone과 현행 iOS에서 시험했지만 그래도 틀릴 수 있습니다. iOS 업데이트가 알람 동작을 바꿀 수 있고, 센서가 움직임을 잘못 읽을 수 있습니다. 앱은 무료이므로 환불할 금액도 없고, 청구의 기준이 될 지불액도 없습니다. 여기의 어떤 내용도 당신의 소비자법상 권리를 없애지 않습니다."),
        ("h", "변경"),
        ("p", "이 약관은 앱이 바뀔 때 같은 릴리스에서 바뀝니다. 적용되는 것은 이 페이지에 실린 판본입니다."),
        ("h", "문의"),
        ("p", "이 약관 또는 앱이 한 일에 대한 질문은 fastpapershot.supp@outlook.com 으로. 프랑스법이 적용되며, 거주 국가의 소비자 보호를 침해하지 않습니다."),
    ],
    "pt-BR": [
        ("p", "Dawnbreak é feito e publicado por Aymane Bamhamed. Instalar significa aceitar o que está escrito aqui. É curto de propósito: não há conta, não há servidor e não há coleta de dados para descrever."),
        ("h", "Um despertador, não um equipamento de segurança"),
        ("p", "Dawnbreak toca através dos modos de concentração e do silencioso, porque o iOS permite isso a um alarme. Ele não pode tocar se o telefone estiver desligado, sem bateria, ou se a permissão pedida no primeiro uso foi negada. Não faça dele a única coisa entre você e um voo, uma prova ou um turno. Mantenha um segundo despertador para tudo que importa tanto."),
        ("h", "As missões pedem que você se mova"),
        ("p", "Duas missões contam passos e agachamentos usando os sensores e a câmera. Faça só o que seu corpo permitir e pare se algo doer. Toda tela de missão tem uma saída, a cruz no canto de cima, que abandona a missão e desarma o alarme; nenhum ajuste a remove. Se uma condição médica torna o esforço físico imprudente, escolha uma das missões que não pede nada do corpo."),
        ("h", "Grátis"),
        ("p", "Tudo no app é grátis: doze missões, quatro dificuldades, até dez rodadas, quantos alarmes a sua semana precisar e noventa dias de histórico. Não há nada para comprar, nenhuma assinatura, nenhum anúncio e nenhuma conta."),
        ("h", "Seus dados"),
        ("p", "Nada sai do seu telefone. Os alarmes, as missões, o histórico e a foto de referência que uma missão possa precisar são arquivos dentro do contêiner do app. A política de privacidade deste site diz o mesmo com mais detalhe."),
        ("h", "O que não é prometido"),
        ("p", "O app é fornecido como está. Foi testado em iPhones e iOS atuais e ainda assim pode errar: uma versão do iOS pode mudar o comportamento dos alarmes, e um sensor pode ler um movimento errado. O app é grátis, então não há preço a devolver nem valor pago sobre o qual medir uma reclamação. Nada aqui retira os direitos que sua lei do consumidor lhe dá."),
        ("h", "Mudanças"),
        ("p", "Estes termos mudam quando o app muda, na mesma versão. Vale a versão que aparece nesta página."),
        ("h", "Contato"),
        ("p", "Dúvidas sobre estes termos, ou sobre algo que o app fez: fastpapershot.supp@outlook.com. Aplica-se a lei francesa, sem prejuízo das proteções ao consumidor do país onde você vive."),
    ],
    "ru": [
        ("p", "Dawnbreak делает и публикует Aymane Bamhamed. Установка означает согласие с тем, что здесь написано. Текст короткий намеренно: нет аккаунта, нет сервера и нет сбора данных, которые надо было бы описывать."),
        ("h", "Будильник, а не средство безопасности"),
        ("p", "Dawnbreak звонит через режимы фокусирования и через беззвучный, потому что iOS разрешает это будильнику. Он не может позвонить, если телефон выключен, разряжен или если разрешение, запрошенное при первом запуске, было отклонено. Не делайте его единственным, что стоит между вами и самолётом, экзаменом или сменой. Для всего настолько важного держите второй будильник."),
        ("h", "Задания требуют движения"),
        ("p", "Два задания считают шаги и приседания с помощью датчиков и камеры. Делайте только то, что позволяет тело, и остановитесь, если что-то болит. На каждом экране задания есть выход, крестик в верхнем углу: он бросает задание и снимает будильник. Никакая настройка его не убирает. Если состояние здоровья делает физическую нагрузку неразумной, выберите одно из заданий, которое ничего не требует от тела."),
        ("h", "Бесплатно"),
        ("p", "В приложении бесплатно всё: двенадцать заданий, четыре уровня сложности, до десяти раундов, столько будильников, сколько нужно вашей неделе, и девяносто дней истории. Покупать нечего, подписки нет, рекламы нет, аккаунта нет."),
        ("h", "Ваши данные"),
        ("p", "Ничего не покидает телефон. Будильники, задания, история и эталонное фото, которое может понадобиться заданию, это файлы внутри собственного контейнера приложения. Политика конфиденциальности на этом сайте говорит то же подробнее."),
        ("h", "Что не обещано"),
        ("p", "Приложение предоставляется как есть. Оно проверено на актуальных iPhone и актуальной iOS и всё равно может ошибиться: обновление iOS может изменить поведение будильников, а датчик может неверно прочитать движение. Приложение бесплатное, поэтому нет цены, которую можно вернуть, и нет уплаченной суммы, по которой измерять требование. Ничто здесь не отменяет прав, которые даёт вам ваше потребительское право."),
        ("h", "Изменения"),
        ("p", "Эти условия меняются вместе с приложением, в том же выпуске. Действует та редакция, которая опубликована на этой странице."),
        ("h", "Контакт"),
        ("p", "Вопросы об этих условиях или о чём-то, что сделало приложение: fastpapershot.supp@outlook.com. Применяется французское право, без ущерба для потребительской защиты страны, где вы живёте."),
    ],
    "zh-Hans": [
        ("p", "Dawnbreak 由 Aymane Bamhamed 开发并发布。安装即表示接受这里写下的内容。它故意很短：没有账号，没有服务器，也没有数据收集需要描述。"),
        ("h", "这是闹钟，不是安全设备"),
        ("p", "Dawnbreak 能穿透专注模式和静音，因为 iOS 允许闹钟这样做。但如果手机关机、电量耗尽，或者首次启动时拒绝了它请求的权限，它就无法响。不要让它成为你与航班、考试或班次之间唯一的依靠。这类事情请再留一个闹钟。"),
        ("h", "任务要求你动起来"),
        ("p", "两个任务用传感器和相机来数步数与深蹲。只做身体允许的部分，感到疼痛就停下。每个任务界面都有出口，就是上方角落的叉，它会放弃任务并撤下闹钟；没有任何设置能去掉它。如果健康状况让体力活动不合适，请选择那些对身体没有要求的任务。"),
        ("h", "免费"),
        ("p", "应用里的一切都是免费的：十二种任务、四档难度、最多十轮、你这一周需要的任意数量的闹钟，以及九十天的历史记录。没有任何东西可买，没有订阅，没有广告，也没有账号。"),
        ("h", "你的数据"),
        ("p", "没有任何东西离开你的手机。闹钟、任务、历史记录，以及某个任务可能需要的参照照片，都是应用自有容器内的文件。本站的隐私政策以更详细的方式说了同一件事。"),
        ("h", "不作出的承诺"),
        ("p", "应用按现状提供。它在当前的 iPhone 和当前的 iOS 上经过测试，但仍可能出错：iOS 的更新可能改变闹钟行为，传感器也可能误读动作。本应用免费，因此没有可退还的价款，也没有可用来衡量索赔的已付金额。这里的任何内容都不会剥夺你所在地消费者法律给你的权利。"),
        ("h", "变更"),
        ("p", "这些条款随应用变更，在同一个版本中更新。适用的是本页面上的版本。"),
        ("h", "联系"),
        ("p", "关于这些条款，或应用做过的任何事：fastpapershot.supp@outlook.com。适用法国法律，且不影响你居住国的消费者保护。"),
    ],
}

PAGES = {
    "index": INDEX,
    "privacy": PRIVACY,
    "terms": TERMS,
    "support": SUPPORT,
}
