"""The three pages App Store Connect needs a URL for, in all twelve languages.

Apple requires a privacy policy URL and a support URL before a build can be submitted, and it
requires them per locale. A Japanese listing that links an English-only support page is accepted,
and it is also the moment a Japanese reader learns how much of this app was actually made for them.
So the pages ship in the same twelve languages as the app.

One page per subject rather than one per subject per language: `make_pages.py` renders all twelve
translations into a single file with a language picker, so `privacy.html` is one URL that answers in
whichever language the reader's browser asks for. Twelve URLs would mean twelve values in
`store.py`, twelve values inside twelve descriptions, and a broken link the day one is renamed.

Blocks rather than HTML strings. A block is a tuple:

    ("h",  "A heading")
    ("p",  "A paragraph. <a href=…> is allowed, nothing else is.")
    ("ul", ["An item", "Another item"])

Written this way so `make_pages.py` can escape the text, check that every language has the same
shape as English, and change the markup for all twelve pages at once.
"""

# What the picker shows. Endonyms, because a reader looking for their own language is looking for
# the word they call it by, not for the English name of it.
LANGUAGE_NAME = {
    "en": "English",
    "ar": "العربية",
    "de": "Deutsch",
    "es": "Español",
    "fr": "Français",
    "hi": "हिन्दी",
    "it": "Italiano",
    "ja": "日本語",
    "ko": "한국어",
    "pt-BR": "Português (Brasil)",
    "ru": "Русский",
    "zh-Hans": "简体中文",
}

# The `<title>` and the `<h1>`, per page per language.
TITLE = {
    "index": {
        "en": "Dawnbreak",
        "ar": "Dawnbreak",
        "de": "Dawnbreak",
        "es": "Dawnbreak",
        "fr": "Dawnbreak",
        "hi": "Dawnbreak",
        "it": "Dawnbreak",
        "ja": "Dawnbreak",
        "ko": "Dawnbreak",
        "pt-BR": "Dawnbreak",
        "ru": "Dawnbreak",
        "zh-Hans": "Dawnbreak",
    },
    "privacy": {
        "en": "Privacy",
        "ar": "الخصوصية",
        "de": "Datenschutz",
        "es": "Privacidad",
        "fr": "Confidentialité",
        "hi": "गोपनीयता",
        "it": "Privacy",
        "ja": "プライバシー",
        "ko": "개인정보",
        "pt-BR": "Privacidade",
        "ru": "Конфиденциальность",
        "zh-Hans": "隐私",
    },
    "support": {
        "en": "Support",
        "ar": "الدعم",
        "de": "Hilfe",
        "es": "Soporte",
        "fr": "Assistance",
        "hi": "सहायता",
        "it": "Assistenza",
        "ja": "サポート",
        "ko": "지원",
        "pt-BR": "Suporte",
        "ru": "Поддержка",
        "zh-Hans": "支持",
    },
}

# The one-line promise under the name on the marketing page.
TAGLINE = {
    "en": "The alarm you cannot switch off in your sleep.",
    "ar": "منبّه لا يمكنك إسكاته وأنت نائم.",
    "de": "Der Wecker, den du im Schlaf nicht ausschalten kannst.",
    "es": "El despertador que no puedes apagar dormido.",
    "fr": "Le réveil qu'on ne peut pas éteindre en dormant.",
    "hi": "वह अलार्म जिसे आप नींद में बंद नहीं कर सकते।",
    "it": "La sveglia che non puoi spegnere nel sonno.",
    "ja": "寝たまま止められない目覚まし。",
    "ko": "잠결에는 끌 수 없는 알람.",
    "pt-BR": "O despertador que você não desliga dormindo.",
    "ru": "Будильник, который не выключить во сне.",
    "zh-Hans": "睡着的时候关不掉的闹钟。",
}

INDEX = {
    "en": [
        ("p", "You do not oversleep because your alarm is too quiet. You oversleep because stopping it takes one thumb, half a second, and no thought at all."),
        ("p", "Dawnbreak takes the thumb out of it. To silence the alarm you have to do something a sleeping person cannot: walk to the kitchen and photograph the kettle, do ten squats in front of the camera, solve arithmetic you would find easy at noon, scan the barcode on a box in another room."),
        ("h", "Twelve missions"),
        ("p", "Arithmetic, a tile pattern to reproduce, a colour sequence, a sentence to type exactly, a shake, a walk of a set number of steps, squats counted by the camera, an object to go and photograph, a barcode to scan, a drawing recognised on the device, a lap of a small game, and a round of guided breathing. Four difficulties, and as many missions in a row as you dare set."),
        ("h", "It does not let go"),
        ("p", "Stop the alarm without finishing the mission and it comes back a few minutes later under a title that says so. Up to ten rounds. An emergency exit is there from the first launch, because an alarm that can trap someone is a bug, not a feature."),
        ("h", "Nothing leaves your phone"),
        ("p", "No account, no server, no analytics, no third-party code of any kind. The camera frames the squat mission counts are analysed in memory and thrown away. Your alarms and your history are files on your device and nowhere else."),
        ("h", "Twelve languages"),
        ("p", "English, Arabic, German, Spanish, French, Hindi, Italian, Japanese, Korean, Portuguese, Russian and Simplified Chinese, including the right-to-left layout Arabic needs rather than a mirrored afterthought."),
    ],
    "ar": [
        ("p", "أنت لا تتأخر في النوم لأن المنبّه هادئ جدًا، بل لأن إسكاته لا يحتاج أكثر من إبهام ونصف ثانية وبلا أي تفكير."),
        ("p", "‏Dawnbreak يزيل الإبهام من المعادلة. لإسكات المنبّه عليك أن تفعل ما لا يقدر عليه نائم: أن تمشي إلى المطبخ وتصوّر الغلاية، أن تؤدي عشر حركات قرفصاء أمام الكاميرا، أن تحلّ مسألة حسابية تراها سهلة في منتصف النهار، أن تقرأ باركود علبة في غرفة أخرى."),
        ("h", "اثنتا عشرة مهمة"),
        ("p", "حساب، نمط مربّعات تعيد رسمه، تسلسل ألوان، جملة تكتبها حرفًا بحرف، رجّة للهاتف، عدد محدد من الخطوات، قرفصاء تعدّها الكاميرا، شيء تذهب وتصوّره، باركود تقرأه، رسمة يتعرّف عليها الجهاز، لفة في لعبة صغيرة، ودورة تنفّس موجّه. أربع درجات صعوبة، وعدد المهام المتتالية متروك لجرأتك."),
        ("h", "لا يتركك"),
        ("p", "أوقف المنبّه دون إنهاء المهمة وسيعود بعد دقائق تحت عنوان يقول ذلك بصراحة. حتى عشر جولات. ومخرج الطوارئ موجود من أول تشغيل، لأن منبّهًا قادرًا على حجز صاحبه هو خلل لا ميزة."),
        ("h", "لا شيء يخرج من هاتفك"),
        ("p", "لا حساب، لا خادم، لا تحليلات، ولا سطر واحد من كود طرف ثالث. صور الكاميرا التي تعدّ القرفصاء تُحلَّل في الذاكرة ثم تُرمى. منبّهاتك وسجلك ملفات على جهازك ولا مكان غيره."),
        ("h", "اثنتا عشرة لغة"),
        ("p", "الإنجليزية والعربية والألمانية والإسبانية والفرنسية والهندية والإيطالية واليابانية والكورية والبرتغالية والروسية والصينية المبسطة، مع تخطيط من اليمين إلى اليسار مصمّم للعربية لا مجرد انعكاس متأخر."),
    ],
    "de": [
        ("p", "Du verschläfst nicht, weil der Wecker zu leise ist. Du verschläfst, weil ihn auszuschalten einen Daumen, eine halbe Sekunde und keinerlei Nachdenken kostet."),
        ("p", "Dawnbreak nimmt den Daumen aus der Rechnung. Um den Wecker still zu bekommen, musst du etwas tun, das ein Schlafender nicht kann: in die Küche gehen und den Wasserkocher fotografieren, zehn Kniebeugen vor der Kamera machen, eine Rechnung lösen, die mittags leicht wäre, den Barcode einer Packung im Nebenzimmer scannen."),
        ("h", "Zwölf Missionen"),
        ("p", "Rechnen, ein Muster nachlegen, eine Farbfolge wiederholen, einen Satz genau abtippen, das Telefon schütteln, eine festgelegte Zahl von Schritten gehen, Kniebeugen von der Kamera zählen lassen, einen Gegenstand fotografieren gehen, einen Barcode scannen, eine Zeichnung, die das Gerät erkennt, eine Runde in einem kleinen Spiel und eine Runde geführtes Atmen. Vier Schwierigkeiten, und so viele Missionen hintereinander, wie du dir zutraust."),
        ("h", "Er lässt nicht los"),
        ("p", "Beende den Wecker ohne die Mission, und er kommt Minuten später zurück, unter einem Titel, der das auch sagt. Bis zu zehn Runden. Ein Notausgang ist ab dem ersten Start da, denn ein Wecker, der jemanden einsperren kann, ist ein Fehler und keine Funktion."),
        ("h", "Nichts verlässt dein Telefon"),
        ("p", "Kein Konto, kein Server, keine Analyse, keine einzige Zeile Fremdcode. Die Kamerabilder, mit denen Kniebeugen gezählt werden, werden im Speicher ausgewertet und weggeworfen. Deine Wecker und deine Historie sind Dateien auf deinem Gerät und sonst nirgends."),
        ("h", "Zwölf Sprachen"),
        ("p", "Englisch, Arabisch, Deutsch, Spanisch, Französisch, Hindi, Italienisch, Japanisch, Koreanisch, Portugiesisch, Russisch und Chinesisch (vereinfacht), mit dem Rechts-nach-links-Layout, das Arabisch braucht, und nicht als nachträglich gespiegelte Notlösung."),
    ],
    "es": [
        ("p", "No te quedas dormido porque la alarma suene poco. Te quedas dormido porque apagarla cuesta un pulgar, medio segundo y ningún pensamiento."),
        ("p", "Dawnbreak quita el pulgar de la ecuación. Para callar la alarma tienes que hacer algo que alguien dormido no puede: ir a la cocina y fotografiar el hervidor, hacer diez sentadillas delante de la cámara, resolver una cuenta que a mediodía te parecería fácil, escanear el código de barras de una caja en otra habitación."),
        ("h", "Doce misiones"),
        ("p", "Cuentas, un patrón de fichas que repetir, una secuencia de colores, una frase que escribir exacta, agitar el teléfono, andar un número fijo de pasos, sentadillas contadas por la cámara, un objeto que ir a fotografiar, un código de barras que escanear, un dibujo que el dispositivo reconoce, una vuelta en un juego pequeño y una ronda de respiración guiada. Cuatro dificultades, y tantas misiones seguidas como te atrevas a poner."),
        ("h", "No te suelta"),
        ("p", "Detén la alarma sin terminar la misión y vuelve unos minutos después, con un título que lo dice. Hasta diez rondas. Hay una salida de emergencia desde el primer arranque, porque una alarma capaz de atrapar a alguien es un fallo, no una función."),
        ("h", "Nada sale de tu teléfono"),
        ("p", "Sin cuenta, sin servidor, sin analítica, sin una sola línea de código ajeno. Los fotogramas con los que se cuentan las sentadillas se analizan en memoria y se descartan. Tus alarmas y tu historial son archivos en tu dispositivo y en ningún otro sitio."),
        ("h", "Doce idiomas"),
        ("p", "Inglés, árabe, alemán, español, francés, hindi, italiano, japonés, coreano, portugués, ruso y chino simplificado, con la disposición de derecha a izquierda que el árabe necesita y no un reflejo puesto al final."),
    ],
    "fr": [
        ("p", "Vous ne dormez pas trop longtemps parce que le réveil est trop discret. Vous dormez trop longtemps parce que l'arrêter demande un pouce, une demi-seconde et aucune réflexion."),
        ("p", "Dawnbreak retire le pouce de l'équation. Pour faire taire le réveil, il faut faire quelque chose qu'un dormeur ne peut pas faire : aller dans la cuisine et photographier la bouilloire, faire dix squats devant la caméra, résoudre un calcul qui serait facile à midi, scanner le code-barres d'une boîte laissée dans une autre pièce."),
        ("h", "Douze missions"),
        ("p", "Du calcul, un motif à reproduire, une séquence de couleurs, une phrase à taper à l'identique, une secousse, un nombre de pas à parcourir, des squats comptés par la caméra, un objet à aller photographier, un code-barres à scanner, un dessin reconnu sur l'appareil, un tour dans un petit jeu, et un cycle de respiration guidée. Quatre difficultés, et autant de missions d'affilée que vous osez en régler."),
        ("h", "Il ne lâche pas"),
        ("p", "Arrêtez le réveil sans finir la mission et il revient quelques minutes plus tard, sous un titre qui le dit. Jusqu'à dix tours. Une sortie de secours existe dès le premier lancement, parce qu'un réveil capable de piéger quelqu'un est un défaut, pas une fonctionnalité."),
        ("h", "Rien ne quitte votre téléphone"),
        ("p", "Pas de compte, pas de serveur, pas de statistiques, pas une ligne de code tiers. Les images qui servent à compter les squats sont analysées en mémoire puis jetées. Vos réveils et votre historique sont des fichiers sur votre appareil, et nulle part ailleurs."),
        ("h", "Douze langues"),
        ("p", "Anglais, arabe, allemand, espagnol, français, hindi, italien, japonais, coréen, portugais, russe et chinois simplifié, avec la mise en page de droite à gauche que l'arabe exige, et non un miroir posé à la fin."),
    ],
    "hi": [
        ("p", "आप देर तक इसलिए नहीं सोते कि अलार्म धीमा है। आप इसलिए सोते हैं कि उसे बंद करने में एक अंगूठा, आधा सेकंड और कोई सोच नहीं लगती।"),
        ("p", "Dawnbreak उस अंगूठे को हटा देता है। अलार्म चुप कराने के लिए आपको वह करना पड़ता है जो सोया हुआ आदमी नहीं कर सकता: रसोई तक जाकर केतली की फ़ोटो लेना, कैमरे के सामने दस स्क्वैट करना, दोपहर में आसान लगने वाला गणित हल करना, दूसरे कमरे में रखे डिब्बे का बारकोड स्कैन करना।"),
        ("h", "बारह मिशन"),
        ("p", "गणित, दोहराने के लिए एक पैटर्न, रंगों का क्रम, हूबहू टाइप करने के लिए एक वाक्य, फ़ोन हिलाना, तय संख्या में क़दम चलना, कैमरे से गिने जाने वाले स्क्वैट, जाकर फ़ोटो लेने के लिए एक चीज़, स्कैन करने के लिए एक बारकोड, डिवाइस पर पहचानी जाने वाली एक ड्रॉइंग, एक छोटे खेल का एक चक्कर, और निर्देशित सांस का एक दौर। चार कठिनाई स्तर, और लगातार जितने मिशन आप रखने की हिम्मत करें।"),
        ("h", "यह पीछा नहीं छोड़ता"),
        ("p", "मिशन पूरा किए बिना अलार्म रोकें और वह कुछ मिनट बाद ऐसे शीर्षक के साथ लौट आता है जो यही कहता है। दस राउंड तक। आपातकालीन रास्ता पहली बार खोलने से ही मौजूद है, क्योंकि किसी को फंसा सकने वाला अलार्म ख़राबी है, सुविधा नहीं।"),
        ("h", "कुछ भी आपके फ़ोन से बाहर नहीं जाता"),
        ("p", "कोई खाता नहीं, कोई सर्वर नहीं, कोई एनालिटिक्स नहीं, किसी और का कोड एक पंक्ति भी नहीं। स्क्वैट गिनने वाले कैमरा फ़्रेम मेमोरी में जांचे जाते हैं और फेंक दिए जाते हैं। आपके अलार्म और आपका इतिहास आपके डिवाइस पर फ़ाइलें हैं, और कहीं नहीं।"),
        ("h", "बारह भाषाएं"),
        ("p", "अंग्रेज़ी, अरबी, जर्मन, स्पेनिश, फ़्रेंच, हिन्दी, इतालवी, जापानी, कोरियाई, पुर्तगाली, रूसी और सरलीकृत चीनी, और अरबी के लिए दाएं से बाएं का वह लेआउट जो उसे चाहिए, बाद में लगाया गया आईना नहीं।"),
    ],
    "it": [
        ("p", "Non dormi troppo perché la sveglia è troppo bassa. Dormi troppo perché spegnerla costa un pollice, mezzo secondo e nessun pensiero."),
        ("p", "Dawnbreak toglie il pollice dall'equazione. Per far tacere la sveglia devi fare qualcosa che chi dorme non può fare: andare in cucina e fotografare il bollitore, fare dieci squat davanti alla fotocamera, risolvere un calcolo che a mezzogiorno ti sembrerebbe facile, scansionare il codice a barre di una scatola in un'altra stanza."),
        ("h", "Dodici missioni"),
        ("p", "Calcoli, uno schema di tessere da rifare, una sequenza di colori, una frase da digitare identica, una scossa, un numero fissato di passi, squat contati dalla fotocamera, un oggetto da andare a fotografare, un codice a barre da scansionare, un disegno riconosciuto sul dispositivo, un giro in un piccolo gioco e un ciclo di respirazione guidata. Quattro difficoltà, e tante missioni di fila quante hai il coraggio di impostare."),
        ("h", "Non ti molla"),
        ("p", "Ferma la sveglia senza finire la missione e torna qualche minuto dopo, con un titolo che lo dice. Fino a dieci giri. Un'uscita di emergenza c'è dal primo avvio, perché una sveglia che può intrappolare qualcuno è un difetto, non una funzione."),
        ("h", "Niente esce dal telefono"),
        ("p", "Nessun account, nessun server, nessuna analitica, nemmeno una riga di codice di terzi. I fotogrammi con cui si contano gli squat vengono analizzati in memoria e buttati. Le tue sveglie e il tuo storico sono file sul tuo dispositivo e in nessun altro posto."),
        ("h", "Dodici lingue"),
        ("p", "Inglese, arabo, tedesco, spagnolo, francese, hindi, italiano, giapponese, coreano, portoghese, russo e cinese semplificato, con l'impaginazione da destra a sinistra che l'arabo richiede e non uno specchio messo alla fine."),
    ],
    "ja": [
        ("p", "寝坊するのは、目覚ましの音が小さいからではありません。止めるのに親指ひとつ、半秒、考える必要がまったくないからです。"),
        ("p", "Dawnbreak はその親指を取り除きます。アラームを黙らせるには、眠っている人にはできないことをしなければなりません。台所まで歩いてケトルを撮る、カメラの前でスクワットを十回、昼間なら簡単な計算を解く、別の部屋にある箱のバーコードを読み取る。"),
        ("h", "ミッションは 12 種類"),
        ("p", "計算、並べ直すタイルの模様、色の並び、一字も違わず打つ文章、端末を振る、決めた歩数を歩く、カメラが数えるスクワット、行って撮ってくる対象物、読み取るバーコード、端末が認識する手描き、小さなゲームの一周、そして誘導つきの呼吸。難易度は四段階、連続させるミッションの数は設定するあなたの度胸次第です。"),
        ("h", "簡単には離してくれません"),
        ("p", "ミッションを終えずに止めれば、数分後にそう書かれたタイトルで戻ってきます。最大十回。緊急脱出は初回起動から用意してあります。人を閉じ込められる目覚ましは機能ではなく不具合だからです。"),
        ("h", "端末から何も出ていきません"),
        ("p", "アカウントなし、サーバーなし、解析なし、他社のコードは一行もありません。スクワットを数えるカメラの映像はメモリ上で解析して捨てます。アラームと記録は端末上のファイルであり、それ以外のどこにもありません。"),
        ("h", "12 の言語"),
        ("p", "英語、アラビア語、ドイツ語、スペイン語、フランス語、ヒンディー語、イタリア語、日本語、韓国語、ポルトガル語、ロシア語、簡体中国語。アラビア語には後付けの鏡像ではなく、必要な右から左のレイアウトを用意しています。"),
    ],
    "ko": [
        ("p", "늦잠을 자는 건 알람이 작아서가 아닙니다. 끄는 데 엄지 하나, 반 초, 그리고 생각이 전혀 필요하지 않아서입니다."),
        ("p", "Dawnbreak는 그 엄지를 빼버립니다. 알람을 멈추려면 잠든 사람은 할 수 없는 일을 해야 합니다. 부엌까지 걸어가 주전자를 찍고, 카메라 앞에서 스쿼트를 열 번 하고, 낮이라면 쉬웠을 계산을 풀고, 다른 방에 둔 상자의 바코드를 스캔하는 일."),
        ("h", "미션 12가지"),
        ("p", "계산, 다시 맞추는 타일 패턴, 색 순서, 한 글자도 틀리지 않게 치는 문장, 흔들기, 정해진 걸음 수 걷기, 카메라가 세는 스쿼트, 가서 찍어와야 하는 물건, 스캔할 바코드, 기기가 알아보는 그림, 작은 게임 한 바퀴, 그리고 호흡 한 세트. 난이도는 네 단계, 연달아 붙일 미션 수는 당신의 배짱에 달렸습니다."),
        ("h", "쉽게 놓아주지 않습니다"),
        ("p", "미션을 끝내지 않고 알람을 멈추면 몇 분 뒤에 그렇게 적힌 제목으로 돌아옵니다. 최대 열 번. 비상 탈출은 첫 실행부터 있습니다. 사람을 가둘 수 있는 알람은 기능이 아니라 결함이니까요."),
        ("h", "휴대폰을 벗어나는 것은 없습니다"),
        ("p", "계정 없음, 서버 없음, 분석 없음, 남의 코드는 한 줄도 없음. 스쿼트를 세는 카메라 영상은 메모리에서 분석하고 버립니다. 알람과 기록은 기기 안의 파일이며 그 밖에는 없습니다."),
        ("h", "12개 언어"),
        ("p", "영어, 아랍어, 독일어, 스페인어, 프랑스어, 힌디어, 이탈리아어, 일본어, 한국어, 포르투갈어, 러시아어, 중국어 간체. 아랍어에는 나중에 붙인 거울이 아니라 필요한 오른쪽에서 왼쪽 배치를 넣었습니다."),
    ],
    "pt-BR": [
        ("p", "Você não dorme demais porque o despertador é baixo. Você dorme demais porque desligá-lo custa um polegar, meio segundo e nenhum pensamento."),
        ("p", "O Dawnbreak tira o polegar da conta. Para calar o despertador você tem que fazer algo que quem está dormindo não consegue: ir até a cozinha e fotografar a chaleira, fazer dez agachamentos na frente da câmera, resolver uma conta que ao meio-dia seria fácil, escanear o código de barras de uma caixa em outro quarto."),
        ("h", "Doze missões"),
        ("p", "Cálculo, um padrão de peças para repetir, uma sequência de cores, uma frase para digitar igual, sacudir o telefone, andar um número fixo de passos, agachamentos contados pela câmera, um objeto para ir fotografar, um código de barras para escanear, um desenho que o aparelho reconhece, uma volta num joguinho e uma rodada de respiração guiada. Quatro dificuldades, e quantas missões em sequência você tiver coragem de configurar."),
        ("h", "Ele não solta"),
        ("p", "Pare o despertador sem terminar a missão e ele volta alguns minutos depois, com um título dizendo exatamente isso. Até dez rodadas. Existe uma saída de emergência desde a primeira abertura, porque um despertador capaz de prender alguém é um defeito, não um recurso."),
        ("h", "Nada sai do seu telefone"),
        ("p", "Sem conta, sem servidor, sem analytics, sem uma linha de código de terceiros. Os quadros da câmera que contam os agachamentos são analisados na memória e descartados. Seus despertadores e seu histórico são arquivos no seu aparelho e em nenhum outro lugar."),
        ("h", "Doze idiomas"),
        ("p", "Inglês, árabe, alemão, espanhol, francês, híndi, italiano, japonês, coreano, português, russo e chinês simplificado, com o layout da direita para a esquerda que o árabe precisa, e não um espelho colado no fim."),
    ],
    "ru": [
        ("p", "Вы просыпаете не потому, что будильник тихий. Вы просыпаете потому, что выключить его стоит одного пальца, половины секунды и никаких размышлений."),
        ("p", "Dawnbreak убирает палец из этого уравнения. Чтобы будильник замолчал, нужно сделать то, чего спящий не может: дойти до кухни и снять чайник, сделать десять приседаний перед камерой, решить арифметику, которая днём кажется простой, отсканировать штрихкод коробки в другой комнате."),
        ("h", "Двенадцать заданий"),
        ("p", "Арифметика, узор из плиток, который надо повторить, последовательность цветов, фраза, которую надо набрать точь-в-точь, встряхивание, заданное число шагов, приседания, которые считает камера, предмет, который надо пойти и снять, штрихкод, рисунок, распознаваемый на устройстве, круг в маленькой игре и подход дыхательного упражнения. Четыре уровня сложности, а заданий подряд — сколько хватит смелости поставить."),
        ("h", "Он не отпускает"),
        ("p", "Остановите будильник, не закончив задание, и через несколько минут он вернётся под заголовком, который об этом и говорит. До десяти кругов. Аварийный выход есть с первого запуска: будильник, способный запереть человека, — это дефект, а не функция."),
        ("h", "Ничего не покидает телефон"),
        ("p", "Ни учётной записи, ни сервера, ни аналитики, ни одной строки чужого кода. Кадры камеры, по которым считаются приседания, разбираются в памяти и выбрасываются. Ваши будильники и ваша история — файлы на устройстве и больше нигде."),
        ("h", "Двенадцать языков"),
        ("p", "Английский, арабский, немецкий, испанский, французский, хинди, итальянский, японский, корейский, португальский, русский и упрощённый китайский, с той раскладкой справа налево, которая нужна арабскому, а не с зеркалом, приделанным напоследок."),
    ],
    "zh-Hans": [
        ("p", "你睡过头，不是因为闹钟太轻。是因为关掉它只需要一根拇指、半秒钟，以及完全不用想。"),
        ("p", "Dawnbreak 把那根拇指拿掉。要让闹钟安静下来，你得做一件睡着的人做不到的事：走到厨房去拍下水壶，在摄像头前做十个深蹲，解一道中午看来很简单的算术，扫描另一个房间里那个盒子上的条码。"),
        ("h", "十二种任务"),
        ("p", "算术、要复原的方块图案、一串颜色顺序、要一字不差打出的句子、摇一摇、走满指定的步数、由摄像头来数的深蹲、要走过去拍下的物件、要扫的条码、由设备识别的手绘、小游戏里的一圈，以及一轮引导呼吸。四种难度，连续几个任务，取决于你敢设几个。"),
        ("h", "它不轻易放手"),
        ("p", "没做完任务就把闹钟停掉，它会在几分钟后带着一个明说这件事的标题回来。最多十轮。紧急退出从第一次启动就在，因为一个能把人困住的闹钟是缺陷，不是功能。"),
        ("h", "没有东西离开你的手机"),
        ("p", "没有账号，没有服务器，没有统计分析，没有一行别人的代码。用来数深蹲的画面在内存里分析完就丢掉。你的闹钟和记录是设备上的文件，别的地方没有。"),
        ("h", "十二种语言"),
        ("p", "英语、阿拉伯语、德语、西班牙语、法语、印地语、意大利语、日语、韩语、葡萄牙语、俄语和简体中文，并为阿拉伯语准备了它需要的从右到左布局，而不是事后加上的一面镜子。"),
    ],
}

PRIVACY = {
    "en": [
        ("p", "Dawnbreak collects nothing. There is no account to create, no server to talk to, and no analytics of any kind. This page is short because there is very little to describe."),
        ("h", "What stays on your phone"),
        ("p", "Your alarms, the missions attached to them, your preferences and your wake-up history are written to files inside the app's own container on your device. They are never uploaded. If you back your device up to iCloud or to a computer, they are part of that backup, which is between you and Apple."),
        ("h", "The camera and the motion sensors"),
        ("p", "Three missions use the camera: photographing an object, scanning a barcode, and counting squats. Frames are analysed on the device, in memory, while the mission is on screen, and are discarded as they are replaced. Nothing is written to your photo library and nothing is transmitted. Two missions read the motion sensors to count steps or detect a shake; those readings are used as they arrive and never stored."),
        ("h", "Purchases"),
        ("p", "Dawnbreak Pro is sold through the App Store. Apple takes the payment and tells the app whether a purchase is active. The app never sees your name, your card, or your Apple Account."),
        ("h", "Children"),
        ("p", "The app collects nothing from anyone, at any age, so there is nothing here to treat differently for a child."),
        ("h", "Changes"),
        ("p", "If any of the above stops being true, this page changes in the same release that makes it untrue."),
    ],
    "ar": [
        ("p", "‏Dawnbreak لا يجمع أي شيء. لا حساب تُنشئه، ولا خادم يتواصل معه، ولا تحليلات من أي نوع. هذه الصفحة قصيرة لأن ما يُوصَف قليل جدًا."),
        ("h", "ما يبقى على هاتفك"),
        ("p", "منبّهاتك، والمهام المرتبطة بها، وإعداداتك، وسجل استيقاظك، تُكتب في ملفات داخل حاوية التطبيق على جهازك. ولا تُرفع أبدًا. وإذا أخذت نسخة احتياطية إلى iCloud أو إلى حاسوب، فهي جزء من تلك النسخة، وذلك أمر بينك وبين Apple."),
        ("h", "الكاميرا وحساسات الحركة"),
        ("p", "ثلاث مهام تستخدم الكاميرا: تصوير شيء، وقراءة باركود، وعدّ القرفصاء. تُحلَّل الصور على الجهاز، في الذاكرة، طوال وجود المهمة على الشاشة، ثم تُرمى مع وصول ما يليها. ولا يُكتب شيء في مكتبة صورك ولا يُرسل شيء. ومهمتان تقرأان حساسات الحركة لعدّ الخطوات أو اكتشاف الرجّة، وتُستخدم القراءات لحظة وصولها ولا تُخزَّن."),
        ("h", "المشتريات"),
        ("p", "يُباع Dawnbreak Pro عبر App Store. تتولى Apple الدفع وتُخبر التطبيق إن كان الشراء ساريًا. ولا يرى التطبيق اسمك ولا بطاقتك ولا حساب Apple الخاص بك."),
        ("h", "الأطفال"),
        ("p", "التطبيق لا يجمع شيئًا من أي شخص في أي عمر، فلا يوجد هنا ما يُعامل بشكل مختلف مع طفل."),
        ("h", "التغييرات"),
        ("p", "إن توقف أي ممّا سبق عن كونه صحيحًا، فستتغير هذه الصفحة في الإصدار نفسه الذي جعله غير صحيح."),
    ],
    "de": [
        ("p", "Dawnbreak erhebt nichts. Es gibt kein Konto, keinen Server, mit dem gesprochen wird, und keine Analyse irgendeiner Art. Diese Seite ist kurz, weil es sehr wenig zu beschreiben gibt."),
        ("h", "Was auf deinem Telefon bleibt"),
        ("p", "Deine Wecker, die daran hängenden Missionen, deine Einstellungen und deine Aufwach-Historie werden in Dateien im eigenen Container der App auf deinem Gerät geschrieben. Sie werden nie hochgeladen. Wenn du dein Gerät in iCloud oder auf einen Computer sicherst, sind sie Teil dieser Sicherung, und das ist eine Sache zwischen dir und Apple."),
        ("h", "Kamera und Bewegungssensoren"),
        ("p", "Drei Missionen nutzen die Kamera: einen Gegenstand fotografieren, einen Barcode scannen, Kniebeugen zählen. Die Bilder werden auf dem Gerät im Speicher ausgewertet, solange die Mission zu sehen ist, und verworfen, sobald das nächste kommt. In deine Fotobibliothek wird nichts geschrieben und übertragen wird nichts. Zwei Missionen lesen die Bewegungssensoren, um Schritte zu zählen oder ein Schütteln zu erkennen; diese Werte werden benutzt, wie sie eintreffen, und nie gespeichert."),
        ("h", "Käufe"),
        ("p", "Dawnbreak Pro wird über den App Store verkauft. Apple nimmt die Zahlung und teilt der App mit, ob ein Kauf aktiv ist. Die App sieht weder deinen Namen noch deine Karte noch deinen Apple-Account."),
        ("h", "Kinder"),
        ("p", "Die App erhebt von niemandem etwas, in keinem Alter, also gibt es hier nichts, was für ein Kind anders behandelt werden müsste."),
        ("h", "Änderungen"),
        ("p", "Sollte etwas davon aufhören zu stimmen, ändert sich diese Seite in derselben Version, die es nicht mehr stimmen lässt."),
    ],
    "es": [
        ("p", "Dawnbreak no recoge nada. No hay cuenta que crear, ni servidor con el que hablar, ni analítica de ningún tipo. Esta página es corta porque hay muy poco que describir."),
        ("h", "Lo que se queda en tu teléfono"),
        ("p", "Tus alarmas, las misiones que llevan asociadas, tus preferencias y tu historial de despertares se escriben en archivos dentro del contenedor propio de la app, en tu dispositivo. Nunca se suben. Si respaldas el dispositivo en iCloud o en un ordenador, forman parte de ese respaldo, que es un asunto entre tú y Apple."),
        ("h", "La cámara y los sensores de movimiento"),
        ("p", "Tres misiones usan la cámara: fotografiar un objeto, escanear un código de barras y contar sentadillas. Los fotogramas se analizan en el dispositivo, en memoria, mientras la misión está en pantalla, y se descartan al llegar el siguiente. No se escribe nada en tu carrete y no se transmite nada. Dos misiones leen los sensores de movimiento para contar pasos o detectar una sacudida; esas lecturas se usan según llegan y nunca se guardan."),
        ("h", "Compras"),
        ("p", "Dawnbreak Pro se vende a través del App Store. Apple cobra y le dice a la app si hay una compra activa. La app nunca ve tu nombre, tu tarjeta ni tu cuenta de Apple."),
        ("h", "Menores"),
        ("p", "La app no recoge nada de nadie, a ninguna edad, así que no hay aquí nada que deba tratarse de otro modo para un menor."),
        ("h", "Cambios"),
        ("p", "Si algo de lo anterior deja de ser cierto, esta página cambia en la misma versión que lo deja de serlo."),
    ],
    "fr": [
        ("p", "Dawnbreak ne collecte rien. Pas de compte à créer, pas de serveur à qui parler, aucune statistique d'aucune sorte. Cette page est courte parce qu'il y a très peu à décrire."),
        ("h", "Ce qui reste sur votre téléphone"),
        ("p", "Vos réveils, les missions qui y sont attachées, vos préférences et votre historique de réveils sont écrits dans des fichiers à l'intérieur du conteneur de l'application, sur votre appareil. Ils ne sont jamais envoyés. Si vous sauvegardez votre appareil sur iCloud ou sur un ordinateur, ils font partie de cette sauvegarde, ce qui se joue entre vous et Apple."),
        ("h", "La caméra et les capteurs de mouvement"),
        ("p", "Trois missions utilisent la caméra : photographier un objet, scanner un code-barres, compter des squats. Les images sont analysées sur l'appareil, en mémoire, pendant que la mission est à l'écran, et jetées dès que la suivante arrive. Rien n'est écrit dans votre photothèque et rien n'est transmis. Deux missions lisent les capteurs de mouvement pour compter des pas ou détecter une secousse ; ces mesures sont utilisées à mesure et jamais conservées."),
        ("h", "Achats"),
        ("p", "Dawnbreak Pro est vendu via l'App Store. Apple encaisse et indique à l'application si un achat est actif. L'application ne voit jamais votre nom, votre carte ni votre compte Apple."),
        ("h", "Enfants"),
        ("p", "L'application ne collecte rien de personne, à aucun âge, il n'y a donc rien ici à traiter différemment pour un enfant."),
        ("h", "Modifications"),
        ("p", "Si l'un des points ci-dessus cesse d'être vrai, cette page change dans la version même qui le rend faux."),
    ],
    "hi": [
        ("p", "Dawnbreak कुछ भी इकट्ठा नहीं करता। कोई खाता बनाना नहीं है, कोई सर्वर से बात नहीं होती, और किसी भी तरह का एनालिटिक्स नहीं है। यह पेज छोटा है क्योंकि बताने के लिए बहुत कम है।"),
        ("h", "आपके फ़ोन पर क्या रहता है"),
        ("p", "आपके अलार्म, उनसे जुड़े मिशन, आपकी पसंद और आपका जागने का इतिहास आपके डिवाइस पर ऐप के अपने कंटेनर के अंदर फ़ाइलों में लिखे जाते हैं। ये कभी अपलोड नहीं होते। अगर आप डिवाइस का बैकअप iCloud या कंप्यूटर पर लेते हैं, तो ये उस बैकअप का हिस्सा होते हैं, जो आपके और Apple के बीच की बात है।"),
        ("h", "कैमरा और मोशन सेंसर"),
        ("p", "तीन मिशन कैमरे का इस्तेमाल करते हैं: किसी चीज़ की फ़ोटो लेना, बारकोड स्कैन करना, और स्क्वैट गिनना। फ़्रेम डिवाइस पर, मेमोरी में, तब तक जांचे जाते हैं जब तक मिशन स्क्रीन पर है, और अगला आते ही फेंक दिए जाते हैं। आपकी फ़ोटो लाइब्रेरी में कुछ नहीं लिखा जाता और कुछ भेजा नहीं जाता। दो मिशन क़दम गिनने या हिलाना पहचानने के लिए मोशन सेंसर पढ़ते हैं; वे रीडिंग आते ही इस्तेमाल होती हैं और कभी संग्रहित नहीं होतीं।"),
        ("h", "ख़रीदारी"),
        ("p", "Dawnbreak Pro App Store के ज़रिए बिकता है। भुगतान Apple लेता है और ऐप को बताता है कि कोई ख़रीद सक्रिय है या नहीं। ऐप आपका नाम, आपका कार्ड या आपका Apple खाता कभी नहीं देखता।"),
        ("h", "बच्चे"),
        ("p", "ऐप किसी भी उम्र के किसी भी व्यक्ति से कुछ इकट्ठा नहीं करता, इसलिए यहां किसी बच्चे के लिए अलग बरताव करने जैसा कुछ नहीं है।"),
        ("h", "बदलाव"),
        ("p", "अगर ऊपर लिखी कोई बात सच न रह जाए, तो यह पेज उसी रिलीज़ में बदल जाएगा जो उसे बदल देती है।"),
    ],
    "it": [
        ("p", "Dawnbreak non raccoglie nulla. Non c'è un account da creare, non c'è un server con cui parlare, non c'è analitica di alcun tipo. Questa pagina è corta perché c'è molto poco da descrivere."),
        ("h", "Cosa resta sul telefono"),
        ("p", "Le tue sveglie, le missioni collegate, le tue preferenze e il tuo storico dei risvegli vengono scritti in file dentro il container dell'app, sul tuo dispositivo. Non vengono mai caricati. Se fai il backup del dispositivo su iCloud o su un computer, fanno parte di quel backup, che è una questione fra te e Apple."),
        ("h", "La fotocamera e i sensori di movimento"),
        ("p", "Tre missioni usano la fotocamera: fotografare un oggetto, scansionare un codice a barre, contare gli squat. I fotogrammi vengono analizzati sul dispositivo, in memoria, mentre la missione è a schermo, e scartati appena arriva il successivo. Nella tua libreria foto non viene scritto niente e niente viene trasmesso. Due missioni leggono i sensori di movimento per contare i passi o rilevare una scossa; quelle letture si usano man mano e non vengono mai salvate."),
        ("h", "Acquisti"),
        ("p", "Dawnbreak Pro si vende tramite l'App Store. Apple incassa e comunica all'app se un acquisto è attivo. L'app non vede mai il tuo nome, la tua carta o il tuo account Apple."),
        ("h", "Bambini"),
        ("p", "L'app non raccoglie nulla da nessuno, a nessuna età, quindi qui non c'è niente da trattare diversamente per un bambino."),
        ("h", "Modifiche"),
        ("p", "Se qualcosa di quanto sopra smette di essere vero, questa pagina cambia nella stessa versione che lo rende falso."),
    ],
    "ja": [
        ("p", "Dawnbreak は何も収集しません。作るアカウントはなく、通信する相手のサーバーもなく、いかなる解析もありません。このページが短いのは、書くことがほとんどないからです。"),
        ("h", "端末に残るもの"),
        ("p", "アラーム、それに結びついたミッション、設定、起床の記録は、端末上のアプリ専用の領域にあるファイルに書かれます。アップロードされることはありません。iCloud やコンピュータにバックアップを取れば、それはバックアップの一部になります。そこから先はあなたと Apple の間の話です。"),
        ("h", "カメラとモーションセンサー"),
        ("p", "カメラを使うミッションは三つです。対象物の撮影、バーコードの読み取り、スクワットの計数。映像はミッションが表示されている間、端末上のメモリで解析され、次の映像が来た時点で捨てられます。写真ライブラリには何も書き込まれず、何も送信されません。歩数の計数と振りの検出のために、二つのミッションがモーションセンサーを読みます。その値は届いたその場で使われ、記録されることはありません。"),
        ("h", "購入について"),
        ("p", "Dawnbreak Pro は App Store で販売されます。支払いは Apple が処理し、購入が有効かどうかだけがアプリに伝わります。アプリがあなたの名前、カード、Apple アカウントを見ることはありません。"),
        ("h", "子どもについて"),
        ("p", "年齢にかかわらず誰からも何も収集しないので、子どもに対して別に扱うべきものがここにはありません。"),
        ("h", "変更"),
        ("p", "上のどれかが事実でなくなったときは、事実でなくしたリリースと同じリリースでこのページも変わります。"),
    ],
    "ko": [
        ("p", "Dawnbreak는 아무것도 수집하지 않습니다. 만들 계정도, 이야기할 서버도, 어떤 종류의 분석도 없습니다. 이 페이지가 짧은 것은 설명할 것이 거의 없기 때문입니다."),
        ("h", "휴대폰에 남는 것"),
        ("p", "알람, 거기에 붙은 미션, 설정, 기상 기록은 기기 안 앱 전용 영역의 파일에 기록됩니다. 업로드되는 일은 없습니다. iCloud나 컴퓨터로 백업하면 그 백업의 일부가 되며, 그다음은 당신과 Apple 사이의 일입니다."),
        ("h", "카메라와 모션 센서"),
        ("p", "카메라를 쓰는 미션은 셋입니다. 물건 촬영, 바코드 스캔, 스쿼트 계수. 영상은 미션이 화면에 있는 동안 기기 안 메모리에서 분석되고, 다음 영상이 오면 버려집니다. 사진 라이브러리에는 아무것도 기록되지 않고, 전송되는 것도 없습니다. 걸음 수를 세거나 흔들기를 감지하기 위해 두 미션이 모션 센서를 읽습니다. 그 값은 들어오는 대로 쓰이고 저장되지 않습니다."),
        ("h", "구매"),
        ("p", "Dawnbreak Pro는 App Store를 통해 판매됩니다. 결제는 Apple이 처리하고, 앱에는 구매가 유효한지만 전달됩니다. 앱이 당신의 이름, 카드, Apple 계정을 보는 일은 없습니다."),
        ("h", "아동"),
        ("p", "나이와 무관하게 누구에게서도 아무것도 수집하지 않으므로, 아동에게 다르게 다룰 것이 여기에는 없습니다."),
        ("h", "변경"),
        ("p", "위의 내용 중 무엇이든 사실이 아니게 되면, 사실이 아니게 만든 그 릴리스에서 이 페이지도 함께 바뀝니다."),
    ],
    "pt-BR": [
        ("p", "O Dawnbreak não coleta nada. Não há conta para criar, não há servidor com quem falar e não há analytics de nenhum tipo. Esta página é curta porque há muito pouco a descrever."),
        ("h", "O que fica no seu telefone"),
        ("p", "Seus despertadores, as missões ligadas a eles, suas preferências e seu histórico de despertares são gravados em arquivos dentro do container da própria app, no seu aparelho. Nunca são enviados. Se você faz backup do aparelho no iCloud ou num computador, eles fazem parte desse backup, o que é assunto entre você e a Apple."),
        ("h", "A câmera e os sensores de movimento"),
        ("p", "Três missões usam a câmera: fotografar um objeto, escanear um código de barras e contar agachamentos. Os quadros são analisados no aparelho, na memória, enquanto a missão está na tela, e descartados quando chega o seguinte. Nada é gravado na sua biblioteca de fotos e nada é transmitido. Duas missões leem os sensores de movimento para contar passos ou detectar uma sacudida; essas leituras são usadas conforme chegam e nunca guardadas."),
        ("h", "Compras"),
        ("p", "O Dawnbreak Pro é vendido pela App Store. A Apple recebe o pagamento e informa à app se há uma compra ativa. A app nunca vê seu nome, seu cartão ou sua conta Apple."),
        ("h", "Crianças"),
        ("p", "A app não coleta nada de ninguém, em nenhuma idade, então não há aqui nada a tratar de outro modo para uma criança."),
        ("h", "Alterações"),
        ("p", "Se alguma das afirmações acima deixar de ser verdade, esta página muda na mesma versão que a torna falsa."),
    ],
    "ru": [
        ("p", "Dawnbreak ничего не собирает. Нет учётной записи, нет сервера, с которым он общается, нет аналитики любого рода. Эта страница короткая, потому что описывать почти нечего."),
        ("h", "Что остаётся на телефоне"),
        ("p", "Ваши будильники, привязанные к ним задания, настройки и история пробуждений записываются в файлы внутри собственного контейнера приложения на вашем устройстве. Они никогда не выгружаются. Если вы делаете резервную копию устройства в iCloud или на компьютер, они входят в неё, и это уже дело между вами и Apple."),
        ("h", "Камера и датчики движения"),
        ("p", "Камеру используют три задания: снять предмет, отсканировать штрихкод, посчитать приседания. Кадры разбираются на устройстве, в памяти, пока задание на экране, и выбрасываются с приходом следующего. В вашу медиатеку ничего не пишется и ничего не передаётся. Два задания читают датчики движения, чтобы считать шаги или заметить встряхивание; эти показания используются по мере поступления и никогда не сохраняются."),
        ("h", "Покупки"),
        ("p", "Dawnbreak Pro продаётся через App Store. Оплату принимает Apple и сообщает приложению лишь то, активна ли покупка. Приложение никогда не видит ваше имя, вашу карту или вашу учётную запись Apple."),
        ("h", "Дети"),
        ("p", "Приложение ничего не собирает ни у кого и ни в каком возрасте, поэтому здесь нечего рассматривать иначе для ребёнка."),
        ("h", "Изменения"),
        ("p", "Если что-либо из перечисленного перестанет быть правдой, эта страница изменится в том же выпуске, который сделает её неправдой."),
    ],
    "zh-Hans": [
        ("p", "Dawnbreak 不收集任何东西。没有要注册的账号，没有要通信的服务器，也没有任何形式的统计分析。这一页很短，因为可写的实在不多。"),
        ("h", "留在你手机上的东西"),
        ("p", "你的闹钟、挂在闹钟上的任务、你的偏好设置和你的起床记录，都写进设备上属于这个应用自己的容器里的文件。它们从不上传。如果你把设备备份到 iCloud 或电脑，它们会在那份备份里，而那是你和 Apple 之间的事。"),
        ("h", "摄像头与运动传感器"),
        ("p", "有三个任务用到摄像头：拍下一件物品、扫描条码、数深蹲。画面在任务显示期间于设备内存中分析，下一帧到来时即丢弃。不会往你的照片图库里写入任何东西，也不会传出任何东西。另有两个任务读取运动传感器来数步数或识别摇动；这些读数随到随用，从不保存。"),
        ("h", "购买"),
        ("p", "Dawnbreak Pro 通过 App Store 销售。付款由 Apple 处理，应用只知道购买是否有效。应用永远看不到你的姓名、你的银行卡或你的 Apple 账户。"),
        ("h", "儿童"),
        ("p", "本应用不从任何年龄的任何人处收集任何东西，因此这里没有需要对儿童另行处理的部分。"),
        ("h", "变更"),
        ("p", "如果上面任何一条不再成立，这一页会在让它不再成立的那个版本里一起改。"),
    ],
}

SUPPORT = {
    "en": [
        ("p", "Dawnbreak is an alarm that will not switch off until you have done something. Most questions are about the alarm not ringing, or about the mission being harder than expected at six in the morning. Both are below."),
        ("h", "The alarm did not ring"),
        ("ul", [
            "Alarms need permission. The app asks once, on the first launch; if it was declined, turn it on in Settings, under Dawnbreak.",
            "An alarm you saved but never switched on will not ring. The toggle on the row is the one that matters.",
            "Focus and Do Not Disturb do not silence it. Alarms are exempt by design.",
            "A phone that ran out of battery overnight cannot ring. Low Power Mode on its own is fine.",
        ]),
        ("h", "I cannot finish the mission"),
        ("p", "Every alarm has an emergency exit. Hold the button at the bottom of the mission screen and the alarm stops. It is on by default and can be turned off in Settings, which is worth doing only once you no longer need it."),
        ("h", "Restoring a purchase"),
        ("p", "Settings, then Dawnbreak Pro, then Restore Purchases, signed in with the Apple Account that bought it. Subscriptions are managed in the App Store rather than here."),
        ("h", "Deleting everything"),
        ("p", "Deleting the app deletes the alarms and the history with it. There is no copy anywhere else, and nothing to ask us to erase."),
        ("h", "Anything else"),
        ("p", "Open an issue and it will be read. Please include your iOS version, the mission, and what the alarm was set to."),
    ],
    "ar": [
        ("p", "‏Dawnbreak منبّه لا ينطفئ حتى تفعل شيئًا. أكثر الأسئلة تدور حول منبّه لم يرن، أو حول مهمة تبدو أصعب مما توقعت في السادسة صباحًا. وكلاهما هنا."),
        ("h", "المنبّه لم يرن"),
        ("ul", [
            "المنبّهات تحتاج إذنًا. يطلبه التطبيق مرة واحدة عند أول تشغيل؛ فإن رُفض، شغّله من الإعدادات ضمن Dawnbreak.",
            "المنبّه الذي حفظته ولم تشغّله لن يرن. المفتاح الموجود على السطر هو المهم.",
            "‏Focus ووضع عدم الإزعاج لا يُسكتانه. المنبّهات مستثناة بالتصميم.",
            "الهاتف الذي نفدت بطاريته ليلًا لا يستطيع أن يرن. أما وضع الطاقة المنخفضة وحده فلا مشكلة فيه.",
        ]),
        ("h", "لا أستطيع إنهاء المهمة"),
        ("p", "لكل منبّه مخرج طوارئ. اضغط مطوّلًا على الزر في أسفل شاشة المهمة فيتوقف المنبّه. وهو مفعّل تلقائيًا ويمكن إيقافه من الإعدادات، وهذا يستحق الفعل فقط عندما لا تحتاجه بعد."),
        ("h", "استعادة عملية شراء"),
        ("p", "الإعدادات، ثم Dawnbreak Pro، ثم استعادة المشتريات، بحساب Apple الذي اشترى. أما الاشتراكات فتُدار من App Store لا من هنا."),
        ("h", "حذف كل شيء"),
        ("p", "حذف التطبيق يحذف المنبّهات والسجل معه. لا توجد نسخة في أي مكان آخر، ولا شيء تطلب منّا محوه."),
        ("h", "أي شيء آخر"),
        ("p", "افتح مسألة وستُقرأ. أرجو ذكر إصدار iOS، والمهمة، وما كان المنبّه مضبوطًا عليه."),
    ],
    "de": [
        ("p", "Dawnbreak ist ein Wecker, der sich erst abschaltet, wenn du etwas getan hast. Die meisten Fragen drehen sich um einen Wecker, der nicht geklingelt hat, oder um eine Mission, die um sechs Uhr morgens schwerer ist als gedacht. Beides steht hier."),
        ("h", "Der Wecker hat nicht geklingelt"),
        ("ul", [
            "Wecker brauchen eine Berechtigung. Die App fragt einmal, beim ersten Start; wurde sie abgelehnt, schalte sie in den Einstellungen unter Dawnbreak ein.",
            "Ein Wecker, den du gespeichert aber nie eingeschaltet hast, klingelt nicht. Entscheidend ist der Schalter in der Zeile.",
            "Fokus und Nicht stören schalten ihn nicht stumm. Wecker sind bewusst ausgenommen.",
            "Ein Telefon, dessen Akku nachts leer wurde, kann nicht klingeln. Der Energiesparmodus allein ist unproblematisch.",
        ]),
        ("h", "Ich schaffe die Mission nicht"),
        ("p", "Jeder Wecker hat einen Notausgang. Halte den Knopf unten auf dem Missionsbildschirm gedrückt, und der Wecker hört auf. Er ist standardmäßig an und lässt sich in den Einstellungen abschalten, was sich erst lohnt, wenn du ihn nicht mehr brauchst."),
        ("h", "Einen Kauf wiederherstellen"),
        ("p", "Einstellungen, dann Dawnbreak Pro, dann Käufe wiederherstellen, angemeldet mit dem Apple-Account, der gekauft hat. Abos werden im App Store verwaltet, nicht hier."),
        ("h", "Alles löschen"),
        ("p", "Die App zu löschen löscht die Wecker und die Historie mit. Es gibt nirgends eine Kopie und nichts, um dessen Löschung du uns bitten müsstest."),
        ("h", "Alles andere"),
        ("p", "Öffne ein Issue, es wird gelesen. Bitte nenne deine iOS-Version, die Mission und wie der Wecker eingestellt war."),
    ],
    "es": [
        ("p", "Dawnbreak es un despertador que no se apaga hasta que has hecho algo. Casi todas las preguntas son sobre una alarma que no sonó o sobre una misión más difícil de lo previsto a las seis de la mañana. Las dos están aquí."),
        ("h", "La alarma no sonó"),
        ("ul", [
            "Las alarmas necesitan permiso. La app lo pide una vez, en el primer arranque; si se denegó, actívalo en Ajustes, dentro de Dawnbreak.",
            "Una alarma que guardaste pero nunca activaste no suena. El interruptor de la fila es el que cuenta.",
            "Concentración y No molestar no la silencian. Las alarmas están exentas a propósito.",
            "Un teléfono que se quedó sin batería de noche no puede sonar. El modo de bajo consumo por sí solo no estorba.",
        ]),
        ("h", "No consigo terminar la misión"),
        ("p", "Toda alarma tiene una salida de emergencia. Mantén pulsado el botón de abajo en la pantalla de la misión y la alarma se detiene. Está activada por defecto y se puede desactivar en Ajustes, lo cual solo vale la pena cuando ya no la necesitas."),
        ("h", "Restaurar una compra"),
        ("p", "Ajustes, luego Dawnbreak Pro, luego Restaurar compras, con la cuenta de Apple que compró. Las suscripciones se gestionan en el App Store, no aquí."),
        ("h", "Borrarlo todo"),
        ("p", "Borrar la app borra las alarmas y el historial con ella. No hay copia en ningún otro sitio, ni nada que pedirnos que eliminemos."),
        ("h", "Cualquier otra cosa"),
        ("p", "Abre una incidencia y se leerá. Indica tu versión de iOS, la misión y cómo estaba puesta la alarma."),
    ],
    "fr": [
        ("p", "Dawnbreak est un réveil qui ne s'éteint pas avant que vous ayez fait quelque chose. La plupart des questions portent sur un réveil qui n'a pas sonné, ou sur une mission plus difficile que prévu à six heures du matin. Les deux sont ici."),
        ("h", "Le réveil n'a pas sonné"),
        ("ul", [
            "Les réveils demandent une autorisation. L'application la demande une fois, au premier lancement ; si elle a été refusée, activez-la dans Réglages, sous Dawnbreak.",
            "Un réveil enregistré mais jamais activé ne sonnera pas. C'est l'interrupteur sur la ligne qui compte.",
            "Concentration et Ne pas déranger ne le font pas taire. Les réveils en sont exemptés par conception.",
            "Un téléphone dont la batterie s'est vidée dans la nuit ne peut pas sonner. Le mode économie d'énergie seul ne gêne rien.",
        ]),
        ("h", "Je n'arrive pas à finir la mission"),
        ("p", "Chaque réveil a une sortie de secours. Maintenez le bouton en bas de l'écran de mission et le réveil s'arrête. Elle est active par défaut et se désactive dans les Réglages, ce qui ne vaut la peine que le jour où vous n'en avez plus besoin."),
        ("h", "Restaurer un achat"),
        ("p", "Réglages, puis Dawnbreak Pro, puis Restaurer les achats, connecté avec le compte Apple qui a acheté. Les abonnements se gèrent dans l'App Store et non ici."),
        ("h", "Tout supprimer"),
        ("p", "Supprimer l'application supprime les réveils et l'historique avec. Il n'y a de copie nulle part ailleurs, et rien à nous demander d'effacer."),
        ("h", "Autre chose"),
        ("p", "Ouvrez un ticket, il sera lu. Précisez votre version d'iOS, la mission, et le réglage du réveil."),
    ],
    "hi": [
        ("p", "Dawnbreak एक अलार्म है जो कुछ करने तक बंद नहीं होता। ज़्यादातर सवाल अलार्म न बजने के बारे में होते हैं, या सुबह छह बजे मिशन के उम्मीद से ज़्यादा मुश्किल लगने के बारे में। दोनों नीचे हैं।"),
        ("h", "अलार्म नहीं बजा"),
        ("ul", [
            "अलार्म के लिए अनुमति चाहिए। ऐप पहली बार खुलने पर एक बार पूछता है; मना कर दिया हो तो Settings में Dawnbreak के नीचे चालू करें।",
            "जो अलार्म आपने सहेजा पर कभी चालू नहीं किया, वह नहीं बजेगा। पंक्ति पर लगा टॉगल ही मायने रखता है।",
            "Focus और Do Not Disturb इसे चुप नहीं कराते। अलार्म को जान-बूझकर छूट दी गई है।",
            "रात में बैटरी ख़त्म हो चुका फ़ोन बज नहीं सकता। अकेला Low Power Mode कोई अड़चन नहीं है।",
        ]),
        ("h", "मैं मिशन पूरा नहीं कर पा रहा"),
        ("p", "हर अलार्म में आपातकालीन रास्ता है। मिशन स्क्रीन पर नीचे वाले बटन को दबाकर रखें और अलार्म रुक जाएगा। यह डिफ़ॉल्ट रूप से चालू है और Settings में बंद किया जा सकता है, जो तभी करने लायक है जब आपको इसकी ज़रूरत न रह जाए।"),
        ("h", "ख़रीद बहाल करना"),
        ("p", "Settings, फिर Dawnbreak Pro, फिर Restore Purchases, उसी Apple खाते से जिसने ख़रीदा था। सब्सक्रिप्शन App Store में संभाले जाते हैं, यहां नहीं।"),
        ("h", "सब कुछ मिटाना"),
        ("p", "ऐप हटाने से अलार्म और इतिहास भी उसके साथ हट जाते हैं। कहीं और कोई प्रति नहीं है, और हमसे मिटाने को कहने जैसा कुछ नहीं है।"),
        ("h", "और कुछ"),
        ("p", "एक issue खोलें, उसे पढ़ा जाएगा। कृपया अपना iOS संस्करण, मिशन, और अलार्म की सेटिंग बताएं।"),
    ],
    "it": [
        ("p", "Dawnbreak è una sveglia che non si spegne finché non hai fatto qualcosa. Quasi tutte le domande riguardano una sveglia che non ha suonato, o una missione più difficile del previsto alle sei del mattino. Ci sono entrambe qui."),
        ("h", "La sveglia non ha suonato"),
        ("ul", [
            "Le sveglie richiedono un permesso. L'app lo chiede una volta, al primo avvio; se è stato negato, attivalo in Impostazioni, sotto Dawnbreak.",
            "Una sveglia salvata ma mai attivata non suona. Conta l'interruttore sulla riga.",
            "Full Immersion e Non disturbare non la silenziano. Le sveglie sono escluse per scelta.",
            "Un telefono rimasto senza batteria di notte non può suonare. La modalità Risparmio energetico da sola non dà problemi.",
        ]),
        ("h", "Non riesco a finire la missione"),
        ("p", "Ogni sveglia ha un'uscita di emergenza. Tieni premuto il pulsante in basso nella schermata della missione e la sveglia si ferma. È attiva di serie e si può disattivare in Impostazioni, cosa che conviene fare solo quando non ti serve più."),
        ("h", "Ripristinare un acquisto"),
        ("p", "Impostazioni, poi Dawnbreak Pro, poi Ripristina acquisti, con l'account Apple che ha comprato. Gli abbonamenti si gestiscono nell'App Store, non qui."),
        ("h", "Cancellare tutto"),
        ("p", "Eliminare l'app elimina le sveglie e lo storico con essa. Non c'è una copia altrove, e non c'è nulla da chiederci di cancellare."),
        ("h", "Qualsiasi altra cosa"),
        ("p", "Apri una issue e verrà letta. Indica la versione di iOS, la missione e com'era impostata la sveglia."),
    ],
    "ja": [
        ("p", "Dawnbreak は、何かをするまで切れない目覚ましです。届く質問のほとんどは、鳴らなかったという話か、朝六時のミッションが思ったより難しいという話です。どちらも以下にあります。"),
        ("h", "アラームが鳴らなかった"),
        ("ul", [
            "アラームには許可が必要です。初回起動時に一度だけ尋ねます。断ってしまった場合は、設定の Dawnbreak からオンにしてください。",
            "保存しただけでオンにしていないアラームは鳴りません。効くのは行にあるスイッチです。",
            "集中モードやおやすみモードでは消音されません。アラームは意図的に対象外です。",
            "夜のあいだにバッテリーが切れた端末は鳴れません。低電力モードそのものは問題ありません。",
        ]),
        ("h", "ミッションを終えられません"),
        ("p", "どのアラームにも緊急脱出があります。ミッション画面の下のボタンを長押しすればアラームは止まります。初期状態でオンで、設定でオフにできますが、それが役に立つのは必要なくなってからです。"),
        ("h", "購入の復元"),
        ("p", "設定、Dawnbreak Pro、購入の復元の順に、購入した Apple アカウントでサインインした状態で行ってください。サブスクリプションの管理はここではなく App Store です。"),
        ("h", "すべて削除する"),
        ("p", "アプリを削除すれば、アラームと記録も一緒に消えます。ほかに控えはなく、こちらに消去を依頼するものもありません。"),
        ("h", "それ以外"),
        ("p", "issue を立ててください。読みます。iOS のバージョン、ミッション、アラームの設定内容を書き添えてください。"),
    ],
    "ko": [
        ("p", "Dawnbreak는 무언가를 하기 전까지 꺼지지 않는 알람입니다. 들어오는 질문은 대개 알람이 울리지 않았다는 것, 아니면 아침 여섯 시의 미션이 생각보다 어렵다는 것입니다. 둘 다 아래에 있습니다."),
        ("h", "알람이 울리지 않았습니다"),
        ("ul", [
            "알람에는 권한이 필요합니다. 앱이 첫 실행에서 한 번 묻습니다. 거절했다면 설정의 Dawnbreak에서 켜주세요.",
            "저장만 하고 켜지 않은 알람은 울리지 않습니다. 중요한 것은 행에 있는 스위치입니다.",
            "집중 모드와 방해금지 모드는 이 알람을 음소거하지 않습니다. 알람은 의도적으로 예외입니다.",
            "밤사이 배터리가 다 떨어진 기기는 울릴 수 없습니다. 저전력 모드 자체는 문제가 없습니다.",
        ]),
        ("h", "미션을 끝낼 수 없습니다"),
        ("p", "모든 알람에는 비상 탈출이 있습니다. 미션 화면 아래 버튼을 길게 누르면 알람이 멈춥니다. 기본으로 켜져 있고 설정에서 끌 수 있지만, 그럴 만한 때는 더 이상 필요하지 않게 된 뒤입니다."),
        ("h", "구매 복원"),
        ("p", "설정, Dawnbreak Pro, 구매 복원 순서로, 구매한 Apple 계정으로 로그인한 상태에서 하세요. 구독 관리는 여기가 아니라 App Store에서 합니다."),
        ("h", "전부 삭제하기"),
        ("p", "앱을 삭제하면 알람과 기록도 함께 사라집니다. 다른 곳에 사본이 없고, 저희에게 삭제를 요청할 것도 없습니다."),
        ("h", "그 밖의 문의"),
        ("p", "issue를 남겨주시면 읽습니다. iOS 버전, 미션, 알람 설정 내용을 함께 적어주세요."),
    ],
    "pt-BR": [
        ("p", "O Dawnbreak é um despertador que não desliga até você fazer algo. Quase toda pergunta é sobre um despertador que não tocou, ou sobre uma missão mais difícil do que se esperava às seis da manhã. As duas estão aqui."),
        ("h", "O despertador não tocou"),
        ("ul", [
            "Despertadores precisam de permissão. A app pede uma vez, na primeira abertura; se foi negada, ative em Ajustes, dentro de Dawnbreak.",
            "Um despertador que você salvou mas nunca ligou não toca. O que vale é a chave na linha.",
            "Foco e Não Perturbe não o silenciam. Despertadores são isentos de propósito.",
            "Um telefone que ficou sem bateria de madrugada não consegue tocar. O Modo de Pouca Energia por si só não atrapalha.",
        ]),
        ("h", "Não consigo terminar a missão"),
        ("p", "Todo despertador tem uma saída de emergência. Mantenha pressionado o botão de baixo na tela da missão e o despertador para. Vem ligada e pode ser desligada em Ajustes, o que só vale a pena quando você não precisar mais dela."),
        ("h", "Restaurar uma compra"),
        ("p", "Ajustes, depois Dawnbreak Pro, depois Restaurar compras, com a conta Apple que comprou. Assinaturas são gerenciadas na App Store, não aqui."),
        ("h", "Apagar tudo"),
        ("p", "Apagar a app apaga os despertadores e o histórico junto. Não existe cópia em outro lugar, nem nada para pedir que a gente apague."),
        ("h", "Qualquer outra coisa"),
        ("p", "Abra uma issue e ela será lida. Informe sua versão do iOS, a missão e como o despertador estava configurado."),
    ],
    "ru": [
        ("p", "Dawnbreak — будильник, который не выключается, пока вы что-нибудь не сделаете. Почти все вопросы про то, что будильник не зазвонил, или про задание, которое в шесть утра оказалось труднее, чем ожидалось. И то, и другое ниже."),
        ("h", "Будильник не зазвонил"),
        ("ul", [
            "Будильникам нужно разрешение. Приложение спрашивает один раз, при первом запуске; если было отказано, включите его в Настройках, в разделе Dawnbreak.",
            "Будильник, который вы сохранили, но не включили, не зазвонит. Решает переключатель в строке.",
            "Фокусирование и режим «Не беспокоить» его не приглушают. Будильники намеренно исключены.",
            "Телефон, у которого за ночь села батарея, зазвонить не может. Сам режим энергосбережения при этом не мешает.",
        ]),
        ("h", "Я не могу выполнить задание"),
        ("p", "У каждого будильника есть аварийный выход. Удерживайте кнопку внизу экрана задания, и будильник остановится. Он включён по умолчанию и отключается в настройках, что имеет смысл только тогда, когда он вам больше не нужен."),
        ("h", "Восстановление покупки"),
        ("p", "Настройки, затем Dawnbreak Pro, затем «Восстановить покупки», с той учётной записью Apple, которая покупала. Подписками управляют в App Store, а не здесь."),
        ("h", "Удалить всё"),
        ("p", "Удаление приложения удаляет вместе с ним будильники и историю. Копии нигде нет, и просить нас что-то стереть не нужно."),
        ("h", "Всё остальное"),
        ("p", "Откройте issue, его прочитают. Укажите версию iOS, задание и то, как был настроен будильник."),
    ],
    "zh-Hans": [
        ("p", "Dawnbreak 是一个在你做完某件事之前不会关掉的闹钟。绝大多数问题都是关于闹钟没响，或者早上六点的任务比想象中难。两件事都写在下面。"),
        ("h", "闹钟没响"),
        ("ul", [
            "闹钟需要权限。应用在首次启动时问一次；如果当时拒绝了，请到「设置」里的 Dawnbreak 打开它。",
            "只保存却没打开的闹钟不会响。起作用的是那一行上的开关。",
            "专注模式和「不供打扰」不会把它静音。闹钟是有意排除在外的。",
            "夜里电池耗尽的手机响不了。单是低电量模式并不影响。",
        ]),
        ("h", "我完不成任务"),
        ("p", "每个闹钟都有紧急退出。长按任务界面下方的按钮，闹钟就会停下。它默认开启，也可以在设置里关掉，而那只在你已经不需要它之后才值得做。"),
        ("h", "恢复购买"),
        ("p", "设置，然后 Dawnbreak Pro，然后「恢复购买」，用当初购买的那个 Apple 账户登录。订阅在 App Store 里管理，不在这里。"),
        ("h", "全部删除"),
        ("p", "删除应用会一并删除闹钟和记录。别处没有副本，也没有需要请我们抹除的东西。"),
        ("h", "其他问题"),
        ("p", "开一个 issue，会有人读。请附上你的 iOS 版本、任务，以及闹钟当时的设置。"),
    ],
}

PAGES = {
    "index": INDEX,
    "privacy": PRIVACY,
    "support": SUPPORT,
}
