"""The upgrade screen.

The numbers in this copy are the real limits from `Entitlement`: free gets 1 alarm, 1 round,
3 missions (math, shake, breathe) and difficulty up to medium. Pro gets 25 alarms, 10 rounds,
all 12 missions and all 4 difficulties. If those constants change, this file is wrong, and the
App Store rejects paywalls that promise what the app does not deliver.

Order of values in every row: en ar de es fr hi it ja ko pt-BR ru zh-Hans
"""

from . import family

PAYWALL = {
    "paywall.subhead": ["All twelve missions, twenty-five alarms, every difficulty. One app, no account, no adverts.", "كل المهام الاثنتَي عشرة، خمسة وعشرون منبهاً، كل مستويات الصعوبة. تطبيق واحد، بلا حساب، بلا إعلانات.", "Alle zwölf Missionen, 25 Alarme, jede Schwierigkeit. Eine App, kein Konto, keine Werbung.", "Las doce misiones, veinticinco alarmas, todas las dificultades. Una app, sin cuenta, sin anuncios.", "Les douze missions, vingt-cinq alarmes, toutes les difficultés. Une app, sans compte, sans publicité.", "सभी बारह मिशन, पच्चीस अलार्म, हर कठिनाई। एक ऐप, कोई अकाउंट नहीं, कोई विज्ञापन नहीं।", "Tutte le dodici missioni, venticinque sveglie, ogni difficoltà. Un’app, nessun account, nessuna pubblicità.", "12 のミッションすべて、アラーム 25 個、すべての難易度。アカウント不要、広告なし。", "열두 가지 미션 전부, 알람 25개, 모든 난이도. 계정도 광고도 없습니다.", "Todas as doze missões, vinte e cinco alarmes, todas as dificuldades. Um app, sem conta, sem anúncios.", "Все двенадцать заданий, двадцать пять будильников, любая сложность. Одно приложение, без аккаунта и рекламы.", "全部十二种任务、二十五个闹钟、所有难度。一个应用，无需账号，没有广告。"],
    "paywall.feature.missions": ["All twelve missions", "كل المهام الاثنتَي عشرة", "Alle zwölf Missionen", "Las doce misiones", "Les douze missions", "सभी बारह मिशन", "Tutte le dodici missioni", "12 のミッションすべて", "열두 가지 미션 전부", "Todas as doze missões", "Все двенадцать заданий", "全部十二种任务"],
    "paywall.feature.missions.body": ["Walk to the kettle and photograph it, scan a barcode, do squats on camera, draw what you are told. Free keeps three.", "امشِ إلى الغلاية وصوّرها، امسح باركود، اسجد قرفصاء أمام الكاميرا، ارسم ما يُطلب منك. المجاني يمنحك ثلاث مهام.", "Zum Wasserkocher gehen und ihn fotografieren, Barcode scannen, Kniebeugen vor der Kamera, auf Kommando zeichnen. Gratis bleiben drei.", "Ve hasta la tetera y fotografíala, escanea un código, haz sentadillas ante la cámara, dibuja lo que te pidan. Gratis te deja tres.", "Aller jusqu’à la bouilloire et la photographier, scanner un code-barres, faire des squats face caméra, dessiner à la demande. La version gratuite en garde trois.", "केतली तक जाकर फ़ोटो लें, बारकोड स्कैन करें, कैमरे के सामने स्क्वैट करें, जो कहा जाए वह बनाएँ। मुफ़्त में तीन मिशन मिलते हैं।", "Vai fino al bollitore e fotografalo, scansiona un codice, fai squat davanti alla fotocamera, disegna a comando. La versione gratuita ne tiene tre.", "ケトルまで歩いて撮影、バーコードを読み取り、カメラの前でスクワット、指示どおりに描く。無料版は 3 つまで。", "주전자까지 걸어가 사진을 찍고, 바코드를 스캔하고, 카메라 앞에서 스쿼트하고, 지시대로 그리세요. 무료에서는 세 가지만.", "Vá até a chaleira e fotografe, escaneie um código, faça agachamentos na câmera, desenhe o que mandarem. O grátis fica com três.", "Дойти до чайника и сфотографировать его, отсканировать штрих-код, приседать перед камерой, нарисовать, что скажут. В бесплатной версии — три задания.", "走到水壶前拍下它、扫描条码、在镜头前深蹲、照要求画画。免费版保留三种。"],
    "paywall.feature.alarms": ["Twenty-five alarms", "خمسة وعشرون منبهاً", "25 Alarme", "Veinticinco alarmas", "Vingt-cinq alarmes", "पच्चीस अलार्म", "Venticinque sveglie", "アラーム 25 個", "알람 25개", "Vinte e cinco alarmes", "Двадцать пять будильников", "二十五个闹钟"],
    "paywall.feature.alarms.body": ["Weekdays, the gym, the flight, the exam. Free gives you one.", "أيام العمل، النادي، الرحلة، الامتحان. المجاني يمنحك منبهاً واحداً.", "Wochentage, Sport, Flug, Prüfung. Gratis gibt es einen.", "Días de semana, el gimnasio, el vuelo, el examen. Gratis te da una.", "La semaine, le sport, l’avion, l’examen. La version gratuite en donne une.", "कार्यदिवस, जिम, फ़्लाइट, परीक्षा। मुफ़्त में एक मिलता है।", "Giorni feriali, palestra, volo, esame. La versione gratuita ne dà una.", "平日、ジム、フライト、試験。無料版は 1 個です。", "평일, 운동, 비행기, 시험. 무료는 하나입니다.", "Dias de semana, academia, voo, prova. O grátis dá um.", "Будни, спортзал, самолёт, экзамен. В бесплатной версии — один.", "工作日、健身、航班、考试。免费版只有一个。"],
    "paywall.feature.difficulty": ["Hard and brutal", "صعب ووحشي", "Schwer und brutal", "Difícil y brutal", "Difficile et brutal", "कठिन और क्रूर", "Difficile e brutale", "難しい・容赦なし", "어려움과 잔혹", "Difícil e brutal", "Сложно и жестоко", "困难与残酷"],
    "paywall.feature.difficulty.body": ["Bigger sums, longer patterns, more repetitions, up to ten rounds. Set it past what you can fake half asleep.", "عمليات أكبر، أنماط أطول، تكرارات أكثر، حتى عشر جولات. اضبطها فوق ما يمكنك تمثيله نصف نائم.", "Größere Rechnungen, längere Muster, mehr Wiederholungen, bis zu zehn Runden. Stelle es höher, als du halb schlafend vortäuschen kannst.", "Cuentas más grandes, patrones más largos, más repeticiones, hasta diez rondas. Ponlo más allá de lo que puedes fingir medio dormido.", "Calculs plus gros, séquences plus longues, plus de répétitions, jusqu’à dix manches. Réglez au-delà de ce que vous pouvez simuler à moitié endormi.", "बड़े सवाल, लंबे पैटर्न, ज़्यादा दोहराव, दस राउंड तक। उतना रखें जितना आप आधी नींद में नकल न कर सकें।", "Calcoli più grandi, sequenze più lunghe, più ripetizioni, fino a dieci turni. Imposta oltre ciò che puoi simulare mezzo addormentato.", "より大きな計算、より長いパターン、より多い回数、最大 10 ラウンド。半分寝たままでは誤魔化せない設定に。", "더 큰 계산, 더 긴 패턴, 더 많은 반복, 최대 10라운드. 반쯤 잠든 상태로는 흉내 낼 수 없는 수준으로 올리세요.", "Contas maiores, padrões mais longos, mais repetições, até dez rodadas. Coloque além do que você consegue fingir meio dormindo.", "Примеры сложнее, последовательности длиннее, повторений больше, до десяти раундов. Поставьте выше того, что можно изобразить в полусне.", "更大的算式、更长的序列、更多的次数，最多十轮。设到半梦半醒时装不出来的程度。"],
    "paywall.feature.stats": ["Ninety days of truth", "تسعون يوماً من الحقيقة", "Neunzig Tage Wahrheit", "Noventa días de verdad", "Quatre-vingt-dix jours de vérité", "नब्बे दिन की सच्चाई", "Novanta giorni di verità", "90 日ぶんの事実", "90일간의 진실", "Noventa dias de verdade", "Девяносто дней правды", "九十天的真相"],
    "paywall.feature.stats.body": ["Every wake time, every streak, and every morning you stopped the alarm without doing the mission.", "كل أوقات الاستيقاظ، كل السلاسل، وكل صباح أوقفت فيه المنبه دون إنجاز المهمة.", "Jede Weckzeit, jede Serie und jeder Morgen, an dem du den Alarm ohne Mission gestoppt hast.", "Cada hora de despertar, cada racha y cada mañana en la que paraste la alarma sin hacer la misión.", "Chaque heure de réveil, chaque série, et chaque matin où vous avez arrêté l’alarme sans faire la mission.", "हर जागने का समय, हर सिलसिला, और हर वह सुबह जब आपने मिशन किए बिना अलार्म रोक दिया।", "Ogni ora di risveglio, ogni serie, e ogni mattina in cui hai fermato la sveglia senza fare la missione.", "起床時刻のすべて、連続記録のすべて、そしてミッションをせずにアラームを止めた朝のすべて。", "모든 기상 시각, 모든 연속 기록, 그리고 미션 없이 알람을 끈 모든 아침.", "Cada hora de despertar, cada sequência e cada manhã em que você parou o alarme sem fazer a missão.", "Каждое время подъёма, каждая серия и каждое утро, когда вы выключили будильник без задания.", "每一次起床时间、每一段连续记录，以及每一个你没做任务就关掉闹钟的早晨。"],
    "paywall.cta": ["Get Pro", "احصل على Pro", "Pro holen", "Consigue Pro", "Passer à Pro", "Pro लें", "Passa a Pro", "Pro を入手", "Pro 구매", "Obter o Pro", "Оформить Pro", "获取 Pro"],
    "paywall.cta.note": ["Cancel any time in the App Store. A lifetime purchase is not a subscription and never renews.", "يمكنك الإلغاء في أي وقت من App Store. الشراء الدائم ليس اشتراكاً ولا يُجدَّد.", "Jederzeit im App Store kündbar. Ein Einmalkauf ist kein Abo und verlängert sich nie.", "Cancela cuando quieras en la App Store. La compra para siempre no es una suscripción y nunca se renueva.", "Annulable à tout moment dans l’App Store. L’achat à vie n’est pas un abonnement et ne se renouvelle jamais.", "App Store में कभी भी रद्द करें। लाइफ़टाइम खरीद सब्सक्रिप्शन नहीं है और कभी रिन्यू नहीं होती।", "Puoi annullare quando vuoi nell’App Store. L’acquisto a vita non è un abbonamento e non si rinnova.", "App Store でいつでも解約できます。買い切りはサブスクリプションではなく、更新されません。", "App Store에서 언제든 해지할 수 있습니다. 평생 구매는 구독이 아니며 갱신되지 않습니다.", "Cancele quando quiser na App Store. A compra vitalícia não é assinatura e nunca renova.", "Отменить можно в любой момент в App Store. Пожизненная покупка не подписка и не продлевается.", "可随时在 App Store 取消。终身购买不是订阅，永不自动续费。"],
    "paywall.restore": ["Restore", "استعادة", "Wiederherstellen", "Restaurar", "Restaurer", "रीस्टोर", "Ripristina", "復元", "복원", "Restaurar", "Восстановить", "恢复购买"],
    "paywall.plansUnavailable": ["Prices are not loading. Check your connection and try again.", "الأسعار لا تُحمَّل. تحقق من اتصالك وحاول مرة أخرى.", "Preise laden nicht. Verbindung prüfen und erneut versuchen.", "Los precios no cargan. Comprueba tu conexión e inténtalo de nuevo.", "Les prix ne se chargent pas. Vérifiez votre connexion et réessayez.", "कीमतें लोड नहीं हो रहीं। अपना कनेक्शन जाँचें और फिर कोशिश करें।", "I prezzi non si caricano. Controlla la connessione e riprova.", "価格を読み込めません。通信状況を確認して、もう一度お試しください。", "가격을 불러올 수 없습니다. 연결을 확인한 뒤 다시 시도하세요.", "Os preços não carregam. Verifique sua conexão e tente de novo.", "Цены не загружаются. Проверьте соединение и попробуйте снова.", "无法加载价格。请检查网络后重试。"],
    "paywall.saving": ["−%lld%%", "−%lld%%", "−%lld%%", "−%lld%%", "−%lld%%", "−%lld%%", "−%lld%%", "−%lld%%", "−%lld%%", "−%lld%%", "−%lld%%", "−%lld%%"],
    "paywall.legal": ["Payment is taken by Apple. Subscriptions renew until cancelled; manage or cancel in your App Store account settings.", "الدفع يتم عبر Apple. تتجدد الاشتراكات حتى الإلغاء؛ يمكنك الإدارة أو الإلغاء من إعدادات حسابك في App Store.", "Die Zahlung erfolgt über Apple. Abos verlängern sich bis zur Kündigung; Verwaltung und Kündigung in den App-Store-Kontoeinstellungen.", "El pago lo gestiona Apple. Las suscripciones se renuevan hasta que las canceles; gestiónalas en los ajustes de tu cuenta de App Store.", "Le paiement est encaissé par Apple. Les abonnements se renouvellent jusqu’à résiliation ; gérez-les dans les réglages de votre compte App Store.", "भुगतान Apple लेता है। सब्सक्रिप्शन रद्द होने तक रिन्यू होती रहती है; App Store खाता सेटिंग में प्रबंधित या रद्द करें।", "Il pagamento è gestito da Apple. Gli abbonamenti si rinnovano fino alla disdetta; gestiscili nelle impostazioni del tuo account App Store.", "お支払いは Apple が処理します。サブスクリプションは解約するまで更新されます。App Store のアカウント設定で管理・解約できます。", "결제는 Apple이 처리합니다. 구독은 해지할 때까지 갱신되며, App Store 계정 설정에서 관리하거나 해지할 수 있습니다.", "O pagamento é feito pela Apple. As assinaturas renovam até serem canceladas; gerencie nas configurações da sua conta da App Store.", "Оплату принимает Apple. Подписки продлеваются до отмены; управлять ими можно в настройках аккаунта App Store.", "款项由 Apple 收取。订阅在取消前会自动续费；可在 App Store 账户设置中管理或取消。"],
    "paywall.error.title": ["Purchase problem", "مشكلة في الشراء", "Problem beim Kauf", "Problema con la compra", "Problème d’achat", "खरीद में समस्या", "Problema con l’acquisto", "購入に関する問題", "구매 문제", "Problema na compra", "Проблема с покупкой", "购买出现问题"],
    "paywall.error.unavailable": ["This purchase is not available right now.", "هذا الشراء غير متاح حالياً.", "Dieser Kauf ist gerade nicht verfügbar.", "Esta compra no está disponible ahora mismo.", "Cet achat n’est pas disponible pour le moment.", "यह खरीद अभी उपलब्ध नहीं है।", "Questo acquisto non è disponibile in questo momento.", "この購入は現在利用できません。", "지금은 이 구매를 이용할 수 없습니다.", "Esta compra não está disponível agora.", "Эта покупка сейчас недоступна.", "此项目当前无法购买。"],
    "paywall.error.unverified": ["Apple could not verify the purchase. Nothing was charged.", "لم تتمكن Apple من التحقق من الشراء. لم يتم خصم أي مبلغ.", "Apple konnte den Kauf nicht verifizieren. Es wurde nichts abgebucht.", "Apple no pudo verificar la compra. No se ha cobrado nada.", "Apple n’a pas pu vérifier l’achat. Rien n’a été débité.", "Apple खरीद की पुष्टि नहीं कर सका। कोई शुल्क नहीं लिया गया।", "Apple non ha potuto verificare l’acquisto. Non è stato addebitato nulla.", "Apple が購入を確認できませんでした。請求は発生していません。", "Apple이 구매를 확인할 수 없었습니다. 결제된 금액은 없습니다.", "A Apple não conseguiu verificar a compra. Nada foi cobrado.", "Apple не смогла подтвердить покупку. Списаний не было.", "Apple 无法验证此次购买，未产生任何费用。"],
    "paywall.error.pending": ["Waiting for approval. Pro unlocks as soon as it comes through.", "في انتظار الموافقة. سيُفتح Pro بمجرد وصولها.", "Warten auf Freigabe. Pro schaltet sich frei, sobald sie da ist.", "Esperando aprobación. Pro se activará en cuanto llegue.", "En attente d’approbation. Pro s’activera dès qu’elle arrive.", "मंज़ूरी का इंतज़ार है। मिलते ही Pro चालू हो जाएगा।", "In attesa di approvazione. Pro si attiverà appena arriva.", "承認を待っています。承認されるとすぐに Pro が有効になります。", "승인을 기다리고 있습니다. 승인되면 바로 Pro가 열립니다.", "Aguardando aprovação. O Pro libera assim que chegar.", "Ожидаем подтверждения. Pro откроется, как только оно придёт.", "正在等待批准。批准后 Pro 会立即解锁。"],
    "paywall.error.nothingToRestore": ["No earlier purchase found on this Apple Account.", "لم يُعثر على شراء سابق على حساب Apple هذا.", "Kein früherer Kauf mit diesem Apple-Account gefunden.", "No se encontró ninguna compra anterior en esta cuenta de Apple.", "Aucun achat antérieur trouvé sur ce compte Apple.", "इस Apple खाते पर कोई पुरानी खरीद नहीं मिली।", "Nessun acquisto precedente trovato su questo account Apple.", "この Apple アカウントに過去の購入は見つかりませんでした。", "이 Apple 계정에서 이전 구매를 찾을 수 없습니다.", "Nenhuma compra anterior encontrada nesta conta Apple.", "На этом аккаунте Apple прежних покупок не найдено.", "在此 Apple 账户下未找到此前的购买记录。"],
}

PLANS = family("paywall.plan.", "", {
    "monthly": ["Monthly", "شهري", "Monatlich", "Mensual", "Mensuel", "मासिक", "Mensile", "月額", "월간", "Mensal", "Ежемесячно", "按月"],
    "yearly": ["Yearly", "سنوي", "Jährlich", "Anual", "Annuel", "वार्षिक", "Annuale", "年額", "연간", "Anual", "Ежегодно", "按年"],
    "lifetime": ["Forever", "للأبد", "Für immer", "Para siempre", "À vie", "हमेशा के लिए", "Per sempre", "買い切り", "평생", "Para sempre", "Навсегда", "永久"],
})

# The unit under the price. Short, because it sits in a 60-point column.
PERIODS = family("paywall.period.", "", {
    "day": ["/ day", "/ يوم", "/ Tag", "/ día", "/ jour", "/ दिन", "/ giorno", "/日", "/일", "/ dia", "/ день", "/ 天"],
    "week": ["/ week", "/ أسبوع", "/ Woche", "/ semana", "/ semaine", "/ सप्ताह", "/ settimana", "/週", "/주", "/ semana", "/ неделя", "/ 周"],
    "month": ["/ month", "/ شهر", "/ Monat", "/ mes", "/ mois", "/ महीना", "/ mese", "/月", "/월", "/ mês", "/ месяц", "/ 月"],
    "year": ["/ year", "/ سنة", "/ Jahr", "/ año", "/ an", "/ वर्ष", "/ anno", "/年", "/년", "/ ano", "/ год", "/ 年"],
    "once": ["once", "مرة واحدة", "einmalig", "pago único", "une fois", "एक बार", "una volta", "一回のみ", "1회", "pagamento único", "разово", "一次性"],
})

# The headline, chosen by what the user was doing when the wall appeared. A generic "Go Pro"
# would answer none of these six questions.
REASONS = family("paywall.reason.", "", {
    "alarmLimit": ["One alarm is not a week", "منبه واحد لا يكفي أسبوعاً", "Ein Alarm ist keine Woche", "Una alarma no es una semana", "Une alarme ne fait pas une semaine", "एक अलार्म से पूरा हफ़्ता नहीं चलता", "Una sveglia non è una settimana", "アラーム 1 個で 1 週間は回らない", "알람 하나로는 한 주가 안 됩니다", "Um alarme não é uma semana", "Один будильник — это не неделя", "一个闹钟撑不起一整周"],
    "premiumMission": ["This mission is Pro", "هذه المهمة لمشتركي Pro", "Diese Mission gehört zu Pro", "Esta misión es de Pro", "Cette mission est réservée à Pro", "यह मिशन Pro का है", "Questa missione è Pro", "このミッションは Pro 限定です", "이 미션은 Pro 전용입니다", "Esta missão é do Pro", "Это задание для Pro", "这个任务属于 Pro"],
    "difficulty": ["Harder than medium is Pro", "ما بعد المتوسط لمشتركي Pro", "Schwerer als mittel gibt es mit Pro", "Más que medio es de Pro", "Au-delà de moyen, c’est Pro", "मध्यम से ऊपर Pro में है", "Oltre il medio è Pro", "「ふつう」より上は Pro です", "보통보다 어려운 건 Pro입니다", "Acima de médio é Pro", "Выше среднего — это Pro", "高于中等的难度属于 Pro"],
    "history": ["More than a week is Pro", "أكثر من أسبوع لمشتركي Pro", "Mehr als eine Woche gibt es mit Pro", "Más de una semana es de Pro", "Au-delà d’une semaine, c’est Pro", "एक हफ़्ते से ज़्यादा Pro में है", "Oltre una settimana è Pro", "1 週間より前は Pro です", "한 주 이상은 Pro입니다", "Mais de uma semana é do Pro", "Больше недели — это Pro", "超过一周属于 Pro"],
    "rounds": ["More than one round is Pro", "أكثر من جولة واحدة لمشتركي Pro", "Mehr als eine Runde gibt es mit Pro", "Más de una ronda es de Pro", "Plus d’une manche, c’est Pro", "एक से ज़्यादा राउंड Pro में है", "Più di un turno è Pro", "2 ラウンド以上は Pro です", "라운드를 늘리는 건 Pro입니다", "Mais de uma rodada é Pro", "Больше одного раунда — это Pro", "超过一轮属于 Pro"],
    "manual": ["Dawnbreak Pro", "Dawnbreak Pro", "Dawnbreak Pro", "Dawnbreak Pro", "Dawnbreak Pro", "Dawnbreak Pro", "Dawnbreak Pro", "Dawnbreak Pro", "Dawnbreak Pro", "Dawnbreak Pro", "Dawnbreak Pro", "Dawnbreak Pro"],
})
