"""The keys whose text depends on a number, in every locale's own plural rules.

Emitted with the String Catalog's *substitution* shape rather than a bare
`variations.plural`, because a substitution declares `formatSpecifier` explicitly. That is what
lets a variant leave the numeral out entirely: Arabic's dual is the word `يومان`, not "2 يوم",
and `stats.streak.unit` prints only the noun because the number is already drawn large inside
the progress ring.

`rows` holds one dict per locale, in the same order as `LOCALES`, and its keys must be exactly
that locale's CLDR plural categories — `make_strings.py` refuses anything else, because a
missing `few` in Russian is a bug you only ever see on a Russian device.
"""

PLURALS = {
    # Shown next to the snooze button while the alarm is ringing.
    "mission.snoozesLeft": {
        "name": "snoozes",
        "arg": 1,
        "spec": "lld",
        "rows": [
            {"one": "%lld snooze left", "other": "%lld snoozes left"},
            {
                "zero": "لم يتبقَّ تأجيل",
                "one": "تأجيل واحد متبقٍ",
                "two": "تأجيلان متبقيان",
                "few": "%lld تأجيلات متبقية",
                "many": "%lld تأجيلاً متبقياً",
                "other": "%lld تأجيل متبقٍ",
            },
            {"one": "Noch %lld Mal schlummern", "other": "Noch %lld Mal schlummern"},
            {"one": "Queda %lld posposición", "many": "Quedan %lld posposiciones", "other": "Quedan %lld posposiciones"},
            {"one": "%lld rappel restant", "many": "%lld rappels restants", "other": "%lld rappels restants"},
            {"one": "%lld स्नूज़ बाकी", "other": "%lld स्नूज़ बाकी"},
            {"one": "%lld posticipo rimasto", "many": "%lld posticipi rimasti", "other": "%lld posticipi rimasti"},
            {"other": "スヌーズ残り%lld回"},
            {"other": "다시 알림 %lld회 남음"},
            {"one": "Resta %lld soneca", "many": "Restam %lld sonecas", "other": "Restam %lld sonecas"},
            {
                "one": "Осталось %lld откладывание",
                "few": "Осталось %lld откладывания",
                "many": "Осталось %lld откладываний",
                "other": "Осталось %lld откладывания",
            },
            {"other": "还能小睡 %lld 次"},
        ],
    },
    # The word under the streak ring. No numeral: the count is the 26-point number above it.
    "stats.streak.unit": {
        "name": "days",
        "arg": 1,
        "spec": "lld",
        "rows": [
            {"one": "day", "other": "days"},
            {"zero": "يوم", "one": "يوم", "two": "يومان", "few": "أيام", "many": "يوماً", "other": "يوم"},
            {"one": "Tag", "other": "Tage"},
            {"one": "día", "many": "días", "other": "días"},
            {"one": "jour", "many": "jours", "other": "jours"},
            {"one": "दिन", "other": "दिन"},
            {"one": "giorno", "many": "giorni", "other": "giorni"},
            {"other": "日"},
            {"other": "일"},
            {"one": "dia", "many": "dias", "other": "dias"},
            {"one": "день", "few": "дня", "many": "дней", "other": "дня"},
            {"other": "天"},
        ],
    },
    # The editor's one-line summary, for the numbers a difficulty can produce. Plural because
    # "Calculs à 1 chiffres" and "3 приседаний" are what the flat strings said on Easy.
    "preview.math": {
        "name": "digits",
        "arg": 1,
        "spec": "lld",
        "rows": [
            {"one": "%lld-digit sums", "other": "%lld-digit sums"},
            {
                "zero": "أعداد من %lld خانة",
                "one": "أعداد من خانة واحدة",
                "two": "أعداد من خانتين",
                "few": "أعداد من %lld خانات",
                "many": "أعداد من %lld خانة",
                "other": "أعداد من %lld خانة",
            },
            {"one": "%lld-stellige Aufgaben", "other": "%lld-stellige Aufgaben"},
            {"one": "Cuentas de %lld cifra", "many": "Cuentas de %lld cifras", "other": "Cuentas de %lld cifras"},
            {"one": "Calculs à %lld chiffre", "many": "Calculs à %lld chiffres", "other": "Calculs à %lld chiffres"},
            {"one": "%lld अंक के सवाल", "other": "%lld अंकों के सवाल"},
            {"one": "Calcoli a %lld cifra", "many": "Calcoli a %lld cifre", "other": "Calcoli a %lld cifre"},
            {"other": "%lld桁の計算"},
            {"other": "%lld자리 계산"},
            {"one": "Contas de %lld dígito", "many": "Contas de %lld dígitos", "other": "Contas de %lld dígitos"},
            {
                "one": "Примеры с %lld-значными числами",
                "few": "Примеры с %lld-значными числами",
                "many": "Примеры с %lld-значными числами",
                "other": "Примеры с %lld-значными числами",
            },
            {"other": "%lld 位数运算"},
        ],
    },
    "preview.sequence": {
        "name": "steps",
        "arg": 1,
        "spec": "lld",
        "rows": [
            {"one": "%lld-step pattern", "other": "%lld-step pattern"},
            {
                "zero": "نمط من %lld خطوة",
                "one": "نمط من خطوة واحدة",
                "two": "نمط من خطوتين",
                "few": "نمط من %lld خطوات",
                "many": "نمط من %lld خطوة",
                "other": "نمط من %lld خطوة",
            },
            {"one": "Muster mit %lld Schritt", "other": "Muster mit %lld Schritten"},
            {"one": "Patrón de %lld paso", "many": "Patrón de %lld pasos", "other": "Patrón de %lld pasos"},
            {"one": "Motif de %lld étape", "many": "Motif de %lld étapes", "other": "Motif de %lld étapes"},
            {"one": "%lld चरण का पैटर्न", "other": "%lld चरणों का पैटर्न"},
            {"one": "Sequenza di %lld passo", "many": "Sequenza di %lld passi", "other": "Sequenza di %lld passi"},
            {"other": "%lldステップのパターン"},
            {"other": "%lld단계 패턴"},
            {"one": "Padrão de %lld passo", "many": "Padrão de %lld passos", "other": "Padrão de %lld passos"},
            {
                "one": "Рисунок из %lld шага",
                "few": "Рисунок из %lld шагов",
                "many": "Рисунок из %lld шагов",
                "other": "Рисунок из %lld шага",
            },
            {"other": "%lld 步的图案"},
        ],
    },
    "preview.typing": {
        "name": "words",
        "arg": 1,
        "spec": "lld",
        "rows": [
            {"one": "Sentences of about %lld words", "other": "Sentences of about %lld words"},
            {
                "zero": "جمل من نحو %lld كلمة",
                "one": "جمل من نحو كلمة واحدة",
                "two": "جمل من نحو كلمتين",
                "few": "جمل من نحو %lld كلمات",
                "many": "جمل من نحو %lld كلمة",
                "other": "جمل من نحو %lld كلمة",
            },
            {"one": "Sätze mit etwa %lld Wort", "other": "Sätze mit etwa %lld Wörtern"},
            {"one": "Frases de %lld palabra", "many": "Frases de unas %lld palabras", "other": "Frases de unas %lld palabras"},
            {"one": "Phrases d’environ %lld mot", "many": "Phrases d’environ %lld mots", "other": "Phrases d’environ %lld mots"},
            {"one": "लगभग %lld शब्द के वाक्य", "other": "लगभग %lld शब्दों के वाक्य"},
            {"one": "Frasi di circa %lld parola", "many": "Frasi di circa %lld parole", "other": "Frasi di circa %lld parole"},
            {"other": "約%lld語の文章"},
            {"other": "약 %lld 단어 문장"},
            {"one": "Frases de cerca de %lld palavra", "many": "Frases de cerca de %lld palavras", "other": "Frases de cerca de %lld palavras"},
            {
                "one": "Фразы примерно из %lld слова",
                "few": "Фразы примерно из %lld слов",
                "many": "Фразы примерно из %lld слов",
                "other": "Фразы примерно из %lld слова",
            },
            {"other": "约 %lld 个词的句子"},
        ],
    },
    "preview.squats": {
        "name": "squats",
        "arg": 1,
        "spec": "lld",
        "rows": [
            {"one": "%lld squat", "other": "%lld squats"},
            {
                "zero": "%lld تمرين قرفصاء",
                "one": "تمرين قرفصاء واحد",
                "two": "تمرينا قرفصاء",
                "few": "%lld تمارين قرفصاء",
                "many": "%lld تمرين قرفصاء",
                "other": "%lld تمرين قرفصاء",
            },
            {"one": "%lld Kniebeuge", "other": "%lld Kniebeugen"},
            {"one": "%lld sentadilla", "many": "%lld sentadillas", "other": "%lld sentadillas"},
            {"one": "%lld squat", "many": "%lld squats", "other": "%lld squats"},
            {"one": "%lld स्क्वैट", "other": "%lld स्क्वैट"},
            {"one": "%lld squat", "many": "%lld squat", "other": "%lld squat"},
            {"other": "スクワット%lld回"},
            {"other": "스쿼트 %lld회"},
            {"one": "%lld agachamento", "many": "%lld agachamentos", "other": "%lld agachamentos"},
            {
                "one": "%lld приседание",
                "few": "%lld приседания",
                "many": "%lld приседаний",
                "other": "%lld приседания",
            },
            {"other": "深蹲 %lld 次"},
        ],
    },
    "preview.flap": {
        "name": "gaps",
        "arg": 1,
        "spec": "lld",
        "rows": [
            {"one": "%lld gap to clear", "other": "%lld gaps to clear"},
            {
                "zero": "%lld فتحة لتعبرها",
                "one": "فتحة واحدة لتعبرها",
                "two": "فتحتان لتعبرهما",
                "few": "%lld فتحات لتعبرها",
                "many": "%lld فتحة لتعبرها",
                "other": "%lld فتحة لتعبرها",
            },
            {"one": "%lld Lücke schaffen", "other": "%lld Lücken schaffen"},
            {"one": "%lld hueco que pasar", "many": "%lld huecos que pasar", "other": "%lld huecos que pasar"},
            {"one": "%lld passage à franchir", "many": "%lld passages à franchir", "other": "%lld passages à franchir"},
            {"one": "%lld गैप पार करना है", "other": "%lld गैप पार करने हैं"},
            {"one": "%lld apertura da superare", "many": "%lld aperture da superare", "other": "%lld aperture da superare"},
            {"other": "隙間%lld個を通過"},
            {"other": "틈 %lld개 통과"},
            {"one": "%lld vão para passar", "many": "%lld vãos para passar", "other": "%lld vãos para passar"},
            {
                "one": "%lld проход",
                "few": "%lld прохода",
                "many": "%lld проходов",
                "other": "%lld прохода",
            },
            {"other": "穿过 %lld 个缝隙"},
        ],
    },
    "preview.breathe": {
        "name": "breaths",
        "arg": 1,
        "spec": "lld",
        "rows": [
            {"one": "%lld guided breath", "other": "%lld guided breaths"},
            {
                "zero": "%lld نفس موجّه",
                "one": "نفس موجّه واحد",
                "two": "نفسان موجّهان",
                "few": "%lld أنفاس موجّهة",
                "many": "%lld نفساً موجّهاً",
                "other": "%lld نفس موجّه",
            },
            {"one": "%lld geführter Atemzug", "other": "%lld geführte Atemzüge"},
            {"one": "%lld respiración guiada", "many": "%lld respiraciones guiadas", "other": "%lld respiraciones guiadas"},
            {"one": "%lld respiration guidée", "many": "%lld respirations guidées", "other": "%lld respirations guidées"},
            {"one": "%lld निर्देशित साँस", "other": "%lld निर्देशित साँसें"},
            {"one": "%lld respiro guidato", "many": "%lld respiri guidati", "other": "%lld respiri guidati"},
            {"other": "ガイド付き呼吸%lld回"},
            {"other": "안내 호흡 %lld회"},
            {"one": "%lld respiração guiada", "many": "%lld respirações guiadas", "other": "%lld respirações guiadas"},
            {
                "one": "%lld направляемый вдох",
                "few": "%lld направляемых вдоха",
                "many": "%lld направляемых вдохов",
                "other": "%lld направляемого вдоха",
            },
            {"other": "%lld 次引导呼吸"},
        ],
    },
    # Joined to the summary with a mid-dot by the editor, only when there is more than one.
    "preview.rounds": {
        "name": "rounds",
        "arg": 1,
        "spec": "lld",
        "rows": [
            {"one": "%lld round", "other": "%lld rounds"},
            {
                "zero": "%lld جولة",
                "one": "جولة واحدة",
                "two": "جولتان",
                "few": "%lld جولات",
                "many": "%lld جولة",
                "other": "%lld جولة",
            },
            {"one": "%lld Runde", "other": "%lld Runden"},
            {"one": "%lld ronda", "many": "%lld rondas", "other": "%lld rondas"},
            {"one": "%lld manche", "many": "%lld manches", "other": "%lld manches"},
            {"one": "%lld राउंड", "other": "%lld राउंड"},
            {"one": "%lld turno", "many": "%lld turni", "other": "%lld turni"},
            {"other": "%lldラウンド"},
            {"other": "%lld라운드"},
            {"one": "%lld rodada", "many": "%lld rodadas", "other": "%lld rodadas"},
            {
                "one": "%lld раунд",
                "few": "%lld раунда",
                "many": "%lld раундов",
                "other": "%lld раунда",
            },
            {"other": "%lld 轮"},
        ],
    },
    # The flame on the done screen, shown from two mornings on. Russian counts days, as the
    # streak ring does: "5 утр подряд" is grammatical and nobody says it.
    "mission.done.streak": {
        "name": "mornings",
        "arg": 1,
        "spec": "lld",
        "rows": [
            {"one": "%lld morning in a row", "other": "%lld mornings in a row"},
            {
                "zero": "%lld صباح على التوالي",
                "one": "صباح واحد على التوالي",
                "two": "صباحان على التوالي",
                "few": "%lld صباحات على التوالي",
                "many": "%lld صباحاً على التوالي",
                "other": "%lld صباح على التوالي",
            },
            {"one": "%lld Morgen in Folge", "other": "%lld Morgen in Folge"},
            {"one": "%lld mañana seguida", "many": "%lld mañanas seguidas", "other": "%lld mañanas seguidas"},
            {"one": "%lld matin d’affilée", "many": "%lld matins d’affilée", "other": "%lld matins d’affilée"},
            {"one": "लगातार %lld सुबह", "other": "लगातार %lld सुबह"},
            {"one": "%lld mattina di fila", "many": "%lld mattine di fila", "other": "%lld mattine di fila"},
            {"other": "%lld日連続"},
            {"other": "%lld일 연속"},
            {"one": "%lld manhã seguida", "many": "%lld manhãs seguidas", "other": "%lld manhãs seguidas"},
            {
                "one": "%lld день подряд",
                "few": "%lld дня подряд",
                "many": "%lld дней подряд",
                "other": "%lld дня подряд",
            },
            {"other": "连续 %lld 个早晨"},
        ],
    },
}
