import { join } from 'path';
import { Duration, RemovalPolicy } from 'aws-cdk-lib';
import { Certificate, CertificateValidation } from 'aws-cdk-lib/aws-certificatemanager';
import {
  AllowedMethods,
  CachePolicy,
  Distribution,
  Function as CloudFrontFunction,
  FunctionCode,
  FunctionEventType,
  HeadersFrameOption,
  HeadersReferrerPolicy,
  HttpVersion,
  PriceClass,
  ResponseHeadersPolicy,
  ViewerProtocolPolicy,
} from 'aws-cdk-lib/aws-cloudfront';
import { S3BucketOrigin } from 'aws-cdk-lib/aws-cloudfront-origins';
import { ARecord, AaaaRecord, IHostedZone, RecordTarget } from 'aws-cdk-lib/aws-route53';
import { CloudFrontTarget } from 'aws-cdk-lib/aws-route53-targets';
import { BlockPublicAccess, Bucket, BucketEncryption, ObjectOwnership } from 'aws-cdk-lib/aws-s3';
import { BucketDeployment, CacheControl, Source } from 'aws-cdk-lib/aws-s3-deployment';
import { Construct } from 'constructs';

export interface StaticSiteProps {
  /** The apex the certificate is issued for and the alias records point at. */
  readonly domainName: string;
  /** Created by `DnsStack`, imported by the stack, passed here as an object. */
  readonly zone: IHostedZone;
  /** The directory whose contents become the site. Generated by `scripts/make_pages.py`. */
  readonly contentPath: string;
}

/**
 * The public pages, served over HTTPS from a bucket nothing can read directly.
 *
 * Three things make this more than a bucket. `.app` is in the HSTS preload list, so a browser will
 * not even try HTTP against this domain and a certificate is not optional. Apple opens the privacy
 * policy during review and a 404 there is a rejection, so the paths the app compiles in have to
 * resolve exactly. And the pages are generated files checked into the repository, so the deployment
 * is a copy of `docs/` rather than anything with a build step.
 */
export class StaticSite extends Construct {
  public readonly distribution: Distribution;
  public readonly bucket: Bucket;

  private readonly props: StaticSiteProps;

  constructor(scope: Construct, id: string, props: StaticSiteProps) {
    super(scope, id);
    this.props = props;

    this.bucket = this.createBucket();
    this.distribution = this.createDistribution(this.createCertificate());
    this.createRecords();
    this.deployContent();
  }

  /**
   * Private, encrypted, and reachable only through the distribution's origin access control. The
   * pages are public information, but a public bucket is a public bucket: it would answer on an
   * s3.amazonaws.com URL that carries no certificate for this domain and no HSTS.
   */
  protected createBucket(): Bucket {
    return new Bucket(this, 'Content', {
      blockPublicAccess: BlockPublicAccess.BLOCK_ALL,
      encryption: BucketEncryption.S3_MANAGED,
      enforceSSL: true,
      objectOwnership: ObjectOwnership.BUCKET_OWNER_ENFORCED,
      versioned: true,
      // The pages can be regenerated from `scripts/make_pages.py` in one command, so nothing here
      // is irreplaceable; a retained bucket after a `cdk destroy` is just litter to clean by hand.
      removalPolicy: RemovalPolicy.DESTROY,
      autoDeleteObjects: true,
    });
  }

  /** Covers the apex and `www`, validated by a record this stack writes into the zone. */
  protected createCertificate(): Certificate {
    return new Certificate(this, 'Certificate', {
      domainName: this.props.domainName,
      subjectAlternativeNames: [`www.${this.props.domainName}`],
      validation: CertificateValidation.fromDns(this.props.zone),
    });
  }

  protected createDistribution(certificate: Certificate): Distribution {
    return new Distribution(this, 'Distribution', {
      defaultBehavior: {
        origin: S3BucketOrigin.withOriginAccessControl(this.bucket),
        viewerProtocolPolicy: ViewerProtocolPolicy.REDIRECT_TO_HTTPS,
        allowedMethods: AllowedMethods.ALLOW_GET_HEAD,
        cachePolicy: CachePolicy.CACHING_OPTIMIZED,
        responseHeadersPolicy: this.createHeadersPolicy(),
        functionAssociations: [
          {
            function: this.createUriRewriter(),
            eventType: FunctionEventType.VIEWER_REQUEST,
          },
        ],
      },
      domainNames: [this.props.domainName, `www.${this.props.domainName}`],
      certificate,
      defaultRootObject: 'index.html',
      httpVersion: HttpVersion.HTTP2_AND_3,
      // Three pages of text in twelve languages. Paying for edge locations in every region on
      // earth to serve 200 KB of HTML would be spending money to look thorough.
      priceClass: PriceClass.PRICE_CLASS_100,
      enableLogging: false,
      comment: `${this.props.domainName}: privacy, terms and support`,
      errorResponses: [
        {
          httpStatus: 403,
          responseHttpStatus: 404,
          responsePagePath: '/index.html',
          ttl: Duration.minutes(5),
        },
      ],
    });
  }

  /**
   * Makes `/privacy` serve `/privacy.html`.
   *
   * The app and the listing link the `.html` names, which S3 serves as they are. The stack's own
   * outputs and anyone typing the address use the short form, and S3 has no notion of one path
   * standing for another, so without this they 404.
   */
  protected createUriRewriter(): CloudFrontFunction {
    return new CloudFrontFunction(this, 'Rewrite', {
      comment: 'Append .html to extensionless paths',
      code: FunctionCode.fromInline(`
function handler(event) {
  var request = event.request;
  var uri = request.uri;
  if (uri.endsWith('/')) {
    request.uri = uri + 'index.html';
    return request;
  }
  var last = uri.substring(uri.lastIndexOf('/') + 1);
  if (last.indexOf('.') === -1) {
    request.uri = uri + '.html';
  }
  return request;
}
`),
    });
  }

  /**
   * HSTS above all, with a two-year age and preload: `.app` is preloaded as a TLD, so anything less
   * would be the one host on the domain pretending HTTP is possible.
   */
  protected createHeadersPolicy(): ResponseHeadersPolicy {
    return new ResponseHeadersPolicy(this, 'Headers', {
      securityHeadersBehavior: {
        strictTransportSecurity: {
          accessControlMaxAge: Duration.days(730),
          includeSubdomains: true,
          preload: true,
          override: true,
        },
        contentTypeOptions: { override: true },
        frameOptions: { frameOption: HeadersFrameOption.DENY, override: true },
        referrerPolicy: {
          referrerPolicy: HeadersReferrerPolicy.STRICT_ORIGIN_WHEN_CROSS_ORIGIN,
          override: true,
        },
      },
    });
  }

  protected createRecords(): void {
    const target = RecordTarget.fromAlias(new CloudFrontTarget(this.distribution));
    for (const [id, recordName] of [
      ['Apex', undefined],
      ['Www', 'www'],
    ] as const) {
      new ARecord(this, `${id}A`, { zone: this.props.zone, recordName, target });
      new AaaaRecord(this, `${id}Aaaa`, { zone: this.props.zone, recordName, target });
    }
  }

  /**
   * Copies `docs/` up and invalidates the edge.
   *
   * A short cache on the HTML is deliberate. These pages carry the privacy claims the App Store
   * listing links, and when one of them is wrong the fix has to be visible to a reviewer in
   * minutes, not after a day of cached copies.
   */
  protected deployContent(): void {
    new BucketDeployment(this, 'Deployment', {
      sources: [Source.asset(join(__dirname, '..', '..', this.props.contentPath))],
      destinationBucket: this.bucket,
      distribution: this.distribution,
      distributionPaths: ['/*'],
      prune: true,
      cacheControl: [CacheControl.setPublic(), CacheControl.maxAge(Duration.minutes(5))],
    });
  }
}
